### ISSUE TITLE
PSF convolution: analytic vs galsim

### ISSUE THREAD

**Issue by cosmicshear** [GalSim-developers/GalSim#1004]
I have a gaussian galaxy with known half light radius and shape. I want to convolve it with a simple gaussian PSF using two methods:

1. Directly using galsim.Convolve
2. Adding the PSF moments to galaxy moments to get the convolved shape where I simply consider

> size_convolved = sqrt(size_original^2 + psf_size^2)

Here are my results for a fixed 55 by 55 pixels postage stamp:

![image_original](https://user-images.githubusercontent.com/2823824/51645946-439e1880-1f2b-11e9-88a6-d94b0fbc291b.png)
![image_analytic_psf](https://user-images.githubusercontent.com/2823824/51645947-439e1880-1f2b-11e9-816b-ab161238eb23.png)
![image_galsim_psf](https://user-images.githubusercontent.com/2823824/51645948-439e1880-1f2b-11e9-86e1-fd4a53a21a63.png)

If I take the difference between the pixel values of the analytically-convolved and galsim-convolved images I get:

![difference_image](https://user-images.githubusercontent.com/2823824/51647070-30417c00-1f30-11e9-86d2-0bbd3511c230.png)

And also its histogram:

![difference](https://user-images.githubusercontent.com/2823824/51646660-5e25c100-1f2e-11e9-9229-cb15c2ab57d2.png)

Why are they different? The analytically-convolved one looks more concentrated around the center and a bit more elongated. I checked my analytic method but couldn't find any problem. I am thinking maybe it is fine and there must be some assumptions in galsim that I am not aware of.

**Comment by rmandelb** [comment]
In general, when you do `galsim.Convolve(gal, psf)` and then draw into an image using `drawImage`, GalSim is quietly convolving with the top-hat pixel response function.  The resulting adaptive moments measured from the image will therefore include the contribution from the top-hat pixel response, but it shouldn't be present in the analytic calculation of galaxy + PSF moments only.   As a result, your  calculation is not an apples-to-apples one; the analytic one should be more elongated  and centrally concentrated, which is exactly what you've found.

If you shut off the convolution by the pixel response, then you should find the calculations agree, because that is a fair comparison.

**Comment by rmjarvis** [comment]
I think both cases here include the pixel response, so I don't think that's the explanation.  Erfan, could you post the script you are doing in each case?  My guess is that your analytic calculation isn't quite right.  But it's hard for me to guess what is wrong with it just from looking at the image.

**Comment by rmandelb** [comment]
Right, we'd need to know how was he defining "PSF moments" and "galaxy moments" in that equation.  I assumed he was using the analytic equation for them based on the sigma of the Gaussian that he is inputting into GalSim when instantiating the PSF and galaxy objects.  If that's the case, the analytic calculation has no pixel response in it, and the images do.  But seeing the script would tell us for sure :)

**Comment by jmeyers314** [comment]
I agree it would be good to see Erfan's script.  (Here's another potential source of error: both size _and ellipticity_ need to be modified when going from galaxy -> convolved surface brightness profile).

FWIW though, I can't get this to work as well as I think it ought to either.  Here's my notebook: https://gist.github.com/jmeyers314/8cf7542ffd470ce29684daa01c82ac6f

**Comment by rmandelb** [comment]
Interesting.  So you are doing it the way Mike mentioned (i.e., including pixel response in both the analytic and direct) version, not the way I thought Erfan was doing (pure analytic without any drawing at all).

I have a deadline so can't dig into this, but I distinctly recall that some of the tests in `test_hsm.py` specifically test that the adaptive moments can recover analytic predictions when drawing Gaussians, which might enable us to rule out some steps in this process as part of the problem?  You  might want to take a look there.

**Comment by esheldon** [comment]
FWIW, ngmix, which does analytic convolutions, agrees with galsim within 1.0e-7 when there is no pixel.

![compare](https://user-images.githubusercontent.com/621661/51704401-fb443080-1fe6-11e9-9175-950a24742938.png)

**Comment by jmeyers314** [comment]
Huh, okay.  That would point to there being something naïve in my notebook then.  Thanks.

**Comment by esheldon** [comment]
@jmeyers314  Did you notice that no pixel was used?  ngmix doesn't integrate over pixels so I can't test that part. Maybe it is related to the tophat convolution.  Can you run your notebook with `no_pixel`?

**Comment by jmeyers314** [comment]
Yeah, I tried all the variations of method='fft', 'no_pixel', 'sb' already.  They all yield similar residuals.

**Comment by jmeyers314** [comment]
Okay, I realized my mistake.  T = Ixx + Iyy is not constant under an applied shear, so I'm using the wrong strategy to realize Gaussian profiles with a desired set of second moments...

**Comment by jmeyers314** [comment]
I updated the [gist](https://gist.github.com/jmeyers314/8cf7542ffd470ce29684daa01c82ac6f).  

Analytic now agrees with galsim to ~1e-10.  @cosmicshear , thanks for asking (I (re-)learned something here); hopefully some of the discussion and maybe the linked notebook answers your question?  If not, please feel free to ask your question another way and of course to post your script.  

Also, this feels like a nice unit test; we should add it! (if it's not buried in the tests already.)

**Comment by rmjarvis** [comment]
I think [this test](https://github.com/GalSim-developers/GalSim/blob/releases/2.1/tests/test_hsm.py#L190) is the closest we have to testing this kind of thing.  But I think it would be fine to add another test, maybe in test_shear.py, that recapitulates your gist.

**Comment by cosmicshear** [comment]
Thank you all for your helpful responses. [Here](https://github.com/cosmicshear/galsim_sims/blob/master/Jupyter%20notebooks/psf_convolution.ipynb) is my notebook. I think it needs some corrections.

**Comment by cosmicshear** [comment]
Just for the record, these are the things I have done to get the best agreement (the combination of the first two solved the problem and the last one is just an improvement):

1. It turns out that my assumption of

```
size_convolved = sqrt(size_original^2 + psf_size^2)
```

was not exactly correct. I didn't notice that until I got the galaxy size from the convolved moments that did not agree with the value above (you can see the comparison in my notebook).

2. My method uses the shape covariance matrix of the galaxies to do the convolution. In order to produce this matrix given the galaxy half light radius `gal_hlr` and ellipticity `gamma`, I need to get two values for the sigma (they will be the same for round galaxies). Using the analogy of shearing a circle to make an ellipse, I was using:

```
sigma_R = gal_hlr / np.sqrt(2.*np.log(2))
sigma_a = sigma_R /(1-gamma)
sigma_b = sigma_R /(1+gamma)
```

which was not quite right because it makes the area of the produced ellipse (with semi-major and semi-minor axes of `sigma_a` and `sigma_b`) bigger than the area of the original circle (of radius `sigma_R`). To preserve the area and not having this magnification effect we need to make sure `sigma_a*sigma_b = sigma_R^2`. This can be achieved by the following:

```
sigma_R = gal_hlr / np.sqrt(2.*np.log(2))
sigma_a = sigma_R * np.sqrt((1+gamma)/(1-gamma))
sigma_b = sigma_R * np.sqrt((1-gamma)/(1+gamma))
```


I basically multiplied my old `sigma_a ` and `sigma_b` values by `mu_inv = np.sqrt(1-gamma**2)`.

3. I used the same conservative GSParams as @jmeyers314's [gist](https://gist.github.com/jmeyers314/8cf7542ffd470ce29684daa01c82ac6f).

__Please let me know if there are any holes in my argument.__

I updated my [notebook](https://github.com/cosmicshear/galsim_sims/blob/master/Jupyter%20notebooks/psf_convolution.ipynb) and here are the new results showing a nice agreement between my analysis and GalSim.

![unknown-28](https://user-images.githubusercontent.com/2823824/52517686-a6fa9c80-2bf3-11e9-9007-bf4a1a115ca9.png)
![unknown-29](https://user-images.githubusercontent.com/2823824/52517687-a6fa9c80-2bf3-11e9-81e0-b5c9f9c9087a.png)
![unknown-30](https://user-images.githubusercontent.com/2823824/52517688-a7933300-2bf3-11e9-95ea-7a29fd7042e3.png)
![unknown-31](https://user-images.githubusercontent.com/2823824/52517689-a7933300-2bf3-11e9-8733-797eaef8364b.png)
