### ISSUE TITLE
Make shared atmospheric screens safer for multiprocessing

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1006]
In [ImSim](https://github.com/LSSTDESC/imSim), the LSST DESC currently uses a *nix copy-on-write + fork() trick to effectively put read-only atmospheric screens into shared memory where multiple processes can access them.  I've done some experimenting over the past few days and determined that this trick breaks when switching the process initialization from fork() to fork()+exec().  Unfortunately, as pointed out in #998, fork()+exec() initialization is required for subprocess thread safety, which includes any future OpenMP optimization inside GalSim, for example.

I think it's possible to solve this by modifying how atmospheric screens are stored in GalSim.  I've found that using the multiprocessing.Array and RawArray abstractions do permit shared memory access under fork()+exec() subprocess initialization, and that it's relatively straightforward to cast either of these to a numpy ndarray through the buffer interface (See [this blog post](https://research.wmz.ninja/articles/2018/03/on-sharing-large-arrays-when-using-pythons-multiprocessing.html) for an example).  

So we could either 1) make AtmosphericScreen always use a multiprocessing Array under the hood, even when there's no multiprocessing being done, or 2) add an alternative AtmosphericScreen constructor that accepts an externally-generated RawArray (or maybe numpy array that wraps a RawArray?, I'd have to experiment...), i.e., enable the user to handle shared memory outside of GalSim.  

I think I prefer option 1) if I can get it to work (not yet clear...), but either way, some GalSim development seems to be required (sans monkey-patching), which is why I'm raising this issue here instead of in ImSim.

As a bonus, I think this work could also enable generating multiple screens concurrently, which would speed up the startup times for jobs that rely on large screens.

**Comment by rmjarvis** [comment]
If there is no runtime overhead, option 1 sounds good.  But if not, we would probably want this to be optional.  E.g. an optional kwarg to the constructor.

**Comment by jmeyers314** [comment]
The following script demonstrates a _mostly_ working example of how I think this could work:

```python
import os
import multiprocessing as mp
import numpy as np
import ctypes
import time
import hashlib
from galsim.utilities import lazy_property

# Global variable to hold shared memory variables.  We'll form key-value pairs here 
# linking Atm objects to their particular shared memory object.
_share = {}


class Atm:
    def __init__(self, i, shape):
        self.i = i
        self.shape = shape

        # Setup shared state variable.  We'll fill it in lazily as needed later
        size = 1
        for s in shape:
            size *= s
        _share[self._hash] = {
            'initialized':mp.RawValue(ctypes.c_bool, False),
            'mpArr':mp.Array(ctypes.c_double, size)
        }

    # Note hash() function is process-dependent through a random salt in python 3.3+, so
    # we don't want to use it for a shared dictionary key.
    def __hash__(self):
        return hash(("DummyAtm", self.i))

    # Use hashlib for a process-independent hash
    @lazy_property
    def _hash(self):
        m = hashlib.sha256()
        m.update(bytes(repr(self), encoding='latin-1'))
        return m.digest()

    def __repr__(self):
        return "DummyAtm({!r}, {!r})".format(self.i, self.shape)

    @lazy_property
    def arr(self):
        d = _share[self._hash]
        if not d['initialized'].value:
            with d['mpArr'].get_lock():
                if not d['initialized'].value:
                    print("initializing {}".format(self))
                    arr = np.frombuffer(
                        d['mpArr'].get_obj(), dtype=np.float64
                    ).reshape(self.shape)
                    arr[:] = self.i
                    d['initialized'].value = True
        return np.frombuffer(
            d['mpArr'].get_obj(), dtype=np.float64
        ).reshape(self.shape)

    # Make sure to not include shared state in pickle.  We don't want to be passing that
    # around in the Pool methods.
    def __getstate__(self):
        return self.i, self.shape

    def __setstate__(self, args):
        self.i, self.shape = args

def initWorkerArgs():
    return (_share,)

def initWorker(share):
    _share.update(share)

def work(i, atm):
    time.sleep(0.5)
    print(i, atm.arr[0,0]*i+1)

def main():
    DIM1 = 8192*8192
    DIM2 = 6
    shape1 = (DIM1, DIM2)  # 3 GB
    shape2 = (DIM1//2, DIM2//2)  # 0.75 GB

    atm1 = Atm(1.5, shape1)
    atm2 = Atm(2.5, shape2)

    # We can instantiate in the parent process, or lazily in the child process...
    print(atm1.arr[0,0])  # uncomment to instantiate in parent process
    print(atm2.arr[1,1])

    with mp.get_context("spawn").Pool(
        10, initializer=initWorker, initargs=initWorkerArgs()
    ) as pool:
        results = []
        for i in range(50):
            results.append(pool.apply_async(work, (i, atm1)))
            results.append(pool.apply_async(work, (i, atm2)))
        for r in results:
            r.wait()


if __name__ == '__main__':
    main()
```

The `Atm` instances allocate their shared memory blocks in the initializer, but don't fill them until later (we prefer this strategy for `AtmosphericScreen` since the screen values depends on whether you're drawing with the geometric approximation or not).  At the moment, the script fills in the screens in the parent process before making the `Pool`.  The `initializer` and `initargs` arguments to `Pool` are used to place the shared memory wrappers into a process-dependent global variable at the time of child process creation, indexed by a hash of the Atm instance so we can reattach the right array to the right Atm later.  The `Atm` instances then know to look there when a worker requests access to the shared array.  This all works with the "spawn" context, which I believe makes it safe to use threads in the subprocesses.

One thing I haven't figured out yet is how to enable the child processes to fill in the shared memory arrays on demand if they weren't already filled in by the parent process.  My intention was for the lock context manager in the `.arr` lazy_property to handle this, but when I try it out, I always get a "bad file descriptor" error.  My guess is that python is using file descriptors for the locks, and that they become out-of-sync when a new process is `exec`'d.  It's a bit funny though, because everything works if there's only one `Atm` instance.  It's always the second instance that leads to the error.  Maybe there's a better way to pass the locks around...

In the meantime, however, I think this works if you're willing to prefill the screens in the parent process, or if you're multiprocessing with "fork" instead of "spawn", or if you're not multiprocessing at all.

**Comment by jmeyers314** [comment]
>One thing I haven't figured out yet is how to enable the child processes to fill in the shared memory arrays on demand if they weren't already filled in by the parent process.

I figured it out.  I needed to indicate the "spawn" context throughout the script, not just when creating the `Pool`.  Adding `mp = mp.get_context("spawn")` just under the imports above makes everything work as intended.

**Comment by jmeyers314** [comment]
FWIW, this may all get easier in python 3.8: https://docs.python.org/dev/library/multiprocessing.shared_memory.html, though I suspect it will be quite a long time before we can deprecate 3.7...!
