### ISSUE TITLE
compilation with scons fails on 'coords' module

### ISSUE THREAD

**Issue by DavidJJansen** [GalSim-developers/GalSim#1007]
Tying to compile GalSim 2.1 using scons on both Fedora 29 and RedHat Enterprise 7.6, the configuration halts when unable to import a coords module in python:

$ scons PREFIX=/software/local
scons: Reading SConscript files ...
SCons is version 3.0.1 using python version 2.7.15
Python is from /usr/include/python2.7
Using the following (non-default) scons options:
   PREFIX = /software/local
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /usr/bin/python
Using PYPREFIX generated from PREFIX =  /software/local/lib/python2.7/site-packages
Using compiler: /usr/bin/g++
compiler version: 8.2.1
Determined that a good number of jobs = 4
Using SSE with flag -msse2
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for C++ header file Eigen/Core... no
Trying eigency installation:  /software/local/lib64/python2.7/site-packages/eigency/eigen_3.2.8
Checking for C++ header file Eigen/Core... yes
Checking if we can build against Python... yes
Building for python version 2.7
Checking if we can build module using Eigen... yes
Eigen version is 3.2.8
Checking if we can build against NumPy... yes
Numpy version is 1.16.1
Checking for astropy.io.fits... yes
Astropy version is 2.0.8
Checking for future... yes
Future version is 0.16.0
Checking for coord... 
Unable to import coord using the python executable:
/usr/bin/python

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at 
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ

If nothing there seems helpful, feel free to post an issue here:
   https://github.com/GalSim-developers/GalSim/issues
describing the problem along with the particulars of your system and
configuration.  Include a copy of the above output to the screen, and
post and copy of the file gs_error.txt, which will help people diagnose
the problem.

I see no mention in the documentation where to download that module, and it is also not on pypi.
How to proceed?

**Comment by rmjarvis** [comment]
I don't know why pip sometimes doesn't get the dependencies right.  But you can do it manually using:

`pip install LSSTDESC.Coord`

**Comment by rmjarvis** [comment]
Oh, actually, I see it's because you're using SCons.  Yeah, then you have to install this yourself.  

And it looks like that's missing from our [Scons installation instructions](https://github.com/GalSim-developers/GalSim/blob/releases/2.1/INSTALL_SCONS.md).  I'll add it.

**Comment by rmjarvis** [comment]
cf. 68c8695b0b78d118ca1c438b2284674dc8a4851

**Comment by rmjarvis** [comment]
In particular, here is the new documentation that now explains this.

https://github.com/GalSim-developers/GalSim/blob/releases/2.1/INSTALL_SCONS.md#vi-python-dependencies

**Comment by DavidJJansen** [comment]
Thanks, that was the missing bit of information, it builds fine now
