### ISSUE TITLE
isinstance(...,int) check in BaseDeviate failing for numpy.int64

### ISSUE THREAD

**Issue by matroxel** [GalSim-developers/GalSim#1009]
I'm updating code to python3 and switching to master branch from #919, on a new machine. I've run into a failed int check that worked in python2/#919/a different machine in BaseDeviate().

The cause is that I'm passing the sum of three values, two of which are python int and one of which is numpy.int64, which types the sum to numpy.int64. isinstance(...,int) then fails on the passed integer.

**Comment by rmjarvis** [comment]
Can you post a snippet that fails for you, which we could turn into a unit test?

**Comment by matroxel** [comment]
>>> galsim.BaseDeviate(np.array(1).astype(np.int64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_08/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.1.4.lsst/lib/python/galsim/random.py", line 92, in __init__
    self.reset(seed)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_08/stack/miniconda3-4.5.4-fcd27eb/Linux64/galsim/2.1.4.lsst/lib/python/galsim/random.py", line 128, in reset
    raise TypeError("BaseDeviate must be initialized with either an int or another "
TypeError: BaseDeviate must be initialized with either an int or another BaseDeviate

**Comment by rmjarvis** [comment]
Ok.  I guess I'm not sure why you are using this for the seed of a BaseDeviate.  Can't you just cast it to `int` in your code before passing to BaseDeviate?

**Comment by matroxel** [comment]
Yes, I can, and do now. @rmandelb asked me to open the issue.

**Comment by rmandelb** [comment]
Even though troxel did the local fix for that specific piece of code, I
thought it worth at least considering whether those type checks should be
made more robust to this problem.

**Comment by rmjarvis** [comment]
Sure.  The documentation says "integer", which I guess is ambiguous about whether non-`int`, numpy integer family types are allowed.

**Comment by rmjarvis** [comment]
Done in #1025
