### ISSUE TITLE
Don't quantize after reciprocity failure

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#1016]
In our standard treatment of WFIRST detector effects, there is a call to `quantize` directly after the call to `applyReciprocityFailure`.  We discussed whether this was correct at the WFIRST hackathon this week, and we concluded that while it's not completely certain, we think it is more likely that this isn't correct.

Basically, putting quantize where it currently is would maybe be appropriate if the reciprocity failure was essentially a variable quantum efficiency, so it represented a chance of a photon to convert to a hole in the sensor.  But if this were the case, then it should be wavelength dependent, which it apparently isn't for WFIRST sensors.

Instead, it is probably a nonlinearity in the conversion of holes to voltage.  In this case, the resulting value should not be quantized yet.  It's a float value that then undergoes further effects until eventually being quantized by the ADC.  The upshot is that we should remove that call to quantize.  (Or maybe move it to right after the sky noise to make sure that we have an integer number of photons in every pixel.)

**Comment by rmandelb** [comment]
Closed by #1022.
