### ISSUE TITLE
BUG integer division in power spectrum module

### ISSUE THREAD

**Issue by beckermr** [GalSim-developers/GalSim#1020]
I think this line might be a bug

https://github.com/GalSim-developers/GalSim/blob/releases/2.1/galsim/lensing_ps.py#L494

It disallows grid spacings less than 1 arcsecond.

**Comment by rmjarvis** [comment]
Yup.  Looks like.  I think this was a casualty of our attempt to convert all the integer division to work right in python 3 several years ago.  `kmax_factor` is an integer, but `grid_spacing` is not, so this should be a regular `/`, not `//`.

**Comment by rmandelb** [comment]
Closed by #1022.
