### ISSUE TITLE
FitsWCS is reading all the data not just the header

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#1024]
When using `FitsWCS` it is reading all the data rather than just the header.  For example running on some DES images I see it is spending all its time reading and decompressing the data. This is inefficient but also could exhaust memory for very large images
```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       21    6.964    0.332    8.140    0.388 {built-in method astropy.io.fits.compression.decompress_hdu}
      895    3.058    0.003    3.058    0.003 {method 'read' of '_io.FileIO' objects}
       21    0.483    0.023    0.483    0.023 {built-in method gc.collect}
    14621    0.274    0.000    0.274    0.000 {built-in method posix.lstat}
   ... snip ...
```

**Comment by rmjarvis** [comment]
I think I see where this is probably happening.  We have a [`_check_hdu`](https://github.com/GalSim-developers/GalSim/blob/releases/2.1/galsim/fits.py#L327) function that we run to see if `hdu.verify('fix')` is required to fix various kinds of broken (but salvageable) fits files.  This process involves making sure `hdu.data` doesn't raise an exception.

I think what we want to do here is to add a parameter `header_only` to this, which `FitsHeader` can set to `True` when it calls it, where it only checks that the header is readable, not the data.

**Comment by rmjarvis** [comment]
Done in #1025
