### ISSUE TITLE
fast, vectorized WCS methods

### ISSUE THREAD

**Issue by beckermr** [GalSim-developers/GalSim#1026]
@esheldon and I noticed a lot of overhead in the current outwardly facing APIs for WCS transformations. Apparently, things are vectorized underneath but it is not fully exposed according to @rmjarvis. After some discussion, @rmjarvis suggested adding methods like this

```
ra, dec = wcs.toWorldRad(x, y)  # returns ra, dec in radians
x, y = wcs.toImageRad(ra, dec)  # takes ra, dec in radians
```

The inputs here are numpy arrays or scalars.

I think these would be added to the Celestial WCS classes?

**Comment by esheldon** [comment]
What do you think about a check in the toWorld type methods for two input arrays rather than a scalar `Position`?  Then everything could take a different code path that is fully vectorized, including a final `np.degrees(ra, out=ra)` ?

**Comment by rmjarvis** [comment]
I don't like having units of angles be implicit.  But perhaps
```
x, y = wcs.toImage(ra, dec, coord.degrees)
ra, dec = wcs.toWorld(x, y, coord.degrees)
```
Then you can specify which unit you are using for the ra, dec arrays explicitly, and it can apply it for you (still vectorized).

**Comment by esheldon** [comment]
looks good to me

**Comment by rmjarvis** [comment]
Done.  #1032
