### ISSUE TITLE
_makeSkyImage function in CelestialWCS ignores coordinate system wrap around at RA=0

### ISSUE THREAD

**Issue by cwwalter** [GalSim-developers/GalSim#1030]
We are seeing highly incorrect sky background images in imSim when objects are places at ra=0.  I believe I have tracked this down to an issue in the _makeSkyImage function in CelestialWCS(BaseWCS).

This code at 

https://github.com/GalSim-developers/GalSim/blob/releases/2.1/galsim/wcs.py#L1067

```
       # Use the finite differences to estimate the derivatives.
        cosdec = np.cos(dec[1:ny-1,1:nx-1])
        dudx = -0.5 * (ra[1:ny-1,2:nx] - ra[1:ny-1,0:nx-2]) * cosdec
        dudy = -0.5 * (ra[2:ny,1:nx-1] - ra[0:ny-2,1:nx-1]) * cosdec
        dvdx = 0.5 * (dec[1:ny-1,2:nx] - dec[1:ny-1,0:nx-2])
        dvdy = 0.5 * (dec[2:ny,1:nx-1] - dec[0:ny-2,1:nx-1])

        area = np.abs(dudx * dvdy - dvdx * dudy)
        factor = radians / arcsec
        image.array[:,:] = area * sky_level * factor**2
```

ignores the fact as that as you move over the RA=0 line the RA immediately changes from 0 to 2*pi. Since this wraparound is ignored, the resulting large derivatives that are used to calculate the area distortions on the sky gives non-physical effective pixel sizes.

**Comment by rmjarvis** [comment]
Closed via #1031
