### ISSUE TITLE
Host RealGalaxy Data on Zenodo?

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/GalSim#1033]
Obviously not a super high priority issue, but this would do two things:
  - Have a nice DOI to cite whenever we use these datasets.
  - Provide a centralized repo from which to download GalSim datasets (because right now, I'm attempting to download the COSMOS_25.2 sample for the 3rd time from great3.jb.man.ac.uk and it keeps failing at about 25% of the download for some reason).

Let me know what you think, I'd be happy to implement the changes in `download_cosmos.py` and move a copy of the data over to Zenodo if that sounds like a good idea.

**Comment by rmjarvis** [comment]
I haven't investigated different hosting options, but it sounds like you have.  I do think it would be a good idea to move to a more official hosting platform if it doesn't cost us anything.  So if you think Zenodo is a good one, that would be great if you could start the process of moving it there.

**Comment by EiffL** [comment]
Great, yes, I think Zenodo is a great solution for this kind of data repository.

I have prepared an upload of the COSMOS dataset but I have a few questions before I can press the `publish` button:
  - I need a list of authors (and optionally contributors). I'm guessing @rmandelb and a few other people as authors ?
  - I need a license for the data, as a default Zenodo suggests `Creative Commons Attribution 4.0 International`
  - A list of grants that supported this work, there I'm guessing I can copy the grants in the acknowledgements of the GREAT3 paper, but let me know.
  - A date of first publication... I have no idea when that data was first released
   
I also went ahead and created a "GalSim" community, which acts as a curated list of datasets compatible with GalSim (it's empty for now): https://zenodo.org/communities/galsim 
There is only one issue with this is that there can only be one curator account. Curators accept or rejects uploads submitted by other people under the given community. I can play this role, but it's kind of weird because I'm not even a galsim dev ^^' Otherwise, someone else needs to create that community under their own personal accounts, or it's possible to create this community under a shared account, like `GalSim-developers`, maybe there is already an email account for this kind purpose ?

**Comment by EiffL** [comment]
I'm working with students who have had difficulties with the download of the galsim  cosmos data... should we move forward with hosting it on zenodo?
Essentially all I need are the answers to the questions in the previous post, mainly a list of authors for the COSMOS_25.2 sample, and associated grant acknowledgements. @rmandelb ?

**Comment by rmjarvis** [comment]
1. For the authors, the original data I think were mostly Rachel and Claire Lackner.  Not sure who else.  Barney Rowe helped make the noise profiles, which are also part of the download, so he should be included as well.  For the follow up i<25.2 data, the wiki page references [this paper](http://adsabs.harvard.edu/abs/2017arXiv171000885M), but I don't know which authors were actually relevant to making the COSMOSIS 25.2 data files.  Probably Rachel can say more about who is actually relevant.
2. I'm not one of the above authors, but I'll be bold and suggest that the default Creative Commons License is probably a good choice.
3. no idea
4. I'm pretty sure 2012 was the first time it was collated into something similar to its current form.  not sure if there is a relevant prior date, but that's probably a good year to quote.  i<25.2 was later.  I think 2015 is probably right, but Rachel may correct me if there is an earlier provenance for that than when it was added to GalSim.

**Comment by rmandelb** [comment]
Ah sorry @EiffL - I didn't notice your earlier questions.

1. The i<25.2 sample primary contributors were me, Claire, Alexie, and Barney.  We each contributed bits that I collected into the current format.

2. Yes, Zenodo's default license is fine.

3. Yes, copy the grants from the GREAT3 paper.  (We did the  work on similar timescales and using nearly the same code, despite not officially releasing the 25.2 sample until later.)

4. Mike has the dates right.

> I'm not even a galsim dev

Weird.  I've fixed that.  ;)

**Comment by EiffL** [comment]
Great :-D thanks Mike and Rachel. I'm uploading the data and will be making a PR to update the download script.

**Comment by EiffL** [comment]
https://zenodo.org/communities/galsim
sweet :-)

**Comment by rmandelb** [comment]
Thank you!

**Comment by rmjarvis** [comment]
Done. #1043
