### ISSUE TITLE
Moving the Great3 server to Edinburgh

### ISSUE THREAD

**Issue by joezuntz** [GalSim-developers/GalSim#1037]
Hi all,

To help deal with things like #1023 I'd like to move the Great3 server, which hosts the COSMOS data among other things, up to Edinburgh where I can debug things properly.

I guess this would mean changing some paths in download code somewhere, and website text change.  Anything else?

Cheers,
Joe

**Comment by rmjarvis** [comment]
See also #1033.  @EiffL was looking into switching the host to Zenodo.  It seems like that might be a better solution than relying on either university's servers.

**Comment by rmjarvis** [comment]
Superseded by #1033 / #1043
