### ISSUE TITLE
Downsampling with PSF

### ISSUE THREAD

**Issue by bluetooth12** [GalSim-developers/GalSim#1055]
Hello, I have two sets of images: One at a high resolution and one at a low resolution. I want both sets of images to be at the same resolution and, to do so, I need to downsample the high resolution image with a PSF. The result should be a blurred image that is "zoomed-out" so that the high resolution image looks like the low resolution image. Can your code do this? If not, can you suggest a resource I could use (paper/code) to achieve this result?

**Comment by rmjarvis** [comment]
If it's an integer number of pixels you want to down sample by, then [`Image.bin`](http://galsim-developers.github.io/GalSim/_build/html/image_class.html#galsim.Image.bin) will do that.

If not, you could make an [`InterpolatedImage`[(http://galsim-developers.github.io/GalSim/_build/html/arbitrary.html#interpolated-images) object from the high resolution image and then [draw](http://galsim-developers.github.io/GalSim/_build/html/gsobject.html#galsim.GSObject.drawImage) if at a lower resolution.

**Comment by bluetooth12** [comment]
Thank you for your reply. The only information I have is that the high resolution images are at 0.5m and the low resolution images are at 3m. I am trying to start with a 3m FWHM Gaussian PSF.

**Comment by rmjarvis** [comment]
Actually, with the PSF added, you'd want to use the InterpolatedImage approach, not `bin`.  Convolve the original high-resolution image by your PSF and then draw it at the lower resolution.

If you want to be extra precise, you can even deconvolve by the original Pixel as well.

```
high_res = galsim.InterpolatedImage(high_res_image, scale=high_res_pixel_scale)
orig_pixel = galsim.Pixel(high_res_pixel_scale)
psf = galsim.Gaussian(sigma=low_res_psf_sigma)
low_res = galsim.Convolve(high_res, psf, galsim.Deconvolve(orig_pixel))
low_res_image = low_res.drawImage(scale=low_res_pixel_scale)
```
Something along those lines should work.
