### ISSUE TITLE
Binary wheel for GalSim? For easy live demos on Colab

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/GalSim#1056]
GalSim is a dependency in some other projects of mine, and I'm trying to see if I can make it even easier to install. The conda builds certainly work, but I hate conda, I don't want  to have to use a different python than my system python. Also, it becomes slightly painful in some environments like Google Colab. 

I have this demo notebook that uses the conda package to run GalSim on Colab:
https://colab.research.google.com/drive/1il04VsOgcDhQlEXkeq1g9XXvURYyoucr
But it's not completely satisfactory, and rather slow It needs to install a completely new environment.

The other solution I have is to pip install GalSim source package, this reuses maximally the colab environment, but it's super slow to compile from source:
https://colab.research.google.com/drive/14CE91UF_GbIMdjCQkxluJXj9BAS3VYmW

So, what would be great is a binary wheel version of the pip package. Any reason why we don't have one? Before diving into it I thought I would ask

**Comment by rmjarvis** [comment]
I tried to do this back when we first released 2.0, and I failed, so I removed it.  I *think* you have to compile separately for every system, but I admit I didn't really look into it all that carefully, so I could be wrong.  My recollection is that I set up a wheel on my laptop, which worked for me, but failed in linux.  If you want to try to figure out how to set it up to work reliably, that would be very appreciated.

**Comment by EiffL** [comment]
Great, this is good news :-) I was afraid there might  be some licensing issues, same as what as been preventing us from building wheels for CCL. I'll try to get this to work, at least for some systems.

**Comment by EiffL** [comment]
Almost ready to open a PR, looks like building wheels for linux and mac is surprisingly easy with this tool: https://cibuildwheel.readthedocs.io/en/stable/

Currently experimenting on my fork: https://github.com/EiffL/GalSim/actions/runs/997012483

It generates as artifacts the wheels for all possible combination of platforms and python versions, which can then be uploaded to PyPi either manually or automatically if preferred.

To try it out I've uploaded it there: https://test.pypi.org/project/GalSim/

Annnd looks like it works \o/ here is a demo on colab: https://colab.research.google.com/drive/10a20mCGadYLiuBVI7_Mwn5DdOUiIh8FF?usp=sharing
