### ISSUE TITLE
Enable `_shoot` method to return photon x/y coords in pixels instead of sky coords.

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1062]
This would be useful for integrating batoid into ImSim.  I'm not totally sure what the right approach would be though.  Maybe add `wcs` as a kwarg to `_shoot`?  Or add some kind of flag to `PhotonArray`?

**Comment by rmjarvis** [comment]
@jmeyers314 Is there anything to do here to make the stuff you're doing with Geri work correctly?  I know we used to think something needed to be done about this, but I think we've now realized that the coordinate system for x,y values in the photon arrays can change arbitrarily as things go through the list of photon ops.  So can we close this issue?

**Comment by jmeyers314** [comment]
Yep, I think we can close this.
