### ISSUE TITLE
Add Refract surface operator to handle refraction of the incident photons

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#1065]
@jmeyers314 pointed out that the photons refract at the surface of the CCD, so the angle inside the silicon is not the same as the angle above the silicon.

We could add that (obvious in retrospect) bit of physics either to the FRatioAngles surface operator, or to the Silicon class.  But I think even cleaner would be to make a new surface operator (e.g. Refract) to handle it, since we will soon have Batoid ray tracing that will figure out the incidence angles a different way.  So putting a Refract surface op after that would be pretty clear I think.

**Comment by jmeyers314** [comment]
Sounds good to me.  I'd suggest an interface where one can specify either a single in/out refractive index ratio as a float, or a callable that returns the refractive index ratio as a function of (vacuum) wavelength.
