### ISSUE TITLE
GSFitsWCS TAN-SIP inversion problems

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1105]
I've been running into some problems with `radecToxy` for TAN-SIP WCS's.  Specifically, occasionally the code to do the inversion gets stuck with a residual > 1e-12 which leads to a max_iter error.  Here's a link to some test data/script: https://www.dropbox.com/sh/oavydz0y8je7bga/AAAKvoe2meptgiUhYeqQv-tla?dl=0.

I think there are a couple of things that could be addressed here.  First, it'd be nice if in an array of many radecToxy transformations, a single failure didn't kill the whole batch.  Maybe there should be an option to just return `NaN` on any failures.  Second, I wonder if 1e-12 is just too small.  It's hard for me to imagine a circumstance where I'd care about errors of even 1e-6 of a pixel.  So I'd vote we either relax this constraint or at least make it user-settable.

**Comment by rmjarvis** [comment]
Fixed on #1106
