### ISSUE TITLE
multiprocessing use crashes on python >= 3.8 on macos

### ISSUE THREAD

**Issue by erykoff** [GalSim-developers/GalSim#1112]
As of python 3.8, the default start method on macos (at least on Catalina 10.15 and greater) has been changed from `fork` to `spawn` due to certain security issues (that have been there forever, but I guess somebody decided now was the time to close this hole and break a bunch of code).  This means that, for example, `demo8.py` will crash if run with python >= 3.8 on macos.

Although `spawn` is indeed "safer" (as commented in `phase_screens.py`) it is also a complete disaster for the way that most people use multiprocessing. It spawns a whole new python process (slow!) and then you lose all shared memory state (so you can't use any objects that are not explicitly pickled in the spawned call).  In python 3.8 a whole new shared memory system was added to multiprocessing which should be able to handle this safely, but this isn't available for earlier pythons, so having compatibility across versions is somewhat challenging.

One option to get around this is to have the following in the top of the demo script (or could be guarded with a macos check):
```
import multiprocessing
multiprocessing.set_start_method('fork')
```
I see in some cases galsim is using contexts, but defaults to the system default.  This should probably be overridden, but I'm not sure what the best approach is.

**Comment by rmjarvis** [comment]
Done. #1117
