### ISSUE TITLE
Patch release for Python 3.8 warning about literals

### ISSUE THREAD

**Issue by TallJimbo** [GalSim-developers/GalSim#1115]
We're now (having recently switched to Python 3.8) seeing warnings from the current (2.2.4) release of GalSim on literal comparisons with `is`, something that I see was fixed on `main` back on 49fe3f55281ac159aa8ff798bcf005ae5ad41738.  I can confirm that that commit cherry-picks cleanly on to the `releases/2.2` branch.  Could we have a patch release with at least that commit included?

**Comment by beckermr** [comment]
I'm happy to make this PR @rmjarvis.

**Comment by rmjarvis** [comment]
GalSim 2.2 didn't officially support python 3.8 (since I believe it was still a dev release at the time), so I can't guarantee that there aren't other problems with using 2.2 on python 3.8.  However, I would expect that that commit is probably the main change required.

**Comment by erykoff** [comment]
Related, what's the timescale for the next galsim release?

**Comment by jmeyers314** [comment]
I'd really like to finish up #1104 first.  That's been on my back burner for a few months now, but I can bump the priority back up.

**Comment by rmjarvis** [comment]
I also have one project I've wanted to include which should kind of wrap up the work done in #1100.  Specifically I have been working to apply those new features to demo13.  It's been about 1 month away for at least 5 months now...  Sorry!  I've been having trouble focusing lately.  And I don't even have a toddler around the house like Josh does, so I have less of a good excuse.  Just general quarantine fatigue I suspect.

**Comment by rmjarvis** [comment]
It turns out that there are other problems with GalSim 2.2 on Python 3.8.  There are 7 errors/failures in the unit tests on a 3.8 system.  I'll see how hard it is to fix them all, but if I can do it without too much effort, I'll make a 2.2.5 version that can work in python 3.8.

**Comment by rmjarvis** [comment]
cf. https://github.com/GalSim-developers/GalSim/pull/1116

I fixed the straightforward things.  But most of the errors were Eli's issue about the spawn vs fork context.  That was complicated enough to merit a PR.

**Comment by rmjarvis** [comment]
Done.

**Comment by rmjarvis** [comment]
v2.2.5 released with this fix.
