### ISSUE TITLE
FindAdaptiveMom fails to return moments for certain Von-Karman profiles

### ISSUE THREAD

**Issue by aaronroodman** [GalSim-developers/GalSim#1132]
this snippet shows the problem:

```
profile = galsim.VonKarman(lam=700.0, r0=0.25, L0=11.0, flux=1.0).shift(-0.13, -0.13)

vkim = galsim.Image(32,32,scale=0.26)    
vkim = profile.drawImage(image=vkim,method='auto')    
mom = vkim.FindAdaptiveMom(weight=None, strict=False)
print(mom)
```

which returns

`galsim.hsm.ShapeData(image_bounds=galsim.BoundsI(xmin=0, xmax=0, ymin=0, ymax=0), observed_shape=galsim.Shear(0j), correction_status=-10, error_message='Error: non positive-definite weight in find_ellipmom_2.\n')`

Moments are successfully found if the value of L0 is changed to 12.0 or the 1/2 pixel shift is changed by a small amount

**Comment by rmandelb** [comment]
The adaptive moment calculation is a bit fragile for undersampled profiles, meaning small changes in the profile definition can affect convergence.  This behavior is mentioned briefly in the docstring for `FindAdaptiveMom`.  My guess is that that is the reason for this issue.  (If you query the profile itself to find out its Nyquist scale, `profile.nyquist_scale()` is ~0.12 arcsec, so the image with 0.26 arcsec pixel scale is significantly undersampled.)  

If you need robust moment estimates for undersampled objects, you could perhaps use the unweighted second moment size, which is provided as `profile.calculateMomentRadius()`?

**Comment by aaronroodman** [comment]
Thanks for the insight - I can work around this issue...

**Comment by rmandelb** [comment]
OK.  My student Tianqing Zhang has been carrying out unweighted moment measurement (for other moments beyond size) on simulated images for quite a while, so you may be able to get some tips from him if you want to go that route.

Closing #1132.
