### ISSUE TITLE
Allow the template keyword to use an eval

### ISSUE THREAD

**Issue by cwwalter** [GalSim-developers/GalSim#1138]
I would like to be able to do something like

```
template: $os.environ.get('IMSIM_DIR') + "/config/imsim-config.yaml"
```

instead of this:
```
template: /Users/walter/LSST/imSim/config/imsim-config.yaml
```

Currently, this isn't possible because the template really needs to be a string.  The motivation is to be able to write generic driving yaml files which don't need to be modified for different site installation setups.

**Comment by rmjarvis** [comment]
This was done in #1143.
