### ISSUE TITLE
Si(x) and Ci(x) approximations accuracy for x>4

### ISSUE THREAD

**Issue by enzymepower** [GalSim-developers/GalSim#1145]
I've found the current Si(x) and Ci(x) approximations, when x>4, to be quite inaccurate.
I've plotted Si(x), the current approximation and some other approximations for comparison.

'smallsi' is the polynomial for the Si(x) pade approximation 0<=x<=4
'fgApprox' is the current approximation using pade approximated f(x) and g(x) and the smallsi for 0<=0<4
'xx2Approx' uses f(x)=1/max(1, x) and g(x)=1/max(1, x^2)
'approxSisecond' uses a few terms from the series expansion at infinity and the smallsi for 0<=0<4
'Si(x)' is Si(x)

![wide_sinintegrals](https://user-images.githubusercontent.com/6540723/161421218-a5d646ea-470b-4902-8d21-b04d1bdeed84.png)
![wide_sinintegralsError](https://user-images.githubusercontent.com/6540723/161421243-43042bc8-4f38-4372-9482-88c6103aae96.png)

As you can see, the current fg approximation is almost always worse than just using 1/x and 1/(x^2) and even crosses the x axis while x>0.

**Comment by rmjarvis** [comment]
I'm not sure how you're computing these, but I'm not able to reproduce your plot with the GalSim implementation of Si.  I exposed our implementation to the python layer to make it easier to plot and test (branch `expose_si`), and I'm getting extremely good agreement with the scipy.special implementation.  Less than 1.e-15 difference at all 0<x<100.

![si](https://user-images.githubusercontent.com/623887/161550701-1e56e21a-ae33-4128-8c5c-c3a266e4f30a.png)

**Comment by rmjarvis** [comment]
cf #1146.  In short, all tests pass, so I don't think there is anything to fix here.

**Comment by enzymepower** [comment]
Sorry, my mistake. It is Excellent.
![wide_sinintegralsError](https://user-images.githubusercontent.com/6540723/161658591-d2fce073-30d0-4dab-907f-66a6e598c41a.png)
