### ISSUE TITLE
PhotonDCR config bugs

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1148]
Placing here so I don't forget:

Looks like `PhotonDCR._opt_params` is missing an entry for `obj_coord`.

Also, there's a typo: `zenit_coord` -> `zenith_coord`.

Need to add some config usage tests.

**Comment by rmjarvis** [comment]
One comment about this.  The `zenit_coord` is of course a typo-bug, which apparently isn't covered by unit tests.  But `obj_coord` is handled by the `PhotonDCRBuilder` here: https://github.com/GalSim-developers/GalSim/blob/releases/2.3/galsim/config/photon_ops.py#L220

**Comment by rmjarvis** [comment]
Done via #1160
