### ISSUE TITLE
drawReal of specific InterpolatedImage leads to seg fault

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1164]
While running Piff (via Rubin science pipelines) on some DECam data, @leeskelvin encountered the following seg fault.  The relevant line in Piff is https://github.com/rmjarvis/Piff/blob/releases/1.2/piff/pixelgrid.py#L249, but I've distilled the error to what's posted below:

[prof.pkl.gz](https://github.com/GalSim-developers/GalSim/files/9021638/prof.pkl.gz)

Code to reproduce:

```
import pickle
import galsim

with open("prof.pkl", 'rb') as f:
    prof = pickle.load(f)

image = galsim.Image(
    galsim.BoundsI(
        xmin=-12,
        xmax=12,
        ymin=-12,
        ymax=12
    ),
    dtype=float,
    scale=1
)

prof.drawReal(image)
```

Seg-faults in both linux and macos.

**Comment by rmjarvis** [comment]
Yep.  I reproduce this on my laptop.  Which means I can fix it.  I'm on it.

**Comment by leeskelvin** [comment]
Thank you both for looking at this and [diagnosing it so quickly](https://github.com/GalSim-developers/GalSim/pull/1165)!

**Comment by rmjarvis** [comment]
No problem.  And thanks much for the bug report!
