### ISSUE TITLE
ZeroDivisionError in ChromaticSum.drawImage

### ISSUE THREAD

**Issue by jchiang87** [GalSim-developers/GalSim#1170]
I'm getting a `ZeroDivisionError` at [this line](https://github.com/GalSim-developers/GalSim/blob/e628f02ae1eaedc96a880d5ab812ee3d5e868414/galsim/chromatic.py#L2252) when `remaining_flux = 0`.

**Comment by rmjarvis** [comment]
I guess I'm surprised this ever turned up.  I had to use a galaxy with two components at the end, both with zero flux.  But here is the fix: #1171.
