### ISSUE TITLE
galsim 2.4.0 makes breaking change to public ImageView.

### ISSUE THREAD

**Issue by erykoff** [GalSim-developers/GalSim#1181]
The recent release of 2.4.0 broke the build of lsst science pipelines apparently due to this commit https://github.com/GalSim-developers/GalSim/commit/f6f57791a5b4a15a255005d1fd11856424e5b67e which changes the interface to `ImageView`.

This does not appear to be reported in https://github.com/GalSim-developers/GalSim/blob/v2.4.0/CHANGELOG.rst .

**Comment by beckermr** [comment]
FWIW Mike has said that the C++ interface is pretty stable but has no official API or ABI.

**Comment by rmjarvis** [comment]
Yup.  Sorry, I should have mentioned this in the CHANGELOG.  There were a some small changes to some of the Image constructors to help give better error checking to guard against pointer overruns and thus help ensure we don't seg fault from code errors.
But as stated [here](http://galsim-developers.github.io/GalSim/_build/html/cpp.html), we don't guarantee C++ API stability across minor version changes.  So I don't believe there is anything to do here.  I don't intend to revert this commit.

**Comment by rmjarvis** [comment]
It's in the CHANGELOG now.
