### ISSUE TITLE
drawFFT_finish vs image.calculate_inverse_fft

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/GalSim#1199]
Hi, 
in the `gsobject.drawFFT` there is a chain of 3 functions

- `kimage, wrap_size = self.drawFFT_makeKImage(image)` : that compute the f(k)  fourier-space coefficient w/o the phase
- ` self._drawKImage(kimage)`: that update the f(k) including the phases
- and finally `self.drawFFT_finish(image, kimage, wrap_size, add_to_image)` that compute the Inverse FFT using `_galsim.irfft`
(nb. here self is a Transformation object)

I was wandering what prevent to use the `kImage.calculate_inverse_fft()` function in place of the last step (drawFFT_finish) ?
Thanks

**Comment by rmjarvis** [comment]
I'm not sure what you mean by prevent here.  The two functions have to do slightly different things before and after the actual call to `_galsim.irfft`.  So we couldn't just replace the `drawFFT_finish` call with `calculate_inverse_fft` within `drawFFT`.  But if a user wants to do that for some other use case, there isn't anything preventing you from doing so.
