### ISSUE TITLE
calculate_inverse_fft: _BoundsI ymax value?

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/GalSim#1200]
Hi 
looking at `image.calculate_inverse_fft` I was wandering why  target_bounds ymax value is `No2-1` and not `No2`, I guess it is a to fit FFT requirements. In fact this is also the case in `drawFFT_finish` by the way.
Thanks

**Comment by rmjarvis** [comment]
Because the size in the x direction has to be even.  Well, it doesn't *have* to be, but it's way faster if the size is a power of 2 or 3 x a power of two, so we enforce that for all our FFTs.
