### ISSUE TITLE
drawFFT image type

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/GalSim#1203]
Hello,
looking at ` def drawFFT_finish(self, image, kimage, wrap_size, add_to_image)` I was wandering if in this line
```python
real_image = Image(breal, dtype=float)
```
the dtype would be more the "image dtype". I know that np.float32 is the default but...
 My 1cp.

**Comment by rmjarvis** [comment]
No, that's intentional.  We do the intermediate calculation in double precision regardless of the dtype to store the result.
