### ISSUE TITLE
Moffat: setupFT

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/GalSim#1209]
Hi (again)
In the `Moffat.cpp` code in case of truncated profile (ie. `trunc>0`) the `maxK`  parameter is determined in conjonction with the computation of `f(k)`for some k-values. What is puzzling to me is that  in the `setupFT` code one reads
```c++
            assert(_trunc > 0.);
            .... 
            if (_trunc > 0) {
                val = math::hankel_trunc(I, k, 0., _maxRrD,
                                         this->gsparams.integration_relerr,
                                         this->gsparams.integration_abserr);
            } else {
                val = math::hankel_inf(I, k, 0.,
                                       this->gsparams.integration_relerr,
                                       this->gsparams.integration_abserr);
```
 and if the `assert` was not there that one would have used a general Hankel computation (in math::Hankel.cpp) while we know the close form of the Moffat `f(k)` in case `trunc=0`(cf. no truncation)...

Well, may  be this is not a really numerical issue, a possible suggestion is to clean a little the code.

**Comment by rmjarvis** [comment]
Yes.  We originally used this calculation of the FT for everything I think.  But then someone noticed the closed form solution, and we now only call this function when it's truncated.  So that branch is unnecessary anymore.
