### ISSUE TITLE
Build wheel error

### ISSUE THREAD

**Issue by MuhammadAliShahid1010** [GalSim-developers/GalSim#1226]
Was trying to install galsim to read fits files and it is showing me an error when it is getting requirements to build wheel. The following is what the terminal says:

`
[error.txt](https://github.com/GalSim-developers/GalSim/files/12064071/error.txt)
`

**Comment by rmandelb** [comment]
Correct me if I'm wrong, but I think from that log you are on a Windows machine?  GalSim supports Linux and Mac, not Windows.  (See https://github.com/GalSim-developers/GalSim/blob/releases/2.4/INSTALL.rst)

**Comment by MuhammadAliShahid1010** [comment]
Thank you @rmandelb, I was wondering if a virtual machine linux can be used?

**Comment by rmandelb** [comment]
Another user reported last year that GalSim seems to work in a Windows Subsystem for Linux (WSL): https://github.com/GalSim-developers/GalSim/issues/1168#issuecomment-1339143148
Seems worth a try.
