### ISSUE TITLE
Can't photon shoot simple chromatic transformation

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1229]
`ChromaticTransformation._shoot` attempts to evaluate wavelength-dependent jacobian, offset, and flux_ratios [here](https://github.com/GalSim-developers/GalSim/blob/releases/2.4/galsim/chromatic.py#L1933), but some of the underlying methods (for example in `ChromaticObject.expand` [here](https://github.com/GalSim-developers/GalSim/blob/releases/2.4/galsim/chromatic.py#L840-L842)) don't work correctly when handed an array of wavelengths.  Here's a short snippet that fails due to the above:

```python
import galsim
bandpass = galsim.Bandpass('LSST_r.dat', 'nm')
psf = galsim.ChromaticObject(
    galsim.Gaussian(fwhm=1)
).dilate(lambda w: (w/500)**-0.3)
star = galsim.DeltaFunction()*galsim.SED('vega.txt', 'nm', 'flambda')
obj = galsim.Convolve(psf, star)
img = obj.drawImage(bandpass, nx=15, ny=15, scale=1, method='phot')
```

**Comment by rmjarvis** [comment]
Done #1236
