### ISSUE TITLE
Small Discrepancy between Real and Fourier Space Shift

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/GalSim#1231]
While working on porting new features to jax-galsim, we noticed that the GalSim phase shifts are not exactly equivalent to the real domain equivalent.

Here is an example of what I mean:
```python
import galsim

gal = galsim.Gaussian(sigma=1.).shift([5,5]).withFlux(200)

real_im = gal.drawImage(nx=128, ny=128, scale=0.2, method='real_space')

fft_im = gal.drawImage(nx=128, ny=128, scale=0.2, method='fft')
```
![image](https://github.com/GalSim-developers/GalSim/assets/861591/cf344c95-cbdb-426d-b7c4-5ca5698ff2fd)

[notebook](https://colab.research.google.com/drive/1jWdrnXeM5Fe6DsUoRBNloNIdfWZDdEn-?usp=sharing)

So, it's definitely small, but not a nice pattern...

My guess... is that it might have something to do with this:
https://github.com/GalSim-developers/GalSim/blob/3a9ab46b3c11333cc5def004cbce3c74f6f186cf/src/SBTransform.cpp#L749
because when we use the exact expression in jax-galsim we recover perfectly the same answer as drawing the image in real space.

Just wanted to report this to see if this is known/not a big deal. Feel free to close this issue if this is the case :-)

**Comment by EiffL** [comment]
Hum interesting, I wouldn't have guessed platform-specific discrepancies at that level. But ok, if you recover 1e-15 using double precision then you are right it's not related to an approximation in this formula used to compute the phase.

**Comment by rmjarvis** [comment]
The first equation is nominally exact, but can have rounding errors.  The line you pointed to was intended to get back to |z|=1, which it does to the accuracy of the data type.  So the errors are just that numerical rounding errors can add up, maybe semi-coherently, rather than purely randomly.  And apparently differently on different systems.  That surprised me too, FWIW.

**Comment by rmjarvis** [comment]
Done. #1234
