### ISSUE TITLE
Installation issue (FFTW problem with Apple ARM)

### ISSUE THREAD

**Issue by wlim-ipac** [GalSim-developers/GalSim#1255]
Hello,
I have tried to install GalSim (actually Romanisim) on my Apple M1 / MacOS 13 but was not successful due to FFTW failure.
Do you have any resolution for this issue?

Downloading GalSim-2.5.0.tar.gz (8.6 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 63.3 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [20 lines of output]
Using setuptools version 68.2.2
Python version = 3.10.7 (v3.10.7:6cc6b13308, Sep 5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)]
Looking for Eigen:
/Library/Frameworks/Python.framework/Versions/3.10/include (no)
/usr/local/include (no)
downloaded_eigen/eigen-3.4.0 (yes)
GalSim version is 2.5.0
running dist_info
creating /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info
writing /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/PKG-INFO
writing dependency_links to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/dependency_links.txt
writing entry points to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/entry_points.txt
writing requirements to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/requires.txt
writing top-level names to /private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/top_level.txt
writing manifest file '/private/var/folders/y7/l7hsphn16lg7tr1p1jwj7ch40005gq/T/pip-modern-metadata-lgmc8mjf/GalSim.egg-info/SOURCES.txt'
Looking for libfftw3.dylib
Could not find fftw3 library. Make sure it is installed either in a standard
location such as /usr/local/lib, or the installation directory is either in
your LIBRARY_PATH or FFTW_DIR environment variable.
error:
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sidneymau** [comment]
As you are installing GalSim through pip (rather than conda), you will need to have fftw already installed (as pip cannot install fftw). See https://galsim-developers.github.io/GalSim/_build/html/install_pip.html#installing-with-pip for details. I think fftw should be available on macOS through brew or macports

**Comment by rmjarvis** [comment]
I'm assuming Sid's advice worked for you, so I'm closing this.  But if not, feel free reopen this issue.
