### ISSUE TITLE
`setuptools.dep_util` is deprecated and will be removed soon. Alternative suggested is `setuptools.modified`.

### ISSUE THREAD

**Issue by abravalheri** [GalSim-developers/GalSim#1290]
https://github.com/GalSim-developers/GalSim/blob/cb4133422ef7aa576182dc18835ce434f9024080/setup.py#L1000

This is the warning currently in place
https://github.com/pypa/setuptools/blob/v69.5.1/setuptools/dep_util.py#L5-L16.

**Comment by rmjarvis** [comment]
I fixed this directly on the releases/2.5 branch.  Thanks for the notice.
