### ISSUE TITLE
Galsim can work in windows environment

### ISSUE THREAD

**Issue by cgq274** [GalSim-developers/GalSim#1310]
I want to use this package in my project, but my project is based on Windows environment, which causes many errors. Does it mean this package can't work in a Windows environment?

**Comment by rmandelb** [comment]
Unfortunately that's correct, as noted in our [installation instructions](https://github.com/GalSim-developers/GalSim/blob/releases/2.5/INSTALL.rst) (blurb near the top about type of systems we support).

**Comment by cgq274** [comment]
> Unfortunately that's correct, as noted in our [installation instructions](https://github.com/GalSim-developers/GalSim/blob/releases/2.5/INSTALL.rst) (blurb near the top about type of systems we support).



> Unfortunately that's correct, as noted in our [installation instructions](https://github.com/GalSim-developers/GalSim/blob/releases/2.5/INSTALL.rst) (blurb near the top about type of systems we support).



> Unfortunately that's correct, as noted in our [installation instructions](https://github.com/GalSim-developers/GalSim/blob/releases/2.5/INSTALL.rst) (blurb near the top about type of systems we support).

Thank you, I will try other ways to solve this problem.

**Comment by rmjarvis** [comment]
FWIW, the main sticking point in making it work on Windows is installing FFTW, which is one of our dependencies.  If you know a reliable way to install that on Windows machines, please let me know.  If I can get that to work, I'm pretty sure I know how to get the rest of GalSim to be Windows-compatible.
