### ISSUE TITLE
Simulating spectrograph slit

### ISSUE THREAD

**Issue by chazshapiro** [GalSim-developers/GalSim#1320]
Hi All,

I'm simulating a spectrograph image where I:

1.  Start with telescope PSF (interpolated)
2. Truncate the PSF on 2 sides as though being blocked by a slit
3. Convolve the result with (interpolated) PSF of re-imaging optics
4. Sample on the detector

What's the most effective, galsimmy way to do step 2?  Trying not to make a mess of things...

Thanks,
Chaz

**Comment by rmjarvis** [comment]
Probably you could draw the step 1 PSF onto an image at some reasonably high resolution.  Then zero out the image where the slit is blocking it.  Then use InterpolatedImage to go the rest of the way.

**Comment by chazshapiro** [comment]
Will do, thanks Mike.  I wanted to make sure I wasn't overlooking some slick functionality that did this already.
