### ISSUE TITLE
generate output truth catalog

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#301]
Make an easy way to generate output catalogs from the (often random) values uses for each object.  Useful both for a truth table, and also for the catalogs that users will use with centroids, etc.

**Comment by rmjarvis** [comment]
Here is my proposal for the structure of a truth catalog output type from the config processing:
```
output : 
    truth :
        file_name : truth.fits
        columns :
            num : obj_num
            g1 : gal.shear.g1
            g2 : gal.shear.g2
            x : image_posx
            y : image_posy
            psf_e1 : 
                type : Eval
                str : 'psf_e * math.cos(psf_beta.rad())`
                fpsf_e : { type : Current, key : psf.ellip.e }
                apsf_beta : { type : Current, key : psf.ellip.beta }
            psf_e2 : 
                type : Eval
                str : 'psf_e * math.sin(psf_beta.rad())`
                fpsf_e : { type : Current, key : psf.ellip.e }
                apsf_beta : { type : Current, key : psf.ellip.beta }
```
The `columns` item is a dict whose keys will be the names of the columns in the output file, and the values are the values in each row for that column.  Typically, the value is taken to be the "Current" value for that item in the config dict.  i.e. it works just like the `type : Current` value type.  So these would look like `gal.shear.g1` and `gal.shear.g2` above.

However, I think it also makes sense to allow some special values that config knows about for each object.  These are the same items that are allowed to be in `Eval` items.  In the above example, these include `obj_num`, `image_posx`, and `image_posy`.

And finally, it's probably worth allowing calculated values here too.  In the above example, we convert from an EBeta specification of the PSF ellipticity to e1,e2.  I'm not sure how useful this really is, so I'd be ok with not including this option.  But I think it would be easy to allow.

Comments welcome.  I'll probably be doing the coding for this issue in the #691 branch, since it is related to things I'll be doing for that.  But discussion about this feature can be kept here.

**Comment by rmjarvis** [comment]
There is one other detail that I thought of.  In Python, a dict doesn't keep any particular order, so the order of the output columns won't necessarily match the order given in the yaml file.  This is probably ok in most cases, especially if the output file is a FITS binary table.  These are usually accessed by column name, so it doesn't matter what order they are in.  

However, some users may desire a particular output order, especially for ASCII output files where it is more common to access columns by number.  In this case, I think we can let the user provide the desired order of the columns in a list item, called 'order' perhaps:
```
output :
    truth :
        file_name : ...
        columns : 
            ...
        order : [ 'num', 'x', 'y', 'g1', 'g2', 'psf_e1', 'psf_e2' ]
```
We could either require that this list has all the column names given in the 'columns' item, or fill in any missing items at the end of the list.  I'm not sure which is more user friendly.  :)

**Comment by rmandelb** [comment]
It lives!

(Sorry, thought this issue was mostly dead.)

I think the proposal in your first comment sounds good to me.  I agree about wanting to specify ordering for ASCII (can we make it print a header line to indicate the order?).  Re: "We could either require that this list has all the column names given in the 'columns' item, or fill in any missing items at the end of the list." - my vote is for the first option.

**Comment by rmjarvis** [comment]
I was taking the header line with the column names to be a given.  That's really the preferred way of dealing with ASCII catalogs.  Most readers (e.g. pandas, numpy) have a way to read the header and use the columns by name.  So the explicit order option is mostly (a) cosmetic and (b) enabling people who don't know how to read ASCII headers properly.  :)

**Comment by jmeyers314** [comment]
>In Python, a dict doesn't keep any particular order, so the order of the output columns won't necessarily match the order given in the yaml file.

What about reading the yaml into an OrderedDict?  A la http://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts ?

**Comment by rmjarvis** [comment]
Interesting.  I might play around with that.

**Comment by rmjarvis** [comment]
Update: I have this working on branch #691.  See [demo9.yaml](https://github.com/GalSim-developers/GalSim/blob/%23691/examples/demo9.yaml) and [demo10.yaml](https://github.com/GalSim-developers/GalSim/blob/%23691/examples/demo10.yaml) for examples of the syntax.  

I used the OrderedDict idea of Josh, which works well for the YAML configuration files, but not for JSON.  So I'm querying whether people think it is still worth maintaining the JSON example files?

[Last time I broached this](https://github.com/GalSim-developers/GalSim/issues/381), people wanted to keep them, but I think now that they won't actually produce identical output for demos 9 and 10 (due to the order of the columns in the truth catalogs), I'm hoping we can remove them now?

I just mean the example scripts, not support for the JSON files by the `galsim` executable.  I'd be very surprised if anyone actually uses JSON files for configuration files, but I don't see any reason to disable support for them.  It's just that it's a pain to keep the demo*.json files in sync with the yaml versions.

**Comment by rmandelb** [comment]
I didn't have a chance to check out the code, but regarding the JSON thing:
In the two years since you last broached this, I have seen basically nobody asking about JSON demos / config, and have personally seen multiple people who are using yaml.  So I think letting the JSON demos go out of sync is not a very big deal.

But why remove the JSON demos 9 and 10?  Couldn't we just leave them since they still show useful functionality in JSON form, but with a comment at the top saying they won't produce identical output as the corresponding python and yaml demos?  (and I guess edit ```check_json``` to remove the diffs associated with those demos)

**Comment by rmjarvis** [comment]
It's mostly the tedium of keeping the json files in sync whenever I make changes to the yaml files that I object to.  If you want to take on that responsibility, I can leave them there but not update them and just let you make sure check_json works before any official releases?

**Comment by rmandelb** [comment]
Sure.  I can start by putting comments in the docstring for demo9.json and demo10.json explaining that it's not in sync, and editing ```check_json``` correspondingly (on this branch).  But I also just edited the wiki of "things to do before releases" to include a note to myself to check that each time.

**Comment by rmjarvis** [comment]
I thought of a possible compromise.  It's not actually all that onerous to keep the working parts of the json files in sync.  The painful bit is keeping the comments in sync.  So would you mind if we get rid of the bulk of the comments, and just leave a comment near the top saying that users should look at the yaml file for more extensive commentary about the features being used?

Also, I discovered that the python JSON parser also [has a way](http://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict-in-python) to read into an OrderedDict, so I can actually make the json parsing compatible with respect to the truth file output.

**Comment by rmjarvis** [comment]
In fact, I think the json files without all the comments is even a pedagogical improvement.  The problem with the way were were commenting them up is that readers can't differentiate the comments from the actual substance, so it doesn't color code them usefully.

Compare:
- [demo9.yaml](https://github.com/GalSim-developers/GalSim/blob/releases/1.3/examples/demo9.yaml)  (nicely color coded, both here and in vim, probably emacs too...)
- old [demo9.json](https://github.com/GalSim-developers/GalSim/blob/releases/1.3/examples/json/demo9.json)  (ugly, imo)
- new [demo9.json](https://github.com/GalSim-developers/GalSim/blob/%23691/examples/json/demo9.json)  (still not color coded, but much easier to follow what is going on without all the clutter)

If anyone objects, I can revert this commit: 1932df6547bef54198625148b60e651146c86203, but I do think it's an improvement.

**Comment by rmandelb** [comment]
I agree that this is an improvement.

**Comment by rmjarvis** [comment]
OK, Good.  I'll stick with that then.  Thanks.
