### ISSUE TITLE
add moments support to Ellipse class

### ISSUE THREAD

**Issue by TallJimbo** [GalSim-developers/GalSim#367]
@rmandelb and I have been discussing some possible API changes to the HSM component, and one feature that we have settled on is having an object to represent image second moments (xx,xy,yy), and possible first moments as well.

I'm inclined to do this using the existing Ellipse class (well, actually CppEllipse), by adding getters setters for (xx,xy,yy).  I already have code in hand to convert these into the native parametrization used by Ellipse, and it already has a position that could be used for first moments as well.

**Comment by rmjarvis** [comment]
@TallJimbo Is there any reason to keep this issue open?  It has been 2 years (to the day) since the last comment here, and coming up on 3 years since any real relevant activity.  So I'm guessing you have moved on.  OK to close?

**Comment by TallJimbo** [comment]
Yup, I think this is now obsolete.
