### ISSUE TITLE
API changes for HSM module

### ISSUE THREAD

**Issue by TallJimbo** [GalSim-developers/GalSim#368]
I've recently been trying to update the HSC/LSST pipeline's version of the HSM code, which is based on an older version of what's included with GalSim.  I'd like to make a few changes here, as GalSim now contains the definitive version of the HSM code.  For the most part, the goal is to make it more configurable and flexible, so it can be better integrated into a large pipeline, and of course to make it no worse for the small-scale testing it is largely used for here.

The main ideas are:
 - Have different result structs and driver functions for algorithms with significantly different result information (i.e. KSB and shapelets).  This would simplify the main results struct, as it would only include the values actually set by the main algorithms (linear, BJ, regauss).
 - Have a single object for second moments that can be passed around (#367).
 - Add overloads that would allow some PSF-correction algorithms to accept pre-measured moments that are passed in, instead of always remeasuring the moments themselves.

**Comment by rmjarvis** [comment]
@TallJimbo Likewise, it seems like this issue probably ought to be closed unless your anticipation of getting to it soon has changed.

**Comment by TallJimbo** [comment]
Agreed, I don't even remember what I'd intended to do here.  Sorry I didn't clean it up myself.
