### ISSUE TITLE
Add a function to load a wavefront map from outside

### ISSUE THREAD

**Issue by HironaoMiyatake** [GalSim-developers/GalSim#379]
It would be nice to add a function to load a wavefront map from outside such as ZEMAX. The first target would be to load an output file of "Wavefront Map" in ZEMAX, which will allow us to simulate more realistic optical PSF.

ZEMAX can output a wavefront map, which divides a pupil plane into a power of 2 (from 32 x 32 to 8192 x 8192), for a position of FOV. So we need to interpolate both on pupil plane and FOV.

As a first step, it might be nice to write up a simple draft version of this as "WavefrontPSF" or similar, without interpolations above.

**Comment by rmjarvis** [comment]
Is this issue essentially satisfied by what Josh has done in #549?

**Comment by jmeyers314** [comment]
Almost.  Everything in #549 currently generates wavefronts on-the-fly from other kinds of input.  It would be straightforward to add a class to take the wavefront itself as input though.

**Comment by rmjarvis** [comment]
Closing this as there doesn't seem to be much continuing interest.  Please reopen if this feature is still desired.
