### ISSUE TITLE
HSM runtime error for highly elliptical galaxy

### ISSUE THREAD

**Issue by tomaszkacprzak** [GalSim-developers/GalSim#384]
While working on #343 I encountered this runtime error in HSM. 
Most of the 300 sersic galaxies give a sensible HSM result, but this is an example when it crashes. Note that it happens when I use space PSF, not for the ground PSF.
The galaxy has quite big ellipticity and the image with space PSF looks very stretched, maybe that is the reason HSM has problems?

```
zupcx32$ python hsm_bug_gal72615.py 
using ground PSF
drawing
getting hsm
hsm success E1=-0.292 E2=0.637
using space PSF
drawing
getting hsm
Traceback (most recent call last):
  File "hsm_bug_gal72615.py", line 41, in <module>
    hsm_result = galsim.FindAdaptiveMom(image)
  File "/export/zupcx32/kacprzak/local/python/2.6.6/lib/python2.6/site-packages/galsim/psfcorr.py", line 395, in FindAdaptiveMom
    raise err
RuntimeError: unidentifiable C++ exception
```

I get an unidentifiable exception, but I think I didn't get the warning designed in #317 and #318. Also other C++ exceptions have more informative messages. I am using my vanilla g++ build here.

This script reproduces the error for me, also showing that it works with the ground PSF.

```
import galsim
import numpy

sersic_index = 0.9275825
half_light_radius = 0.3982398      
g = 0.7220457
gal = galsim.Sersic(n=sersic_index,half_light_radius=half_light_radius)
beta = 1. * galsim.radians
gal.applyShear(g=g,beta=beta)

print 'using ground PSF'
pixel_scale = 0.2
fwhm = 0.65 
atmos = galsim.Moffat(beta=3,fwhm=fwhm)
optics = galsim.Airy(lam_over_diam = (700e-9/4)*(180/numpy.pi)*3600)
psf = galsim.Convolve([atmos,optics])
pix = galsim.Pixel(pixel_scale)
final = galsim.Convolve([gal,psf,pix])
n_pix = 196
image = galsim.ImageD(n_pix,n_pix)
print 'drawing'
final.draw(image,dx=pixel_scale)
print 'getting hsm'
hsm_result = galsim.FindAdaptiveMom(image)
print 'hsm success E1=%2.3f E2=%2.3f' % (hsm_result.observed_shape.getE1(),hsm_result.observed_shape.getE2())
image.write('gal72615.ground.fits')

print 'using space PSF'
pixel_scale = 0.03
lam = 700.
diam = 1.3
psf = galsim.Airy(lam_over_diam=lam/diam/1.e9*206265.) 
pix = galsim.Pixel(pixel_scale)
final = galsim.Convolve([gal,psf,pix])
n_pix = 196
image = galsim.ImageD(n_pix,n_pix)
print 'drawing'
final.draw(image,dx=pixel_scale)
image.write('gal72615.space.fits')
print 'getting hsm'
hsm_result = galsim.FindAdaptiveMom(image)   
```

**Comment by rmjarvis** [comment]
Looking through the old issues, this one seems like one that could be deleted.  The original issue was solved, some further investigation fixed more problems but revealed that all is not perfect, and no one particularly is pushing for more work to be done on it any time soon.

Also, the branch named #384 is still around, but has been merged into master already, so I think we can delete that.

**Comment by rmandelb** [comment]
+1

**Comment by cwwalter** [comment]
FWIW I think we have come across this in a project we are restarting and mostly just tried to avoid it by making things not too elliptical.  I'm OK with closing it, I am mostly typing this so if it comes up again I can find the issue :)
