### ISSUE TITLE
Support input simulation catalog (PhoSim) and output data format for LSST

### ISSUE THREAD

**Issue by chihway** [GalSim-developers/GalSim#399]
The main purpose of this would be to take in PhoSim input catalogs and generate fits images that look similar to the PhoSim images and can be processed through LSST DM pipeline.

**Comment by cwwalter** [comment]
Note that the LSST-galsim CatSim interface has a lot of the code to do this already in it.  @danielsf is looking into making a stripped down version for this purpose.  This is to alert him to the presence of this issue.

**Comment by rmjarvis** [comment]
I think this issue is pretty much completely superseded by the existence of [LSSTDESC/imSim](https://github.com/LSSTDESC/imSim).  Closing.
