### ISSUE TITLE
aperture flux

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#431]
This issue is based on a conversation with Matt George (Berkeley), who is using GalSim to simulate some profiles that would be observed with a spectroscopic fiber placed on a part of a galaxy:

It would be useful to have a method like getApertureFlux() that would let you take a GSObject and a specification of the aperture (circular or elliptical with some configuration), and say how much flux is in that aperture.

This is low priority compared to issues required for GREAT3, but I thought it was a neat idea to do at some point.

**Comment by rmjarvis** [comment]
Nearly 5 years later, there seems to be little enthusiasm for this feature.  Closing.
