### ISSUE TITLE
assert statements in hsm C++ code

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#445]
An assert statement added in https://github.com/GalSim-developers/GalSim/commit/a8fe486e419e723c93ac32ccd150e808bd07774d to `find_ellipmom_1` is causing problems for estimation of moments of a galaxy with severe isophote-twisting.  I thought I might be able to quickly/easily figure out a way around this and make changes on the master branch, but it doesn't seem so simple, so I'm opening an issue for further investigation.

**Comment by rmjarvis** [comment]
I think this one also can be closed.  The proximate problem (assertion rather than exception) was solved.  And while there might be cause to investigate further why the exception happens occasionally, there doesn't seem to be a pressing demand for it, nor enthusiasm to work on it.

**Comment by rmandelb** [comment]
+1
