### ISSUE TITLE
Make class for 2D interpolation ala LookupTable in 1D

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#465]
As far as I understand, the SBInterpolatedImage inherits the standard SBProfile xValue() method.  I'm not sure that this is actually the behavior we want.

If we have some analytic profile then we can interpolate it to any position.  But if we have an SBInterpolatedImage then there is something intrinsically different about interpolating within the bounds of the original Image vs. going off its edge.  It seems like it could be valuable to have an SBInterpolatedImage xValue() method that recognizes this and emits a warning (not exception) rather than quietly going off the edge.

Update by MJ: I changed the title of this issue to conform to the conclusion we came to in the discussion below -- that this issue is to make a new class that can be properly used as a generic 2D interpolation class.

**Comment by jmeyers314** [comment]
Done as part of #549 (PR #703)
