### ISSUE TITLE
Make sure negative flux works correctly

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#472]
I have two unrelated questions that probably don't have any "issue" associated with them, but I'm not sure where else to ask...
1. There have been a few times when having a "delta function" source would be useful, e.g., to add an AGN component to a galaxy.  I know I can always add separate images of [gal,psf,pix] and [agn,pix] convolutions where "agn" is a scaled psf, but is there a way to directly convolve [gal+agn,psf,pix] where "agn" is now a scaled delta function? If not, perhaps this would be a useful addition in future.
2. I recently found it useful to draw FFT images with negative flux. This seems to work as expected with draw() so I would ask that you preserve this capability in future versions. However, although negative flux is not well defined for photon shooting, GalSim will happily drawShoot() when flux < 0 (effectively using |flux| ?) Perhaps drawShoot() should refuse to render a negative flux object, as it already does for Deconvolve objects?

[Update by MJ: I changed the title of this issue to more accurately describe the task that I think remains at this point.]

**Comment by rmjarvis** [comment]
Done via #1052
