### ISSUE TITLE
Degenerate object profiles

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#533]
In a recent GalSim script I wrote, I was drawing both stars and galaxies onto an image, and the way this currently works in GalSim, you need to handle them differently, since for the stars, you don't convolve by the gal object.  Consequently, I made the mistake of forgetting to set the flux of the stars in that case (my flux was on the gal object), and drew all the stars with flux=1, which wasn't what I wanted.

I think it would be a nice feature to have a DeltaFunction object, which would just hold a flux value and be a trivial convolution.  Then you could use this for the "galaxy" when you want just a star, and the code would be a bit more streamlined, and probably less error prone.

I believe David Kirkby @dkirkby requested this also a while back, and we suggested using a minuscule Gaussian as a workaround until we added something like this.  But it seems that the actual request never made it into an issue. (It was a side comment in another issue if I recall.)  So here it is.

Similarly, Josh Meyers @jmeyers314 was looking for a 1-d degenerate profile that was infinitesimal in one direction, but have extent in the other for simulating a dcr effect.  He got it to work by using a very sheared Gaussian, but it would be nice to have this natively.

I suspect we could even allow an arbitrary function along the 1-d direction and improve the current implementation of the dcr chromatic effect. (i.e. Figure out what that function is and then convolve by the 1-d smear, rather than add up a series of full images.)  

Anyway, this is a similar enough effect, that it is probably worth doing both together.  Although this latter feature would be significantly harder to code up, so if someone wants to implement the 0-d delta function and not the 1-d smear, I think it is ok to punt this second request to another issue.

**Comment by zunyibrt** [comment]
Hi, for a starter project, I'll like to work on implementing the 0-d delta function. Since I'm new to galsim, I'll post the plan on how I'm thinking of doing it once I have one, for advise and comments.

**Comment by zunyibrt** [comment]
Hi, I have a question regarding the handling of the delta function in k-space. Since we are dealing with a delta function, in Fourier space, we have a constant value at every location. I was wondering how to handle maxK() and stepK() in this situation and it seems like there are two possible approaches: Firstly, we could define a large value for maxK and stepK and go with that, given that it is unlikely a delta function would be rendered independently without using it as a convolution with some other psf. Another possibility would be to handle this as a special case and throw an exception should the user try to work directly with the delta function. Which approach would be better in this case?

**Comment by rmjarvis** [comment]
I think it should be fine to give them essentially infinity values.  Like 1.e100 or something like that.  You could even try a literal infinity (1.0/0.0) for both and see if anything breaks.  It might work (although math with inf is sometimes problematic).  

Then if this is used as part of a convolution (as it should always be of course), these value will be ignored in the calculation of the net stepk and maxk of the convolution.

Then it would probably also be worth checking what happens with that when someone tries to draw a DeltaFunction without convolving it and make sure that the error message is something comprehensible.  We might need to add a check or two in various places to make sure the user gets the information they need to figure out what they did wrong.

**Comment by rmandelb** [comment]
@dkirkby - We have DeltaFunctions now!  It only took 3 years... :)

Closing #533.

**Comment by rmjarvis** [comment]
We still don't have a 1-d degenerate profile.  But I suppose someone can reopen this (or another) issue if such a use case re-emerges.

**Comment by rmandelb** [comment]
Oh right, I forgot about 1d.
