### ISSUE TITLE
Vignetting, non-uniform quantum efficiency

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#553]
Real telescopes often are vignetted around the edges, which means that some of the photons that should be hitting the camera get blocked by some part of the telescope structure.  The leads to a flux variation as you approach the edges of the field of view (typically affecting the corners of the camera the most).

In GalSim, this would be implemented as a function to multiply the image values that is 1 in the center and <1 near the edges.

This is very similar to having pixels with variable quantum efficiency.  So we should also implement this.  Each pixel could have some given QE, the probability of a photon turning into an electron in a CCD -- other kinds of detectors have similar things, but they don't call it QE.  This would a applied in the same way as the vignetting.

**Comment by rmjarvis** [comment]
Propose closing this.  The variable QE is probably too trivial a step to make a bespoke GalSim function for it.  And vignetting is either equally trivial (if implemented the same way as variable gain) or too complicated (emergent from tracing rays through an optical system).  FWIW, the last item is implemented in [imSim](https://github.com/LSSTDESC/imSim) via [batoid](https://github.com/jmeyers314/batoid).

**Comment by rmandelb** [comment]
Makes sense to me.
