### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#554]
Some IR detectors have significant persistence where some (small) fraction of the previous image is not fully cleared before taking the next image.  I believe this can already be implemented in GalSim by keeping track of the order of the images, and multiplying by some small values to get an initial image on which to add the values for the next image.  

But it would probably be worth making this effect a bit more native to GalSim, and in particular add it to the config layer, so people can just specify `persistence_factor : 0.01` or whatever to get this effect.

N.B. This is somewhat related to #542, since that implementation also involves having an initial image onto which the new objects should be added.

**Comment by rmjarvis** [comment]
Did we want to include this in version 1.3?  It seems from the above conversation that this was ready for a PR, but we were waiting on #590 being merged in.  That's been done, so do we want to try to include this in the next release, or proceed without this issue?

**Comment by rmandelb** [comment]
@arunkannawadi , what do you think?  What's the status on your end?

**Comment by arunkannawadi** [comment]
For persistence, some work needs to be done by the user before calling the
persistence routine, such as storing the previous exposures in a list. So
this is something that must go on the demo as well. I guess it makes sense
to merge it in the master with an update in demo13. I can include in the
demo by the end of this week.

On Sun, Apr 19, 2015 at 8:47 PM, Rachel Mandelbaum <notifications@github.com
> wrote:

> @arunkannawadi <https://github.com/arunkannawadi> , what do you think?
> What's the status on your end?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/554#issuecomment-94329586>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
Sorry, I didn’t understand - are you proposing to include it directly on master?  It would be enough of a change that a pull request is necessary so we can review the change.

Also, how are you going to modify the demo to include this?  Make a series of exposures in the same band instead of a single one in each band?

-------------------------------

Rachel Mandelbaum
rmandelb@andrew.cmu.edu
http://www.andrew.cmu.edu/~rmandelb/

**Comment by rmjarvis** [comment]
I guess this issue is done.  Merged via PR #710.
