### ISSUE TITLE
Inter-pixel capacitance

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#555]
Some NIR detectors apparently have an effect called inter-pixel capacitance where charge in a pixel can induce voltage in neighboring pixels, which then spuriously gets interpreted as photons falling into those pixels.

I'm still not completely sure why this isn't just a convolution that can be included as part of the PSF.  A write-up (unpublished) by Jason Rhodes and others seems to imply that this can be modeled by convolving by a 3x3 kernel, which I would think means that it could be included as part of the PSF.  But I was told that it's not that simple.  

So this issue is to investigate this issue in more detail and find a convenient way to include this effect in GalSim.

cf. http://adsabs.harvard.edu/abs/2008SPIE.7021E...3S

**Comment by rmandelb** [comment]
Closing #555.
