### ISSUE TITLE
Quantization

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#558]
We have been fairly loose with how we quantize the output ADU of our pixels.  By which I mean we haven't really paid attention to it at all. :)  

Currently, photon shooting things without negative regions (so not InterpolatedImages) will end up with an integer number of ADU in each pixel.  At least before noise is added that is.  And adding Poisson noise to an image will turn the values into integers I believe.

But in most other cases, the output is just real valued data.  Not integers.  If users care about this, it might be worth having a quantization step somewhere along the way to make sure the data are turned into integral values at the appropriate place in the readout process.

This might be as simple as passing `dtype=integer` to the `drawImage` command.  But I am not sure if this actually does precisely the correct thing currently.  So we should check that this works appropriately, and maybe add an option to let the user have quantized output will still having `dtype=float` (which they might want for other reasons).

**Comment by rmandelb** [comment]
Closing #558.
