### ISSUE TITLE
Whether to, and how to, check for power spectra being (mostly) positive in the generation of correlated noise

### ISSUE THREAD

**Issue by barnabytprowe** [GalSim-developers/GalSim#587]
This is a somewhat esoteric issue in the guts of the `correlatednoise.py` module, and came up in discussions on #579 , the pull request for #563.

The problem is broadly summarized in the following: https://github.com/GalSim-developers/GalSim/pull/579#discussion-diff-15014527

And Mike put forward an opinion about this issue here: https://github.com/GalSim-developers/GalSim/pull/579#discussion-diff-15129638

This issue is to discuss:

* Whether it makes sense for the code to work out if the Power Spectrum (PS) that is going to be used contains significant negative power, which might be present due to approximations in the rendering of the Correlation Function from which it is Discrete Fourier Transformed

* Whether, if so, GalSim should warn the user about it.

* What the warning should say.

* (part of the first point I guess) Whether we can think of a way to sensibly define what too much negative power is.  1% has been suggested, but we might need to explore a little bit what we expect in a reasonable use case, I actually have no idea if 1% is a much too high or too low threshold.

Then we'll implement whatever we think is best.

**Comment by rmjarvis** [comment]
Recommend closing this in light of the fact that it has been sitting dormant for 2+ years with no user complaints related to the current behavior.  Any objections?

**Comment by rmandelb** [comment]
Fine with me.
