### ISSUE TITLE
WFIRST module

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#590]
This issue is similar in flavor to #556, but I'm interested in working on this one first.  The idea is to make a WFIRST module.  Comments on any of the below are welcome:

(1) Bandpasses: I would like there to be routines to get Bandpass objects for the planned WFIRST bandpasses, i.e.
```
my_bandpass = galsim.wfirst.getBandpass(...)
```
where the argument might be a string that is the name of the bandpass.  An alternative would be to make a routine that returns all bandpass info, e.g., 
```
bandpass_list = galsim.wfirst.getBandpasses()
```
where it returns a list of tuples, each containing the name of the bandpass and the associated Bandpass object.

(2) WCS information for the chips, similar to what's described on #556.

(3) PSF information.  I need to dig a bit more into what information I have before deciding how to put this in.  Will probably post some thoughts once I've done that.

(4) Information about various detector effects such as those discussed in #552, #553, #554, #555.  My assumption is that the code to apply those effects will not be in a WFIRST module, but rather in a GalSim "detectors" (or something) module, but presumably those routines will require inputs like the function defining nonlinearity, the type of kernel to apply to simulate inter pixel capacitance, etc.  So the WFIRST module needs to know those things about the WFIRST detectors, to provide inputs for anyone who wants to use the routines in the "detectors" module to make WFIRST-y detector effects.

Any comments or suggestions?

**Comment by rmjarvis** [comment]
I made the changes to FitsHeader for you.  It should be working.  Let me know if that also makes AstropyWCS work now.  It should be able to handle TAN-SIP just fine, so you should not need to muck around with `fits_wcs_types`.  If that still doesn't work, let's figure out why and fix it rather than override the current `fits_wcs_types` list.

**Comment by rmandelb** [comment]
Cool, thanks.  I’ve made a note to try the AstropyWCS stuff the next time I do work on this branch.

**Comment by rmandelb** [comment]
@arunkannawadi - please take a look at the latest version of demo13, and see what you think.  It's a much more realistic galaxy population.

**Comment by rmandelb** [comment]
@arunkannawadi , we have to think about unit tests before we can make a PR (which in any case has to wait until #618 is merged, but it would be good to be ready as soon as that is done).

Here are the routines that currently lack unit tests:
1) WFIRST background routines.
2) WFIRST PSFs.
3) WFIRST WCS.
4) WFIRST bandpass.
5) COSMOS catalog stuff that I just put in catalogs.py.
6) The routine to include piston, tip, and tilt in the OpticalPSF.

For (1), I have Chris Hirata's exposure time calculator, so I could just calculate the results using his calculator for a few positions on the sky, and compare them with what comes out of GalSim.  For (3), I have code from Jeff Kruk that he developed for the WFIRST project office, so I could store a WCS for some position and rotation angle and check that the GalSim routine gives the same WCS.  Any ideas for (2), (4), (5), or (6)?

**Comment by arunkannawadi** [comment]
@rmandelb, I'll have a look at the code by early next week and see if I can
come up with unit tests for the ones you've listed.

On Wed, Feb 18, 2015 at 10:10 AM, Rachel Mandelbaum <
notifications@github.com> wrote:

> @arunkannawadi <https://github.com/arunkannawadi> , we have to think
> about unit tests before we can make a PR (which in any case has to wait
> until #618 <https://github.com/GalSim-developers/GalSim/issues/618> is
> merged, but it would be good to be ready as soon as that is done).
>
> Here are the routines that currently lack unit tests:
> 1) WFIRST background routines.
> 2) WFIRST PSFs.
> 3) WFIRST WCS.
> 4) WFIRST bandpass.
> 5) COSMOS catalog stuff that I just put in catalogs.py.
> 6) The routine to include piston, tip, and tilt in the OpticalPSF.
>
> For (1), I have Chris Hirata's exposure time calculator, so I could just
> calculate the results using his calculator for a few positions on the sky,
> and compare them with what comes out of GalSim. For (3), I have code from
> Jeff Kruk that he developed for the WFIRST project office, so I could store
> a WCS for some position and rotation angle and check that the GalSim
> routine gives the same WCS. Any ideas for (2), (4), (5), or (6)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/590#issuecomment-74879411>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
@rmjarvis - I have a question for you about this branch, which is going to be ready for a PR after the addition of just a few unit tests (and after we merge #618).  For context, this branch includes not just code, but also some data that is in share/ and therefore that will be installed with the other stuff that's already in there when users install GalSim.  I have two questions for you:

- Do you think we should try to make some option in scons so that people can stop it from installing this galsim.wfirst module and its associated data if they don't want to use it?  (The module itself is no big deal, of course, but perhaps they don't want all these bandpasses and other things stored in the installation directory because it's too much clutter?)  Or is this not worth bothering with?

- Perhaps more importantly, do we want to always run the unit tests associated with the module, or should those be optional?

So, Mike, I'm particularly directing these questions to you because (a) as far as I know you won't particularly be using this module yourself and (b) if we want to do either of the above things, I will probably be asking you for help :)

**Comment by rmjarvis** [comment]
I think a rule of thumb with regards to the share directory is that it is fine to stick things in there that are significantly smaller than the compiled library.  On my Mac, the file `libgalsim.1.2.dylib` is 2.8 MBytes.  The things that are currently in the `share` directory total 168 KBytes.  So no big deal.  If you keep things to around that size, then I wouldn't worry about it.  If you want to have things that are several MBytes or bigger, you might want to find a different way to distribute them.

As for the unit tests, I think it's probably fine to always run them.  I didn't do that with the DES module, which was probably a mistake, since there have been times when that module was broken by various changes we made, and it took a while to discover the problem and fix it.  So it would probably be better to have any module tests always be run with `scons tests`.

**Comment by rmandelb** [comment]
> I think a rule of thumb with regards to the share directory is that it is fine to stick things in there that 
> are significantly smaller than the compiled library. 

Can you define "significantly"?  On this branch, ```share``` is up to ~800K.   (The dylib on my Mac is 3.7M, quite a bit larger than yours - interesting.)  Anyway, once we're up to ~20% rather than just a few %, do you think that is a problem?

Re: unit tests, I'm happy with that, it's less work to just make them in the usual way than to try to do something fancy to only run in certain circumstances!

**Comment by rmjarvis** [comment]
> Can you define "significantly"?

I don't know.  800K is probably ok, although you could think about applying a critical eye to some of the larger items to see if they could be made smaller.  But it's probably fine.

The thought process is that by installing GalSim on their system, the user is essentially agreeing that we can take up as much space on disk as needed to get GalSim working.  That's apparently a few MB.  We don't want to abuse that implicit agreement by shuttling in other stuff that take up more space than that.

Update: it looks like `_galsim.so` is even bigger.  On my computer, it's another 5 MB.  So together with all the .py files that get installed, the total might be close to 10 MB right now.  So if share is <1MB, I don't see it being a problem.

**Comment by rmandelb** [comment]
@rmjarvis , you had fixed up some FitsHeader related issues on this branch a while ago, and everything seemed to work fine on my laptop.  Now that we're preparing for a pull request, I was running the unit tests on the Linux cluster here as well, and found that some of the associated tests in ```test_fitsheader.py``` are failing:
```
Traceback (most recent call last):
  File "test_fitsheader.py", line 193, in <module>
    test_read()
  File "test_fitsheader.py", line 106, in test_read
    header.update(d)
  File "/home/rmandelb/software/lib/python2.7/site-packages/galsim/fits.py", line 1198, in update
    for k, v in dict2.iteritems:
TypeError: 'builtin_function_or_method' object is not iterable
```

In the interest of full disclosure, the cluster doesn't have astropy installed system-wide, and the pyfits version is on the older side (3.0.8).  Is the answer that I should get astropy or a later version of pyfits, or do we still want to support this older pyfits, in which case are you able to either fix this or point me in the right direction?

Thanks!

**Comment by rmandelb** [comment]
@arunkannawadi - do you have any further work to do on this branch before we make a pull request?

**Comment by rmjarvis** [comment]
> some of the associated tests in test_fitsheader.py are failing

Fixed.

**Comment by rmandelb** [comment]
Great, thanks!

**Comment by rmandelb** [comment]
@arunkannawadi - I realized that I couldn't make achromatic=True a valid option, because getPSF doesn't know about the WFIRST bandpasses (which I had forgotten).  So "True" is now officially caught and an exception is thrown.  However, there is one new option which is that you can give ```achromatic``` a Bandpass object, and it'll use the effective wavelength automatically.  In other words, the options for ```achromatic``` are

- False -> for a chromatic PSF
- a float -> for an achromatic PSF at that wavelength (nanometers)
- a bandpass -> for an achromatic PSF at the effective wavelength of that bandpass

I hope that helps.

**Comment by arunkannawadi** [comment]
@rmandelb: Ah, yes! That sounds good.

On Wed, Feb 25, 2015 at 1:17 PM, Rachel Mandelbaum <notifications@github.com
> wrote:

> @arunkannawadi <https://github.com/arunkannawadi> - I realized that I
> couldn't make achromatic=True a valid option, because getPSF doesn't know
> about the WFIRST bandpasses (which I had forgotten). So "True" is now
> officially caught and an exception is thrown. However, there is one new
> option which is that you can give achromatic a Bandpass object, and it'll
> use the effective wavelength automatically. In other words, the options for
> achromatic are
>
>    - False -> for a chromatic PSF
>    - a float -> for an achromatic PSF at that wavelength (nanometers)
>    - a bandpass -> for an achromatic PSF at the effective wavelength of
>    that bandpass
>
> I hope that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/590#issuecomment-76021829>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by arunkannawadi** [comment]
This is a minor thing, but nevertheless, I think it's important and ask for
it. Effective wavelengths for WFIRST bandpasses are stored in Angstroms,
not in nanometers. So it would be better if the getPSF routine within the
WFIRST module accepts the wavelength in Angstroms as well. There is a
factor of 10 that I as a user would have to put in to use this feature.

On Wed, Feb 25, 2015 at 3:27 PM, Arun Kannawadi <arunkannawadi@cmu.edu>
wrote:

> @rmandelb: Ah, yes! That sounds good.
>
> On Wed, Feb 25, 2015 at 1:17 PM, Rachel Mandelbaum <
> notifications@github.com> wrote:
>
>> @arunkannawadi <https://github.com/arunkannawadi> - I realized that I
>> couldn't make achromatic=True a valid option, because getPSF doesn't know
>> about the WFIRST bandpasses (which I had forgotten). So "True" is now
>> officially caught and an exception is thrown. However, there is one new
>> option which is that you can give achromatic a Bandpass object, and
>> it'll use the effective wavelength automatically. In other words, the
>> options for achromatic are
>>
>>    - False -> for a chromatic PSF
>>    - a float -> for an achromatic PSF at that wavelength (nanometers)
>>    - a bandpass -> for an achromatic PSF at the effective wavelength of
>>    that bandpass
>>
>> I hope that helps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GalSim-developers/GalSim/issues/590#issuecomment-76021829>
>> .
>>
>
>
>
> --
> Regards
>
> Arun Kannawadi Jayaraman
> PhD candidate, Dept. of Physics,
> Carnegie Mellon University,
> Pittsburgh, PA 15213
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
Hi Arun - I�m not sure what you mean; if I load up the WFIRST bandpasses using getBandpasses(), and take J129 for example, the effective wavelength reported by the Bandpass object as 1292.  This is nm, since all bandpass calculations are done internally in nm.  Where do you need a factor of 10?

**Comment by arunkannawadi** [comment]
Sorry, I had seen wavelengths being given in units of Angstroms while have
to extend SEDs to the infra-red regime. For the bandpasses, they are fine!

On Thu, Feb 26, 2015 at 6:57 AM, Rachel Mandelbaum <notifications@github.com
> wrote:

> Hi Arun - I�m not sure what you mean; if I load up the WFIRST bandpasses
> using getBandpasses(), and take J129 for example, the effective wavelength
> reported by the Bandpass object as 1292. This is nm, since all bandpass
> calculations are done internally in nm. Where do you need a factor of 10?
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/590#issuecomment-76166326>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
Closing #590.
