### ISSUE TITLE
__version__ for GalSim

### ISSUE THREAD

**Issue by richardgmcmahon** [GalSim-developers/GalSim#610]
GalSim does not seem to have a __version__ variable aka many other packages. IMHO this is 
a good idea especially on shared system or when paths are messy so that code and humans can check what version they are running.

aka

import astropy
print('astropy.__version__:  ', astropy.__version__)

**Comment by rmjarvis** [comment]
I cherry picked this onto master for inclusion in v1.2.  Closing.
