### ISSUE TITLE
PyAstWCS works but FitsWCS doesn't?

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#624]
I have a possibly interesting WCS problem.

I have a FITS header that is in TAN-SIP format, which should be readable by WCSTools, Starlink AST, and one other library that GalSim doesn't know how to talk to.  Given the warnings in fitswcs.py about WCSTools being slow, I went with Starlink AST.  The problem I'm having is that if I do something like
```
wcs = galsim.PyAstWCS('myfile.fits')
```
it makes a WCS with no problem and I can use the various methods like ```toImage()``` and so on.  But if I do
```
wcs = galsim.FitsWCS('myfile.fits')
```
then I get this warning "All the fits WCS types failed to read myfile.fits.  Using AffineTransform instead, which will not really be correct."  As far as I can tell, when the FitsWCS constructor is looping over the WCS types, it really is hitting an exception when it does this two-step process of reading in the header and then using the ```_readHeader``` method, unlike when directly instantiating the ```PyAstWCS``` directly.

In principle this isn't a very big deal; I could just require Starlink AST for these WCSs, instead of using FitsWCS (which would allow users with either Starlink AST or WCSTools to use these WCSs).  But it seemed a bit odd so I thought I would ask if this is something you've run into before, @rmjarvis , or have some ideas about?

**Comment by rmjarvis** [comment]
The test suite does test a file with TAN-SIP format, and on my machine it works fine with FitsWCS, so I guess there must be something different about the file you are using that messes it up.

I can take a look if you want.  Send me the fits file and I'll try to figure out what is going wrong.

**Comment by rmandelb** [comment]
Thanks.  Will send it in a moment.

**Comment by rmjarvis** [comment]
I haven't been able to reproduce the problem.  Maybe you have an old version of either pyfits or starlink?  I have version 3.3 of each, which are the latest versions available with pip:
```
Mike@Fife:~/Downloads $ pip search starlink-pyast
starlink-pyast            - A Python wrapper for the Starlink AST library
  INSTALLED: 3.3 (latest)
Mike@Fife:~/Downloads $ pip search pyfits
pyfits                    - Reads FITS images and tables into numpy arrays and manipulates FITS
                            headers
  INSTALLED: 3.3 (latest)
Mike@Fife:~/Downloads $ python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import galsim
>>> w = galsim.FitsWCS('myfile.fits')
/Library/Python/2.7/site-packages/starlink/Atl.py:113: PyfitsDeprecationWarning: The ascard function is deprecated as of version 3.1 and may be removed in a future version.

        Use the `.cards` attribute instead.
  if self.index < len( self.hdu.header.ascard ):
/Library/Python/2.7/site-packages/pyfits/card.py:70: PyfitsDeprecationWarning: The CardList class has been deprecated; all its former functionality has been subsumed by the Header class, so CardList objects should not be directly created.  See the PyFITS 3.1.0 CHANGELOG for more details.
  PyfitsDeprecationWarning)
/Library/Python/2.7/site-packages/starlink/Atl.py:114: PyfitsDeprecationWarning: The ascard function is deprecated as of version 3.1 and may be removed in a future version.

        Use the `.cards` attribute instead.
  result = self.hdu.header.ascard[ self.index ].ascardimage()
/Library/Python/2.7/site-packages/starlink/Atl.py:114: PyfitsDeprecationWarning: The ascardimage function is deprecated as of version 3.1 and may be removed in a future version.

        Use the `.image` attribute instead.
  result = self.hdu.header.ascard[ self.index ].ascardimage()
>>> w
PyAstWCS('header',PositionD(x=0.0, y=0.0))
>>> 
```
So some warnings, but it seems to work correctly.

**Comment by rmandelb** [comment]
You're right, my pyfits was 3.0.3 which is pretty old.  I decided to bite the bullet and install astropy, which I'd been meaning to do for ages, and now it's all good.  (Of course, given the order of things that FitsWCS tries, it ends up using an AstropyWCS.  But if I swap the order so that FitsWCS tries PyAstWCS first, that also works without any complaint.)

Do you think it's worth putting in anything in the FitsWCS documentation about possible issues with older pyfits versions?  Or is this just covered under the standard "don't use ridiculously old versions of packages" advice?

**Comment by rmjarvis** [comment]
Considering how easy it is to get the latest version of each of these packages with pip, I think it's probably fine to just recommend that people try upgrading if they have problems.  But if you want, I don't mind trying to get pyfits 3.0 and trying to reproduce your error.  There might be some check that isn't being done correctly.  OTOH, if I recall, 3.0.3 [isn't available anymore](http://www.stsci.edu/institute/software_hardware/pyfits/Download), and for another of your issues, 3.0.13 didn't reproduce the problem...

**Comment by rmandelb** [comment]
Nooooo, I definitely do NOT think it’s worth your time to get 3.0 and try to reproduce my error.  I’m going to go with a warning in the FitsWCS docstring on master, mentioning that upgrading can solve problems encountered with older pyfits versions.

**Comment by rmandelb** [comment]
https://github.com/GalSim-developers/GalSim/commit/32cd5849346f83bc1f451712edb212a29ac68706

**Comment by rmandelb** [comment]
Closing #624.

**Comment by rmjarvis** [comment]
> Nooooo, I definitely do NOT think it’s worth your time to get 3.0 and try to reproduce my error.  

lol.  ok.  The edit looks fine.
