### ISSUE TITLE
how to change the .fits file format in galsim?

### ISSUE THREAD

**Issue by phioen** [GalSim-developers/GalSim#627]
I have generated an image with galsim, and write it to a .fits file.
the format of the .fits file is -32, float. 
What shall I do if I want to make it double precision?
Or Is there any other way to out put the image just some simple ascii file with double precision.

**Comment by phioen** [comment]
sorry, I find out the solution. if the image I generated is double precision, then the fits file is also double precision.

**Comment by rmandelb** [comment]
Yes, that's correct.
