### ISSUE TITLE
SED units

### ISSUE THREAD

**Issue by danielsf** [GalSim-developers/GalSim#629]
Hello,

I am working to make GalSim distributable with the LSST software stack.

One issue I have discovered:

In the tagged versions of galsim/sed.py in the __init__() for the SED class, there is no unit conversion done when converting SEDs from "flambda" to"fphotons".  In master, there are values for Planck's constant and the speed of light hard-coded into the method.  These are absent from the tagged versions.

Would it be possible to release a new tagged version that includes the unit conversio?  The lack of a unit conversion is fouling up our unit tests.  If this is not feasible, we will go ahead and distribute a copy of GalSim taken from the current master.

I'm trying to get our distribution ready in the next day or two, so I would appreciate a quick response (even if it is just "no: we'd rather wait until we've done some more development").

Thank you,

Scott Daniel
University of Washington Astronomy Department

**Comment by rmjarvis** [comment]
Actually, we are just about to release version 1.2.0, which is basically the current version of master.  So if you wait a day or two, you should have a tagged version that includes the `wave_type` argument you need.

**Comment by danielsf** [comment]
okay.  Thanks.

**Comment by rmjarvis** [comment]
Version 1.2.0 is released.  Closing this issue.
