### ISSUE TITLE
confusion between variance vs. std dev of noise

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#630]
I found a bug in UncorrelatedNoise or perhaps something related.  If you do this:
```
import galsim
im = galsim.Image(256,256)
ucn = galsim.UncorrelatedNoise(variance=0.1)
im.addNoise(ucn)
print im.array.std(), im.array.var()
```
then you'll get a standard deviation of 0.1, variance of 0.01.  But I had specified variance=0.1.  So something is getting labeled incorrectly somewhere in UncorrelatedNoise or the routines that it calls.

I will dig into this some more in a bit, just wanted to open the issue.

@emhuff, this isn't all of the problem you're seeing, but it's definitely part of it.

**Comment by rmjarvis** [comment]
Wow.  Sorry. That's probably my mistake.  And I don't seem to have written the appropriate unit tests that would have caught this.

There is one test that would have caught it, but it uses var=1.0, which misses the missed sqrt.  Oops.  I'll fix this.

**Comment by rmandelb** [comment]
Thank you!  I didn't have time to look into it yet, so if you have an idea where it could be happening, it would be great if you can fix it.

So... time for GalSim 1.2.1?  ;)
