### ISSUE TITLE
how to configure the accuracy?

### ISSUE THREAD

**Issue by phioen** [GalSim-developers/GalSim#633]
I have tried to find the way, but did not get a good method yet
For instance, I have a psf and a galaxy object, I deconvolve the galaxy with psf, and convolve back.
I compare the shear between two galaxies, there is about 1e-8 difference ( numerical error)?
What shall I do if I want to have a 1e-10 errors.

**Comment by rmandelb** [comment]
To learn about how to adjust parameters controlling numerical accuracy, you will find it helpful to read the docstring for the GSParams class (do help(galsim.GSParams) in the python interpreter or look at the online documentation, http://galsim-developers.github.io/GalSim/structgalsim_1_1_g_s_params.html ).  You can pass a GSParams object in when initializing your galaxy and PSF, using the ```gsparams``` keyword argument.

However, in the context of shear, 1e-8 is actually quite good.  For what application do you need 1e-10 errors on the shear?

**Comment by phioen** [comment]
the color gradient bias, which is around 1e-5, 1e-4 or so, then  people want to make sure the numerical noise better to be 1e-10. but I guess 1e-8 should be okay. I ask also, maybe in future needed it.
thanks a lot.

**Comment by rmandelb** [comment]
To be honest, I have a hard time imagining that you really could determine such a quantity to 1e-5 (meaning 1e-10 numerical error / 1e-5 effect).  I think that many other factors such as the model for galaxy colors and light profiles must be far more important than that.

But there are definitely situations where you might find it helpful to adjust the numerical accuracy parameters.  Anyway, it sounds like you have the information you need, so I am closing this issue.  Please re-open if you have additional questions on this topic.

**Comment by rmjarvis** [comment]
I'll just add one more comment.  There is a better description of how to use a GSParams object in the python layer in the documentation for [GSObject](http://galsim-developers.github.io/GalSim/classgalsim_1_1base_1_1_g_s_object.html#a9a6d32438a27766235e087d76acdaa18).  Also, you can type `help(GSParams)` in Python to get some better documentation for GSParams in Python that Doxygen unfortunately doesn't really capture correctly.  ([Here](https://github.com/GalSim-developers/GalSim/blob/releases/1.2/galsim/base.py#L2203) is the place in the code for that doc string, if you'd rather read it online.) So those two docs may be helpful to read as well.
