### ISSUE TITLE
sky scenes

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#635]
I've been asked a few times recently whether GalSim has or will have some default "sky scenes", i.e., a way to decide on some galaxy or star sample to simulate rather than every user having to choose every single aspect of the sky scene themselves.  Obviously for specific applications people WILL want complete control over the galaxy/star sample they are simulating, but it seems like it might be valuable to have ~2-3 simple samples of objects to simulate.  For example:
- a star sample with a reasonable flux distribution in some optical band.
- a COSMOS-based galaxy sample.

One option is to simply put these into a demo to tell people to look at that code.

Another option is to make a "sky scene" module that returns a star catalog and a galaxy catalog that have the parameters needed to generate a reasonable sample.  It's obvious we can't make this infinitely customizable without having a gazillion parameters, which I think would be the argument for just putting it in a demo.  But I think that for example getting a COSMOS sample that is reasonable down to some limiting magnitude could be useful enough that it might be worth having a routine for it.  (I find myself often copying that code from the GREAT3 simulation scripts and thinking "why am I copying this again?!").

If there is some agreement on this, I'm likely to do this in #590 for use in the demo of WFIRST module capabilities as the last task before making a PR.

**Comment by dkirkby** [comment]
Perhaps the first example at http://weaklensingdeblending.readthedocs.org/en/latest/examples.html#quick-simulation-demo could serve this purpose, at least until something better is available?

**Comment by rmandelb** [comment]
Just a quick update: I put some code to make a realistic galaxy catalog (either COSMOS real galaxies, or parametric representations that have the right joint distributions of flux / size / shape) on #590.  I am going to integrate it into a demo that shows how to use it.

I don't plan to make a star-based sky scene (or a mixed galaxy + star sky scene) for that branch, so I think this issue should be left open after the PR for #590, but with less work to do.

**Comment by rmjarvis** [comment]
Propose closing this.  demo13 now includes a star + galaxy scene as an example of how to do something simple.  And I suspect anything more realistic nowadays would be in the context of something like [SkyCatalogs](https://github.com/LSSTDESC/skyCatalogs), so probably doesn't belong in GalSim proper.

**Comment by rmandelb** [comment]
Makes sense to me.
