### ISSUE TITLE
Wiki page describing demo scripts

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#636]
I noticed from a slide that Bhuv just showed that had both Cosmosis and GalSim on the same page that Cosmosis seems to have a nice list of demo scripts that describe what each one is about.

We should do that too!

I imagine a wiki page that lists each demo with:
- One line description of what the demo is about
- Key code features that are introduced in the demo
- Links to the .py and .yaml files

**Comment by rmandelb** [comment]
+1

For the "key code features", we can probably grab that directly from the docstring.

Are you volunteering?  :)

**Comment by rmjarvis** [comment]
> Are you volunteering? :)

Sure.

**Comment by rmandelb** [comment]
Is this done?  https://github.com/GalSim-developers/GalSim/wiki/Tutorials looks fairly complete to me.

**Comment by rmjarvis** [comment]
I think so.  I still need to go over the config documentation, since my updates were done before all the config issues were finalized, but this aspect of the wiki edits are probably fine.  At least good enough to do "code review" if you're so inclined.

**Comment by rmandelb** [comment]
What's the best way to do this?  I know there's a way to git clone the wiki pages, but I'm not sure there's a good way to view the source on GitHub.  So should I just edit the wiki and let you know of any comments and questions?

**Comment by rmjarvis** [comment]
Sure.  Edit directly if you see any errors, and I guess post here anything that would normally be an inline comment.  

BTW, I do have a git clone of the wiki pages.  It makes batch editing much easier, since I can use vim rather than the web editor.

**Comment by rmandelb** [comment]
OK.  I just edited a bit, but basically it seems great to me.  Shall we close this?

**Comment by rmjarvis** [comment]
Thanks.  I just finished the other thing that this issue was meant to prompt me to do, which is to go through the documentation and make sure it was all up to date with other changes we've made since issue #691.  I've finished that now, so I think I'm ready to close this.  However, I have a question, and this seems like a good place to ask it.  

We now have a series of wiki pages called Config-Documentation-v1.x.md for various x values.  Is there a good reason to keep doing that?  I think we can probably just have Config-Documentation.md be the docs for the current release (which is now called Config-Documentaion-v1.3.md) and have a future docs page (or pages) which can be the staging area for an upcoming version.

Then when we cut a new release, I think we can just copy over the staged page(s) to the unversioned names and delete the old ones.  Anyone see any potential problem with that approach?

**Comment by rmandelb** [comment]
Do we think that people who actively use GalSim are always updating to the latest tagged release?  If not, then it's worth keeping at least one release back.   So once we have v1.4, I would like to keep v1.3 up as well (but I agree about getting rid of the older ones, given the amount of time between releases).

**Comment by rmjarvis** [comment]
I suspect people who are looking to the wiki for how to do something new will probably also be willing to update to the latest version.  But I think it's fine to keep one version back as well as the current one.
