### ISSUE TITLE
Running HSM on const view

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#637]
I can't think of an obvious reason why the HSM FindAdaptiveMom() needs to modify an image, so I was surprised that I cannot use a const view, e.g.
```
img = galsim.Image(10,10)
cview = img.view(make_const=True)
cview.FindAdaptiveMom()

ArgumentError: Python argument types in
    galsim._galsim._FindAdaptiveMomView(ConstImageViewF, ImageViewI)
did not match C++ signature:
    _FindAdaptiveMomView(galsim::ImageView<int> object_image, galsim::ImageView<int> object_mask_image, double guess_sig=5.0, double precision=1e-06, double guess_x_centroid=-1000.0, double guess_y_centroid=-1000.0, boost::shared_ptr<galsim::hsm::HSMParams> hsmparams=None)
...
```
I see a FindAdaptiveMomView() method in the C++ layer, so perhaps this function just needs to be made visible in the python layer?

http://galsim-developers.github.io/GalSim/namespacegalsim_1_1hsm.html#a3b02518ad082885608ebea6950bf4a9c

**Comment by rmandelb** [comment]
Hi David - the code you pointed to actually is the code that is being used already.  If you didn�t use the make_const option, you�d get an ImageView (which FindAdaptiveMom works on) but your code is getting a ConstImageView class, which is different.  It wouldn�t be hard to make it work for those too, but I believe it would require some minor work on the C++ side, unless the python-level FindAdaptiveMom were to check for ConstImageView objects and make a temporary ImageView object before calling the C++ routines.

**Comment by rmandelb** [comment]
Looks like github had some weird issue converting apostrophes in the e-mail reply I sent.  Weird.

Anyway, Mike suggests I do this on the C++ side, so that's what I'll do.  (Should be very fast.)

**Comment by dkirkby** [comment]
The C++ method already expect a `const ImageView<T>`, so perhaps the const-ness of my input view is being lost somewhere?

**Comment by rmandelb** [comment]
No, the point is that the ImageView class is different from the ConstImageView class (even if you happen to declare the const-ness of the ImageView in question).  They are both subclasses of BaseImage.  So the solution is to make the routine take a BaseImage, which works for Images, ImageViews, and ConstImageViews.  I checked and this works.

**Comment by rmandelb** [comment]
Closing #637.
