### ISSUE TITLE
Circular top-hat profile

### ISSUE THREAD

**Issue by chazshapiro** [GalSim-developers/GalSim#639]
Hi - I would like to request a circular top-hat profile, or an ellipse more generally.

This would be useful to the Precision Projector Lab for modelling detector emulations in which the sources are simply illuminated holes.  The profile would always be convolved with a bandlimited PSF.  For now, we use PSFs much larger than the holes (approximate point sources), but this won't always be the case.

Thanks,
Chaz

**Comment by rmjarvis** [comment]
Sure.  This would be easy to add.  I'll just do the circle, since you can always shear it to get any ellipse you want, so a circle is a sufficient implementation.

**Comment by chazshapiro** [comment]
Wonderful - thanks!

**Comment by chazshapiro** [comment]
very cool - thanks

---
