### ISSUE TITLE
InterpolatedKImage

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#642]
In scoping out what will be required for #640, Josh Realized it would be helpful to have a way to specify a profile in terms of its fourier image.  i.e. an InterpolatedKImage object.

I think this could share most of the implementation that is currently in SBInterpolatedImage.  Really, it would just need to change how xtab and ktab get built, using the input image for the latter rather than the former.  Then once they are built, most of the rest of the functions would work the same way.

So I think SBInterpolatedKImage could either be a subclass of SBInterpolatedImage or we could make a new base class that both could derive from.

**Comment by jmeyers314** [comment]
Hi all,
I think I have a handle on the c++ part of this issue now.  I've added a `SBInterpolated` parent class for both `SBInterpolatedImage` and `SBInterpolatedKImage`, and roughly laid out which methods/variables are in common and which probably need to be in the derived classes.  I also completely excised the `MultipleImageHelper` class, which helped me see how `SBInterpolatedImage` worked.

What's left is the Fourier logic part.  I have a few basic questions on how to go about filling in _ktab and _xtab in `SBInterpolatedKImage`:

1. Do the `pad_factor`, `stepk`, and `maxk` parameters make sense for `SBInterpolatedKImage`?  It's not obvious to me what one would do with any of these if provided the Fourier-space image directly instead of calculating it from either a real-space image or some analytic expression.
2. Does dk (=kimage.scale from the python layer) need to be directly passed to the `SBInterpolatedKImage` constructor?  I didn't see anything like scale or dx in `BaseImage`, but maybe I missed it.
3. What's a reasonable size for _xtab?  I guess the simplest thing is to get a `goodFFTSize` on _ktab (or _ktab + _kinterp), pad _ktab to this size with zeros, and then transform.  I'm not sure if one needs to consider anything like `pad_factor` here or not.

Does that sound right?

**Comment by rmjarvis** [comment]
I'm not sure I know all the answers here, but hopefully @gbernstein can correct me if I'm wrong about any of this.

First, I think we probably wouldn't need `pad_factor`.  Or any of the padding options that we have in the regular InterpolatedImage class.  

I think stepk can probably be taken as the scale of the Fourier image.  I guess we'd want to restrict the image to not have any complicated wcs.  Just a pixel scale, which people should be able to override I guess with a scale parameter to the InterpolatedKImage constructor.

Similarly, maxk will be the size of the image provided * dk.  If we take the provided image as the exact Fourier image, then there is no power at larger k values than this.  We should pad up to the next power of 2 or 3 x power of 2.  But other than this detail, I think we can just take what the user provided.  

Finally, another difference I think is that we'll only have kinterp.  I don't think it makes any sense to consider an xinterp in this case.  Although I guess if we want to allow photon shooting of this type of object, we might need to build the xtab and have some way to interpolate it.  Maybe Gary has some thoughts about what the right interpolant would be to use in this case.

**Comment by jmeyers314** [comment]
Thanks @rmjarvis.  I think that's pretty much what I had in mind.  One minor detail, won't we need xinterp for (the potentially rarely used) `xValue` too?  

Although, now that I take a closer look at `SBInterpolatedImage.kValue`, which I suppose is analogous to `SBInterpolatedKImage.xValue`, I realize I don't quite get how this works.  What's `xKernelTransform`? Why not just `return _ktab->interpolate(k.x, k.y, *_kInterp);`?

I think maybe I need to read through Bernstein&Gruen again... :)

**Comment by gbernstein** [comment]
Agreed, the pad factor and the xinterp have no meaning if you are providing a k-space grid which you have already decided is dense enough (dk) to portray the galaxy to large enough x and spans enough (maxk) to reach all the k's where there is power.   Some user is making the choices of stepk and maxk in the case you're describing?  You will have to trust that he/she made a wise choice of k grid.

xinterp gained its original meaning by the assumption that the "real" continuous galaxy image was defined to be the input x-sampled image interpolated between samples by this function.  If you want to assume instead now that the "real" image is defined by some interpolation between your k samples, then you don't need an xinterp at all.  You asked whether you'd want an xinterp to interpolate between some x grid values that you produced by an FFT of your given k grid.  I would say the purist's view would be that if you want values at other k's you should produce another FFT from a resampled k grid.

The kinterp I would keep with the same choice as before.  It is up to the use to insure that he/she has constructed an image with a dk that is small enough that good interpolation in k space will occur.  Note that this is what the pad factor was for before - hence the dk on which the k grid is drawn should be substantially finer than the bare minimum if you want the k interpolation to be accurate at part per thousand.

As Mike says, kmax is easy: it's always just the k value at which the FT goes to zero (for your chosen definition of zero ;) ).  The stepk could most logically be the spacing of the k grid that was provided.  But recall that it will actually be used to determine the stepk at which convolutions of this object with others will be drawn.  So if you think your grid is actually finer than is needed for drawing, you could specify a stepk that is larger than the actual k grid pitch.

**Comment by rmjarvis** [comment]
> One minor detail, won't we need xinterp for (the potentially rarely used) xValue too?

Not everything has to implement xValue (or photon shooting).  For example, neither of these are implemented for Deconvolve objects.  In this case, (unlike for Deconvolve) I think it should be possible to implement the xtab stuff, but a reasonable start here would be to just implement fourier rendering and make another issue for direct rendering (xValue) and photon shooting.

> Although, now that I take a closer look at SBInterpolatedImage.kValue, which I suppose is analogous to SBInterpolatedKImage.xValue, I realize I don't quite get how this works. What's xKernelTransform? Why not just return _ktab->interpolate(k.x, k.y, *_kInterp);?

An InterpolatedImage is really a convolution of the image sampled at the pixel locations (a field of delta functions) convolved by the interpolant.  So in k-space, the value is the ktab (interpolated with the k-space interpolant) multiplied by the FT of the (real-space) interpolant.

I guess there would be a similar thing for the xValue of an SBInterpolatedKImage.

> The stepk could most logically be the spacing of the k grid that was provided. But recall that it will actually be used to determine the stepk at which convolutions of this object with others will be drawn. So if you think your grid is actually finer than is needed for drawing, you could specify a stepk that is larger than the actual k grid pitch.

This is a good point.  We'd want to allow the user to specify a stepk value that may be larger than kimage.scale.
