### ISSUE TITLE
Deprecate things we nominally got rid of in v1.1

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#643]
In version 1.1, we semi-deprecated a lot of old syntax in preference to our new API.  However, we didn't officially deprecate any (or at least much) of the old API.  I think it is time to do so.

For the next release, v1.3, I'd like to have all the old syntax give deprecation warnings (not errors yet) indicating what the preferred function to use is.

**Comment by rmandelb** [comment]
+1
