### ISSUE TITLE
it's 2015 - update license?

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#644]
Should the license be updated to say 2012-2015?

Mike, I think you had a script that updated the license in all files when we changed from GPL to BSD.  Can your script be used to update this too?

**Comment by rmjarvis** [comment]
Yes.  I can do this pretty easily.   

The script is in GalSim/devel/updatecr, btw.  A perl script no less!  :)

**Comment by rmandelb** [comment]
Thanks!  A perl script - so retro.

**Comment by rmjarvis** [comment]
Done on master

**Comment by rmandelb** [comment]
Thanks!
