### ISSUE TITLE
TMV error when using transform()

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#645]
Hi @rmjarvis - I am trying to use the GSObject.transform() method to do a parity flip, and ran into an error that I don't understand.  I want to remap the image coords from (x, y) to (x', y') where x'=-x and y'=y, so I wrote the code like this:

```
foo = galsim.OpticalPSF(0.1, obscuration=0.2, nstruts=6)
foo_flip = foo.transform(-1.,0.,0.,1.)
im_foo_flip = foo_flip.drawImage(scale=0.01)
```

When I do this, the output is:
```
last col element (2536) must be in 0 -- 768
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmandelb/software/lib/python2.7/site-packages/galsim/base.py", line 1249, in drawImage
    image.added_flux = prof.SBProfile.draw(imview.image, gain, wmult)
RuntimeError: TMV Error: Failed Assert statement base::hasSubMatrix(i1,i2,j1,j2,1,1)
```

Do you have any idea what could be going on here?  Is this a case of stupid input (did I misunderstand the args to transform?) or is this a bug somewhere?

**Comment by rmjarvis** [comment]
At the very least the error needs to be changed, since that's not very helpful.  But I don't see anything wrong with what you are doing, so this is probably a bug somewhere.

I was able to reproduce this on my machine, so I'll look into it and see if I can figure out what is going wrong.

**Comment by rmandelb** [comment]
Thanks!
