### ISSUE TITLE
HSM ShapeData

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#646]
The `hsm.ShapeData` returned by `hsm.EstimateShear()` seems to always have `corrected_g1,2 == -10.` and `corrected_shape_err == 0.`.  The `ShapeData` docs refer to a `meas_type` parameter that would switch between e1,2 and g1,2 but I don't see this parameter in the `EstimateShear` arg list or in `HSMParams`.  Is there no way to estimate g1,2 from the python layer?  Is it possible to enable the shape error calculation?

**Comment by rmandelb** [comment]
Hi David - if you're using re-Gaussianization, which is the default shear estimation method, then it returns PSF-corrected distortions and uncertainties (e-type shear, not g-type shear).  If you want a method that returns a g-type shear, your only option is KSB, which you can select using the ```shear_est='KSB'``` option to ```EstimateShearHSM```.

```meas_type``` is not a kwarg, it's actually an entry in the ShapeData object that tells you, for the chosen measurement type (re-Gaussianization, linear, KSB, etc.), what type of measurement was done (e- or g-type shape).

**Comment by rmandelb** [comment]
BTW if you want a shape uncertainty, you have to give EstimateShearHSM a variance for the noise in the image.  If you're not doing that, it'll always return 0, since it uses a formula for shape uncertainty that is linearly proportional to the square root of the sky variance.

**Comment by rmandelb** [comment]
Sorry, I should have said: if you read Hirata & Seljak (2003) you'll see that re-Gaussianization and two of the other methods are literally only defined for distortions, not shears.  So that's why you can't choose to switch between them.

**Comment by dkirkby** [comment]
Thanks for the clarifications!

**Comment by rmandelb** [comment]
No problem.  I just pushed a commit to the master branch that clarifies the docstrings, https://github.com/GalSim-developers/GalSim/commit/d31076af787c447dfeee662ec59c9f1575eb22b2,  but please let me know if you think it would be helpful to add anything else.  Otherwise I will close this issue.

**Comment by dkirkby** [comment]
Looks great!

**Comment by rmandelb** [comment]
Glad to hear it.

Closing #646.
