### ISSUE TITLE
Debian package for Galsim

### ISSUE THREAD

**Issue by olebole** [GalSim-developers/GalSim#647]
Dear Galsim developers and enthusuats,

I just stumbled across your software, and I think it is definitely worth to include it in Debian. Would you like to create a package that can be included in this distribution? Once it is in Debian, it will automatically appear on all derivative distributions like Ubuntu or Mint.

The packaging does not need to be done by GalSim developers, so if anyone interested can volunteer here. From the Debian side, we could offer you any help to solve problems that may appear during the packaging process. Please contact me either directly, or via the [Debian Astronomy mailing list](http://lists.debian.org/debian-astro).

Best regards

Ole

**Comment by rmjarvis** [comment]
Thanks for the interest.  We did have someone look into this a while back (Issue #300), but he ran into some difficulties and couldn't figure out how to get scons working with debuild.  I didn't have root access on a linux box at the time, so I wasn't able to look into it myself.  (Nor I think did the other principal GalSim developers.)  

I do have a linux box now that I can try this on to see if I can get it working.  If you have any tips to share specifically about using scons with debuild, please let me know.  Thanks!

**Comment by olebole** [comment]
It seems that scons is not supported by debhelper yet, so one seems to have to do things manually. This may server as a start:
```
#!/usr/bin/make -f

%:
        dh $@

override_dh_auto_build:
        scons

override_dh_auto_clean:
        scons -c
        rm -rf .sconsign.dblite .sconf_temp
```
The `rm -rf` in the last line is just my guess -- I didn't use scons myself so far.

**Comment by rmjarvis** [comment]
> Could you try this out?

It may be a bit before I get to this, but I will try it out.  Thanks so much for the advice.

**Comment by rmjarvis** [comment]
We decided not to go this route, but rather to try to make GalSim pip installable, so it will be easy to install on all flavors of linux, not just Debian.  This change is planned for v2.0.

**Comment by olebole** [comment]
To bring this up again now: There is already an unofficial Debian package made by @gijzelaerr for the [kernsuite](http://kernsuite.info/). Maybe someone here, or Gijs could polish the package ready for inclusion in Debian?

**Comment by rmjarvis** [comment]
The current version of GalSim is pip installable.  So, probably not so critical to use the debian packaging anymore?  Or if you do want to make a debian package, it might be easier to do now, since there are no longer boost or tmv dependencies.

**Comment by rmjarvis** [comment]
Well, if you don't want to use scons, then pybind11 (>=2.2) is required.  The new version though does allow you to keep using scons, in which case you can continue to use boost and/or tmv as you prefer.
