### ISSUE TITLE
adjust header file paths to ease building against GalSim library

### ISSUE THREAD

**Issue by TallJimbo** [GalSim-developers/GalSim#648]
I'd like to build against the GalSim compiled library, in order to create a measurement plugin in the LSST stack that delegates to the GalSim HSM module.

Unfortunately, the headers in GalSim are setup in such a way that it seems that multiple directories have to be added to the include path:
 - the `GalSim.h` include file is just in `include/`, and refers to all other headers as `galsim/${FILENAME}.h`.  That means we need `INCLUDE_PATH=${ROOT}/include/`
 - all the headers in the `include/galsim` directory refer to other files in that directory as just `${FILENAME}.h`.  That means we need `INCLUDE_PATH=${ROOT}/include/galsim`.
 - all the headers in directories below `include/galsim` (e.g. `include/galsim/hsm`) refer to all other headers relative to that directory, so we also need to put each of those directories in `INCLUDE_PATH`.

I think it'd make more sense to have all headers referred to the way they are in `GalSim.h` - so external libraries would only need to have `INCLUDE_PATH=${ROOT}/include`.

If there's agreement on that idea, I can have a PR ready by the end of the day (I'd like to move relatively quickly on this, as it's blocking some LSST pipeline work we'd like to do).

**Comment by rmjarvis** [comment]
I guess I don't understand the problem.  I just did a quick test, and the following code seems to compile with just the main GalSim directory in the include list (plus boost and tmv of course):

```
#include "GalSim.h"

int main() {
    galsim::ImageAlloc<double> im(3,4);
    galsim::ImageAlloc<int> mask(3,4);

    galsim::hsm::CppShapeData res = galsim::hsm::FindAdaptiveMomView(im, mask);

    return 0;
}
```

Of course it doesn't actually do anything, but it compiled fine for me with the command
```
g++ junk.cpp -IGalSim/include -I/sw/include/boost-1_53 -I/sw/include -o junk -LGalSim/lib -L/sw/lib -lgalsim -ltmv -lboost_python
```

Can you give a concrete use case of what you are trying to do that fails currently?

**Comment by TallJimbo** [comment]
Hmm, I guess I don't understand how the include search path works - that example does indeed work fine, and what I wanted to do (essentially the above, but using `galsim/hsm/PSFCorr.h` directly) does too.

I'd have expected it to fail when `PSFCorr.h` included e.g. "../CppShear.h", as I didn't think the compiler would find a header (`CppShear.h`) in a location that's relative to the location of another header that included it (`PSFCorr.h`) - I thought it could only be relative to to the actual source file that is actually being compiled (`junk.cpp`), or one of the explicitly-declared paths to be searched.

And this StackOverflow question still has me a little worried that we're relying non-standardized behavior:

http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename

But seems all the major compilers do support the way GalSim is doing things, and it's not clear that my proposed change would actually be any more standardized.

**Comment by rmjarvis** [comment]
Interesting link.  I didn't realize this usage is officially reliant on an implementation detail of common compilers.  The top answer by quest49 matches my experience.

I'll add that I've done a lot of cross-platform compatibility tests, more on TMV than GalSim, and this usage has _never_ caused a problem.  This includes g++, icpc, pgCC, clang++, cl (a Window C++ compiler), and Microsoft Visual C++.  So even if it's not the official *Standard C++* behavior, it seems to be the de facto standard that everyone uses for their implementations.

**Comment by TallJimbo** [comment]
That's good enough for me.  I'll just close the issue.
