### ISSUE TITLE
Kolmogorov docstring typo

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#656]
The Kolmogorov docstring gives the wavelength dependence of the Fried parameter r0 as lambda^(-6/5) but I believe this should be lamba^(+6/5) so that FWHM ~ lambda/r0 ~ lambda^(-1/5). The docstring example also uses the wrong exponent:

https://github.com/GalSim-developers/GalSim/blob/e2ef05fb978c0d1e41422b00b08e0ed0126c847a/galsim/base.py#L1670-L1681

**Comment by rmjarvis** [comment]
Yep.  You're right.  cf. http://en.wikipedia.org/wiki/Fried_parameter

**Comment by rmjarvis** [comment]
I think this is uncontroversial.  So I just fixed this on master.  Thanks for letting us know about this David.  cf. 483f978
