### ISSUE TITLE
Angular size units

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#657]
GalSim parameters like FWHM and half-light-radius that specify transverse sizes are generally treated as dimensionless, with the implicit assumption that the user is free to work in arcsec, microrad, microns, etc, although most (all?) examples use arcsecs.  However, the Airy, Kolmogorov and OpticalPSF profiles are not scale free so there is some potential confusion.  Specifically, the Airy.getFWHM and Kolmogorov.getFWHM return sizes in radians, which is probably not what the user is expecting if they are consistently using arcsecs for their galaxy profile sizes.  This confusion is probably not helped by the following docstring for the Image ctor scale parameter:

        scale       You can optionally specify a pixel scale to use.  This would normally have
                    units arcsec/pixel, but it doesn't have to be arcsec.  If you want to
                    use different units for the physical scale of your galsim objects, then
                    the same unit would be used here.

The simplest solution is probably to just clearly document that the Airy and Kolmogorov profiles work in radians, but that will still trip  someone up who makes reasonable assumptions and doesn't read the docs carefully.

A more radical solution would be to require explicit units on all size and scale parameters so that inconsistent units generate runtime errors, e.g. using astropy.units (which I didn't like at first, but is growing on me).

**Comment by rmjarvis** [comment]
For Airy and OpticalPSF, I believe #618, which has been merged into master, and will be part of the next release 1.3, may address the concern you are raising.  

These classes only return sizes in radians if the value of `lam_over_diam` is given in radians as well.  In other words, they also follow the general pattern that the size units are arbitrary and can be specified by the user.  The new functionality allows the user to separately specify `lam`, `diam`, and `scale_units` which will convert the angular `lam / diam` into whatever angle units you want.  `arcsec` is the default.

cf. https://github.com/GalSim-developers/GalSim/blob/master/galsim/base.py#L1455

We forgot to add the same functionality to Kolmogorov, where it would also make sense.  So if we add the same thing there, do you think that would satisfy the concerns raised on this issue?

**Comment by dkirkby** [comment]
The new functionality works numerically, although lumping the angular unit
conversion into the dimensionless quantity (lambda/D) seems non-intuitive.

**Comment by dkirkby** [comment]
> The point is that lambda / D is not dimensionless. It is an angle.

There's an important distinction between dimensions and units here:  (lambda/D), "1 arcsec", and "0.001 deg" are all dimensionless, but have [different units of dimension 1](http://physics.nist.gov/Pubs/SP811/sec07.html#7.10).  It is certainly possible to allow dimensionless quantities to be provided in different units. For example, you could allow Sersic indices to be input in % or ppm. However, my point is that this is not intuitive (since dimensionless quantities are unique in having a single 'natural' unit) and likely to be error prone unless the API includes some additional book keeping (e.g., require that lambda/D be multiplied by an AngleUnit, like other angles in GalSim).
