### ISSUE TITLE
make GalSim citable via DOI

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#659]
@jmeyers314 pointed me towards these instructions for making a GitHub repo citable:
https://guides.github.com/activities/citable-code/

I already looked into this for his chroma repository, and I think it would be very easy to do for GalSim as well.  Any objections / concerns / questions?  If not, I'll go ahead.

**Comment by rmjarvis** [comment]
Looks straightforward.  I guess there is a new DOI for each release.  Looking at a couple examples, it looks like the equivalent of a CHANGELOG is given on zenodo as a description page for each release. Do you know if this can be made automatic?  Or will we need to include copying over the CHANGELOG there each time as part of the release instructions?

**Comment by rmandelb** [comment]
Yes, there's a new DOI for each release, though we can exclude releases that we don't want to have DOIs (e.g., pre-v1.0).

For chroma, here's what the release page looks like with no direct intervention:
https://zenodo.org/record/16804
i.e., it pulled this directly from GitHub.  (It can then be edited to include more info.)  So it looks to me like it takes the top-level repository description, which for GalSim would be "The modular galaxy image simulation toolkit", then makes a preview of the files in the release, and that's it.  If we want CHANGELOG then I would guess we have to put it there, unless it searches for a file with that name automatically and said nothing about it for chroma since it didn't find one.

Want me to give it a whirl and we can see what it looks like when the page is auto-generated?  It's easy to turn off if we hate it.

**Comment by rmjarvis** [comment]
I don't see any down side.  :)

**Comment by rmandelb** [comment]
It turns out that after creating the web hook that tells zenodo we want it to archive releases for GalSim, it doesn't do anything retroactive - it has to be triggered by us making a new release.  (At least, I can't find a way to force it to take the old releases.)  So perhaps we should just leave this as-is and there will be a DOI for v1.3 and onwards.

**Comment by rmjarvis** [comment]
@rmandelb It seems like there is nothing left to do on this issue, right?  Close?

**Comment by rmandelb** [comment]
Closing #659.
