### ISSUE TITLE
latest version of GalSim broke WFIRST module getPSF()

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#663]
The GalSim WFIRST module getPSF routine uses setupInterpolation(), which was removed in the latest version of GalSim.  Need to fix this so that the routine is usable again.  Also, should have a unit test that would have caught this.

I'll take care of it within a few days.

**Comment by rmjarvis** [comment]
Sorry. I thought I grepped for all instances of setupInterpolation when I was making that switch.  I must have missed going one directory further down in the directory structure.

**Comment by rmandelb** [comment]
No worries, it's easily fixed.  :)  And now that I play around with it, I realize that there were unit tests in ```test_wfirst.py``` that would have caught this if we ran the script directly (but not as part of ```scons tests```).  I just moved the fastest of those out of the ```if``` statement so it gets run with ```scons tests```.

However - the problem I'm having is that this test is now failing, even though it's one that should pass at very high precision.  The test is as follows:
- We had previously made an achromatic WFIRST PSF at a particular wavelength (```use_lam=900 nm```) and drew it into an image.
- We then make an interpolated WFIRST PSF, for which one of the wavelengths used for interpolation is 900 nm.
- We evaluate the interpolated WFIRST PSF at 900 nm and draw it into an image.

Previously the images from the original achromatic PSF and the interpolated one agreed to 8 decimal places, which I think should trivially be the case.  Now, the test fails unless I restrict it to 4 decimal places.  You can see this is if you go to branch #663 and run ```test_wfirst.py```.  This change in precision suggests to me that something important might have actually changed.  Can you think offhand of anything from your own code rearrangements in chromatic.py that might cause this?  If not, I will start digging into this further.

**Comment by rmandelb** [comment]
@rmjarvis - do you have any comments or suggestions on what I was finding with the unit tests? (https://github.com/GalSim-developers/GalSim/issues/663#issuecomment-98729298)

**Comment by jmeyers314** [comment]
Hey @rmandelb , I thought this sounded weird too so I took a look.  I think what happened is that your original interpolation code used the parent ChromaticObject.evaluateAtWavelength() method which doesn't actually reference any of the stored monochromatic images, but just creates the appropriate GSObject on-the-fly.  In @rmjarvis 's refactorization, which implements interpolation in the InterpolatedChromaticObject subclass, the InterpolatedChromaticObject.evaluateAtWavelength() method returns an InterpolatedImage formed from the stored monochromatic images.  So in the new code there's some interpolation going on, with potentially mismatched stepk, maxk, and so on.  I'd guess that 4 decimal places is reasonable in this case.

**Comment by rmandelb** [comment]
I am using one of the endpoints in wavelength, so I was thinking of this as an interpolation-free operation.  I also confirmed that for the images I'm comparing, the GSObjects have the same maxK and nearly the same stepK (within a %).

**Comment by jmeyers314** [comment]
Right, I didn't mean interpolation in wavelength.  Just that formerly, you got the same GSObject back from evaluateAtWavelength (an OpticalPSF object) as when drawing achromatically at 900nm, but now you get an InterpolatedImage out of evaluateAtWavelength that was constructed by wrapping an array drawn at a different image scale/size than what you're comparing to in the test.  (You're probably right that the stepk/maxk don't matter). Roughly, I think this is the new comparison:
```
a = OpticalPSF(...)
a_img = a.drawImage(nx, ny, scale)
b = InterpolatedImage(a.drawImage(some other nx, ny, scale))
b_img = b.drawImage(nx, ny, scale)
assert(a_img == b_img)
```

**Comment by rmandelb** [comment]
Okay, fair enough.  Now that it's an InterpolatedChromaticObject and is going from an object to an image to an InterpolatedImage to an image again, it's non-trivial.  I weakened the unit test.

**Comment by rmandelb** [comment]
Closing #663.
