### ISSUE TITLE
[Mac 10.9.5 & LSST v10] Galsim

### ISSUE THREAD

**Issue by JPGlaser** [GalSim-developers/GalSim#664]
Hello Guys,

So I'm trying to install LSST_Sims package locally on my iMac, however it seems to be getting hug up on the installation for GalSim 1.2.lsst2+4. I receive the following error:
````
***** error: from /Users/jglaser/lsst/EupsBuildDir/DarwinX86/GalSim-1.2.lsst2+4/build.log:
         programs or modules that link to the BLAS library (such as GalSim).
         If you do have problems, the solution is to recompile TMV with
         the SCons option "WITH_BLAS=false".
Checking for correct TMV linkage... (this may take a little while)
Checking for correct TMV linkage... yes
Checking if we can build against Python... 
Unable to build a python loadable module using the python executable:
/usr/bin/env python,
the library name libpython2.7.a,
and the libdir /Users/harrison/anaconda/lib/python2.7/config.
If these are not the correct library names, you can tell scons the
correct names to use with the flags EXTRA_LIB_PATH and/or EXTRA_LIBS.

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at 
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ

+ exit -4
eups distrib: Failed to build GalSim-1.2.lsst2+4.eupspkg: Command:
	source /Users/jglaser/lsst/eups/bin/setups.sh; export EUPS_PATH=/Users/jglaser/lsst; (/Users/jglaser/lsst/EupsBuildDir/DarwinX86/GalSim-1.2.lsst2+4/build.sh) >> /Users/jglaser/lsst/EupsBuildDir/DarwinX86/GalSim-1.2.lsst2+4/build.log 2>&1 4>/Users/jglaser/lsst/EupsBuildDir/DarwinX86/GalSim-1.2.lsst2+4/build.msg 
exited with code 252
````
The issue isn't stemming from TMV (0.72.lsst1-1-gf77e209+1) as it was installed just fine or the Xcode install, as that is working properly. Any idea on how to get past this issue?

~ Joe

**Comment by rmandelb** [comment]
Hi - have you seen this wiki page?

https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ#why-is-scons-unable-to-build-a-python-loadable-module-using-the-python-executable (scroll down to the bit that refers to anaconda), and
https://github.com/GalSim-developers/GalSim/wiki/Building-GalSim-with-the-LSST-stack

I suspect you might encountering the issues described in the first link, with a solution suggested in the second link.

**Comment by JPGlaser** [comment]
Thanks for the suggestion @rmandelb. This is likely the problem I am facing. Where can I find the newinstall_galsim.sh file?

~ Joe

**Comment by rmandelb** [comment]
I thought that script was available with the winter 2014 DM stack, but I haven’t tried to do this process myself, so I can’t say for sure.  If you don't find it there, then I could ask Chris Walter for you (since he's the one who wrote those instructions).  Alternatively, there is another procedure on that wiki page which is hacky but supposedly works.

**Comment by jmeyers314** [comment]
Hi Joe,
I last grab the script via this command:

curl -O "https://sw.lsstcorp.org/eupspkg/newinstall_galsim.sh"

**Comment by JPGlaser** [comment]
Thanks @jmeyers314, that worked just fine and GalSim is installed and operating nicely. Now, I am just having an error with the lsst_sims install of healpy 1.8.1+6, which will hopefully be resolved over here: https://github.com/lsst/lsst_sims/issues/2

Thanks for all your help guys!

~ Joe

**Comment by rmandelb** [comment]
I'm glad that worked!

**Comment by rmandelb** [comment]
Closing #664.
