### ISSUE TITLE
Cache chromatic drawImage intermediate results

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#670]
This issue is to implement caches of intermediate products in the drawImage() and drawKImage() methods of `ChromaticObject` and subclasses where possible.

There are several instances where one may wish to call the `drawImage()` (or `drawKImage()`) method of a `ChromaticObject` with only minor changes between invocations, and in particular with no changes to `SED`s, `Bandpass`es, and chromatic PSFs.  Examples include forward-model fitting/sampling and ring tests.  In these cases, it would be advantageous to avoid recomputing certain intermediate results of `ChromaticObject.drawImage()` and `.drawKImage()`, such as the product of an SED and a Bandpass in the case of separable profiles, or the effective (wavelength-integrated) profile in the case of convolution of separable and inseparable profiles.

Previously, creating such a cache was problematic since it was difficult to recognize when particular GalSim objects had been seen before.  Now that (most) GalSim objects are immutable, though, and carry `__eq__` and `__hash__` methods, caching is feasible.  

My current plan is to steal the code for the cache from here: http://code.activestate.com/recipes/577970-simplified-lru-cache/ , but I'm happy to hear alternatives.

**Comment by jmeyers314** [comment]
This still needs to be cleaned up a bit, but I wanted to report that some of the ring test results in chroma are sped up by a factor of ~18 from 107s to 6s with this update!

@mdschneider, @wadawson I think this may speed up some of the chromatic drawings you've been playing with too.

**Comment by rmandelb** [comment]
Nice!
