### ISSUE TITLE
segfault when importing GalSim

### ISSUE THREAD

**Issue by mcvespe** [GalSim-developers/GalSim#674]
Hi, I'm a statistics grad student working with Rachel at CMU, trying to use galsim as one component of an ABC analysis pipeline. My issue: galsim seems to build fine, but when I try to import it I get "Segmentation fault: 11". 

I'm on a Mac running Yosemite (10.10.1). I've already tried updating the Command Line Tools for Xcode and rebuilding everything, and it still didn't work. I'm not using a package manager. Any thoughts on how to proceed?

**Comment by rmjarvis** [comment]
This usually means that the python library you are using when you compile is not the same one as either (a) the python you are running when you do `import galsim` or (b) the python library that was used when you compiled boost.

My guess would be the latter.  Boost python is notoriously tricky to get compiled correctly.  See these FAQ entries, which discuss slightly different problems, but they may be relevant for diagnosing this one: [1](https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ#why-is-scons-unable-to-run-a-program-built-with-boostpython), [2](https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ#in-mac-osx-what-can-i-do-if-im-having-trouble-getting-boostpython-to-work-with-enthought-canopy-python).

Also, make sure that `which python` returns the same python executable that was found by the GalSim build process.  (Look for the line that starts "Using python =" when you run `scons`.)

**Comment by mcvespe** [comment]
Mike, I appreciate your response. I think it ended up being an issue with multiple versions of Python floating around on my computer. Examining the "Using python = " line, it pointed to "usr/bin/env", which as I understand it means the first version of Python it can find via your $PATH variable. It looks like my $PATH contained a link to a different version of Python than I wanted to be using (not sure how it got there).

The fix was that I edited the .bash_profile script (in my home directory) to remove that link and then rebuilt Boost and GalSim, and now I am able to import GalSim without getting a Segmentation fault. Thanks for your help!

**Comment by rmjarvis** [comment]
Good.  Thanks for the update.  Glad it works now.
