### ISSUE TITLE
Cross-post from homebrew/homebrew-science:  Building gal-sim on 10.10.4 and it can't find FFTW3 (#2577)

### ISSUE THREAD

**Issue by josePhoenix** [GalSim-developers/GalSim#677]
See https://github.com/Homebrew/homebrew-science/issues/2577 for details  @rmandelb

**Comment by rmandelb** [comment]
I pointed Dustin your way (he's the one who set up the homebrew installation for us) and it looks like it's all under control now.  Is that correct?  If so, we can close this issue.

**Comment by josePhoenix** [comment]
Yep, seems to be all set now. Thanks!
