### ISSUE TITLE
cannot allocate memory for thread-local data: ABORT

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#679]
linux, galsim master, boost 1.55 or 1.58

This appears to be an intreraction between galsim/boost-python functions that generate images and scipy. The error occurs when calling scipy leastsq.

I can run these codes separately fine: I can generate images with galsim and I can run leastsq.  But if I run a leastsq fit on images generated by galsim in the same python session I get the above error

This only fails on one system I am using, the others work fine.

**Comment by rmjarvis** [comment]
thread-local sounds like OpenMP stuff to me.  Which in turn might mean BLAS-related.  Is the TMV installation you are using for GalSim using BLAS?  Maybe it's incompatible with whatever BLAS scipy uses for leastsq.

**Comment by esheldon** [comment]
Interesting idea, I'll check it out.

Note neither tmv were compiled with openmp support.

**Comment by rmjarvis** [comment]
And GalSim doesn't use OpenMP either.  But many BLAS libraries do.  Or at least pthreads, which might also involve thread-local objects.  (I only know that term in relation to OpenMP, but it might be a more general threads thing.)

**Comment by esheldon** [comment]
there is a scons option for openmp, should that be there if it is not used?

**Comment by rmjarvis** [comment]
It was there in case we wanted to use it, but none of the code in GalSim uses any OpenMP pragmas, so it doesn't actually make a difference if it's turned on or not.  So yeah, it would probably make sense to remove it as a SCons option.

**Comment by rmjarvis** [comment]
@esheldon Did you ever track down the source of this error?  Is there any action item for us to do in the GalSim repo to help address this?  (I did remove the unused and misleading WITH_OPENMP option in our SConstruct file.)

**Comment by esheldon** [comment]
I did not track it down.

**Comment by rmjarvis** [comment]
Was this just on `import galsim` or is this something that happens for a particular script you're running?  If the latter, maybe we can try to figure out what the minimum use case is that causes the error.

Also, is this on a machine where I can log into?  Something on the BNL cluster maybe?  If not, maybe next time we get together, you can log in for me and I'll see if I can figure something out.

**Comment by rmjarvis** [comment]
Closing due to lack of actionable information to work with.  Please reopen if this recurs, especially if you can provide more information that might help us track down the problem.
