### ISSUE TITLE
Make it easier to produce great3-like simulations

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#691]
One of the takeaways from the recent "Great4" planning meeting at Penn last week was that people would like it to be easier to produce simulations along the lines of what was done for Great3, and then to improve on that in various ways for sims that test blending, selection, etc.  

There are four principal improvements to the config structure that I think would go a long way towards this goal:
- [x] Incorporate some of the recent features to GalSim, most notably the `COSMOSCatalog` class, to simplify the config files that were used to generate the Great3 sims.  In particular, I think all the parameter calculations that we wrote to catalogs and then read in as `type : Catalog` entries can be done directly in the yaml file.  This would make it significantly easier for people to see what is actually being done for these and modify the scripts appropriately for their use case.  I propose cleaning these up, adding comments, and then putting them in the examples directory (or better, in a sub-directory examples/great3) as cgc.yaml, csc.yaml, etc. so people can more easily find useful examples for making these types of sims.
- [x] Make truth catalogs.  This is already an open issue #301.  Part of the reason for our decision to make the catalogs and then read the values from there was that the catalogs would serve as truth information.  If we can make the truth catalogs directly, then we wouldn't need this two-step process.  I have an idea about how to do that, but I'll comment further on that issue page.
- [x] Add a command-line option to split the work into multiple jobs.  We put some hacks into the config generation scripts to make several config files per branch to make it easier to run on multiple machines.  If you're starting with vsc.yaml, say, it's not super trivial to make the necessary changes to split it into multiple runs.  There are a number of values that would need to be adjusted correctly.  However, internal to the config processing, it wouldn't be that hard actually.  It can just skip the appropriate output files and increment the numbers appropriately.  So I propose adding an option along the lines of `galsim vsc.yaml -n 10 -j 1` to split the work into 10 jobs, where this would only do the work of job number 1.  This would then be easy to run on multiple machines.
- [x] Finally, I think it would be useful to be able to define templates for various parts of the config file, so it would be easier to do some standard kinds of galaxies or psfs or image types, etc.  I'm not completely settled on what the best API for this would be, but here is a possibility.  The file great3_constant_space_psf.yaml could have the `psf` part of the config for the constant-PSF space branches.  Then rather than duplicate that in csc.yaml, csv.yaml, rsc.yaml, rsv.yaml, msc.yaml, and msv.yaml, all 6 of these files could just do:
```
psf :
    template : great3_constant_space_psf
```
which would pull the `config['psf']` information from that file.  If a template defined several top-level items, then they could either be incorporated separately (maybe several but not all of the items defined in the template file)
```
gal:
    template : cgc
psf:
    template : cgc
image:
    template : cgc
output:
    type : NumberedFile
    ...  # Maybe a different output structure here than what is in cgc.yaml
```
or all at once, which would get everything:
```
template : cgc
```
And then (especially in the latter example) it would make sense to allow for changes to the template info.  So the template would be a starting point, but any other items in the dict would supersede the values in the template:
```
psf : 
    template : cgc
    items.1.defocus : { type : RandomGaussian, sigma : 0.13 }  # Not so out of focus!
```
or
```
template : cgc
psf :
    items.0.fwhm : { type : Random, min : 0.75, max : 1.05 }  # DES has larger seeing than cgc.
    items.1 :
        type : OpticalPSF
        ... # Build a DES-like optical PSF
image : 
    pixel_scale : 0.26   # DES pixel scale
output.file_name.format : deslike_image-%03d-%1d.fits
```

I don't think the implementation of any of these changes will be terribly hard.  And IMO, the result would be a lot more user-friendly than trying to parse the great3-public scripts, which are a bit obtuse, to be honest.

**Comment by rmjarvis** [comment]
[Here](https://github.com/GalSim-developers/GalSim/blob/%23691/examples/great3/cgc.yaml) is my first pass at cgc.yaml.  The main thing I discovered that isn't implemented currently that we need for this is the ability to keep the same PSF and shear for a bunch of objects in a row before generating a new one.  I think a convenient API for this is to allow any gsobject or value item to take a `repeat: N` parameter, which means repeat each result N times before moving on to the next one.  It shows up here in both the psf and the galaxy.shear.  

@rmandelb @msimet Rachel and Melanie, please check that this seems to accurately describe what the cgc branch was supposed to do.  I'm not trying for exact duplication -- the way the randoms are done will necessarily make the precise output different.  Just that this would also create a valid Great3 cgc branch simulation.  It would be very helpful to get a sanity check on this before charging ahead to implement the necessary bits in the config module.

@TallJimbo Jim, please see if you think agree that this is moving in the right direction to make it easier to make the kinds of simulations we would need for Great4 as discussed at Penn last week.  If you have concerns about this direction, we should probably discuss now before I get too far along.

**Comment by rmandelb** [comment]
Would it be helpful if I were to send you the actual cgc.yaml, rgc.yaml, etc. from GREAT3?  There will be differences since you're not going for exact duplication, but maybe it still helps?

**Comment by rmjarvis** [comment]
Sure.  I made my own from the test suite, but those are only for one output file, so some of the details of the subfields got lost.  Most of the work though is figuring out where the entries in the input catalog get calculated and reproducing those calculations in config.

**Comment by rmandelb** [comment]
Yes, of course.  But I figure it can't hurt to have something to copy for parts of it.  I just sent them.

**Comment by TallJimbo** [comment]
This isn't quite what I originally had in mind for GREAT4 - I was envisioning a multi-level config system, in which a single simpler config file is used to generate these more complex ones.  But I think the template approach you suggested here would provide essentially the same functionality in a different way, and it might be easier to build - the "simple master config" files would just delegate to a bunch of standardized template config files, with the top-level changes corresponding to selecting between those templates.

So I think this is all perfectly compatible with my vision for GREAT4, but we haven't yet gotten to what I think are the messy parts.  That goes beyond the scope of this issue, but in order to support spatially-variable PSFs and custom WCSs as defined by instrument-specific modules I think we'll need to find some way to have the config system load arbitrary Python code and delegate to some specific black-box interfaces.  In other words, it doesn't scale to have @rmjarvis (or someone else familiar with the config code) write hand-rolled config interfaces for every possible PSF or WCS as those get more instrument-specific (and we add a PSF class of some sort with spatial variation).

**Comment by rmjarvis** [comment]
> I think we'll need to find some way to have the config system load arbitrary Python code and delegate to some specific black-box interfaces. 

I've been thinking about this.  I think what we need is to make it easy for the user to define their own types in a straightforward way.  Then the config layer could just load in their custom code at run time and use that.  I'm still thinking about the best API for this, but if we can add that kind of hook, then the config layer would be completely customizable, but still hopefully user-friendly.

BTW, it's already easy to do this for PSFs and WCSs that are shipped as galsim modules (e.g. as galsim.lsst.wcs).  It's just not currently easy to do this from outside of GalSim, and I definitely want to enable that as well.
