### ISSUE TITLE
let InterpolatedImage read in an image from a multi-extension fits file?

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#692]
This issue was inspired by a conversation with @TallJimbo .

Currently, InterpolatedImage can take an image or a string representing the filename for a FITS file with the image.  I think it would be useful if InterpolatedImage (both the python and config interface) could be given a multi-extension FITS file with some way to specify which of the images it should take.  At first I thought this must already be possible because of ```RealGalaxy``` but then I realized that functionality is all hidden inside the ```RealGalaxyCatalog``` class (```getGal``` method) and not accessible in other contexts.

At the python level, I think we want to avoid having yet another kwarg.  One option would be to make three options (instead of two) for ```image```: an image, a string for the filename, or a tuple/list that will be interpreted as ```(filename, extension)```.

For config, we could perhaps include it in the string that is used to specify the filename, e.g., check if the filename has anything after the ".fits", and whatever it is tells the extension?  So "myfile.fits.37" would mean to use the 37th extension of "myfile.fits"?  I don't love this - other ideas?  I feel like I'm missing some obvious option.

I think this is something I could code up fairly quickly myself, but would like some feedback on the above suggestions first.

**Comment by rmjarvis** [comment]
This is a duplicate of #660.  I think in the contexts where we have enabled this, we use the parameter `hdu` to specify which hdu.  So I'd suggest the syntax `galsim.InterpolatedImage('myfile.fits', hdu=37)`.

**Comment by rmandelb** [comment]
Oops, I missed that old issue.  I'll close this and assign that one to me, hopefully to be done within ~a week (unless you need it for the work you're doing now, in which case by all means go ahead).

**Comment by rmjarvis** [comment]
> I'll close this and assign that one to me, hopefully to be done within ~a week 

Sounds good.  I agree that it should be an easy fix.  Really just an oversight that we didn't include that option originally.
