### ISSUE TITLE
Unsigned int Images

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#715]
On branch #654, I fixed a number of problems that we had related to reading in unsigned int Images.  We don't have any unsigned int instantiations for the Image class in C++, so it had been recognizing the incompatibility and converting to float64 (our default catchall if we can't handle the dtype of a numpy array).  

However, for badpix masks, this isn't the right thing to do, so now the code uses the corresponding int type instead.  i.e. uint16 -> int16 and uint32 -> int32.  This works ok, but it would be better if we actually supported uint Images correctly.

**Comment by rmandelb** [comment]
A student who recently started working with me, Brent ( @zunyibrt ), would like to do this issue as his starter project.

**Comment by rmandelb** [comment]
@rmjarvis - Brent has added this functionality, and we were hoping for some advice from you about one remaining problem.

The unit tests (old + new ones that he added) pass on our Linux cluster here.  But there is a single test failure on my Mac that looks like this:
```
FAIL: Test that all four FITS reference images are correctly read in by both PyFITS and our Image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rmandelb/git/GalSim/tests/galsim_test_helpers.py", line 412, in f2
    result = f(*args, **kwargs)
  File "/Users/rmandelb/git/GalSim/tests/test_image.py", line 652, in test_Image_CubeFITS_IO
    assert test_array.dtype.type == types[i], "%s != %s" % (test_array.dtype.type, types[i])
AssertionError: <type 'numpy.float32'> != <type 'numpy.uint16'>
```

We were wondering if either (a) this is something you've seen before, and you can suggest a specific place in the code where Brent should be able to fix this, or (b) you can suggest an effective way that  we can go about investigating the cause of this problem, given that it's showing up on a Mac (he doesn't have a Mac himself) and everything is fine on the Linux system where he's working?  

Thanks!

**Comment by rmjarvis** [comment]
It's not Mac vs Linux.  It's the astropy version.  I didn't have this error on my Mac with astropy 1.1.1, but when I regressed back to astropy 1.0, it showed up.

It's also not just true for the Cube file.  It's true for all of the pyfits reads of unsigned int images.  It's just that apparently, that one is the only one where we check the type of the incoming pyfits data array.
```
>>> f = pyfits.open('testUS.fits')
>>> f[0].data
array([[ 11.,  21.,  31.,  41.,  51.,  61.,  71.],
       [ 12.,  22.,  32.,  42.,  52.,  62.,  72.],
       [ 13.,  23.,  33.,  43.,  53.,  63.,  73.],
       [ 14.,  24.,  34.,  44.,  54.,  64.,  74.],
       [ 15.,  25.,  35.,  45.,  55.,  65.,  75.]], dtype=float32)
```
So that one is wrong too.

I'm not sure what the right solution is.  Require astropy >= 1.1.0 (but don't get 1.1.2 -- it's broken)?  Or maybe only run this test for astropy >= 1.1.0?

I think GalSim is probably working correctly now with whatever image astropy gives us; just the old version doesn't know how to read unsigned int data in fits files, so it reverts to float32.

**Comment by rmandelb** [comment]
Ah ha.  Tricky; thanks for the tip.  I had astropy 1.0.7 on my laptop, but when I went to 1.2.1 this error went away.  In my opinion, if GalSim is actually working correctly even with an older astropy, but it's just reverting to another type, then we should simply require astropy >=1.1.0 in order to run the test.  Otherwise we skip this test.  @zunyibrt , can you give that a try?

And re: 1.1.2, unfortunately that's the system default on our linux cluster, so I've gotten used to ignoring the resulting warnings while running the unit tests on there.  Once I was in "install astropy" mode I went ahead and installed 1.2.1 in my own directory on the cluster so that I don't have those warnings any more... nice.

**Comment by rmjarvis** [comment]
Merged.  #817
