### ISSUE TITLE
Dev Workflow Suggestion: Online-Checklist for Pull Requests

### ISSUE THREAD

**Issue by daniel-kun** [GalSim-developers/GalSim#718]
Hello there,
sorry for the intrusion. GalSim seems to be of very high quality code, and I noticed that you have a nice [checklist on the wiki](https://github.com/GalSim-developers/GalSim/wiki/Checklist-for-making-a-pull-request) to ensure it keeps that way.

Recently I wrote an online-checklist tool exactly for this kind of purpose (code review and pull requests). I thought maybe you liked it and want to use it in your guideline for pull requests?

The nice thing is that it creates a neat "badge" that you can easily paste into github issues and gives the reviewer a warm feeling of comfort. The badges look like this (click it to see the filled-out checklist results):
[![11 Passed, 0 Not Passed, 1 Not Checked](http://www.guess-what.io/badge/esj8y0woB0u8xZ3HYavU7Q.png)](http://www.guess-what.io/c/result/esj8y0woB0u8xZ3HYavU7Q)
Note that I already copied your guidelines into a checklist template for demo purposes here :-)

The tool is completely open source ([github repo](https://github.com/daniel-kun/guess-what)) and free to use.

Greetings,
Daniel

P.S.: Maybe, at a later stage, I might write a GitHub bot that will reply to pull requests without a filled out checklist in them to remind the author to follow the guidelines and paste the checklist results.

**Comment by rmjarvis** [comment]
Thanks for the interest Daniel.  However, I don't really think we need this.  Cheers.
