### ISSUE TITLE
adjust GalSim eups table to make setup command `setup galsim` instead of `setup GalSim`

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#724]
This issue is to change the name of `ups/GalSim.table` to `ups/galsim.table`, so that the eups name of the package is all lowercase rather than camelCase, which is more in line with other LSST eups package names.  This also helps avoid an eups bug on OS X related to that os's filesystem's lack of case sensitivity.

If no one objects in the next few days, I'll do this on master, and then also create and tag some revision releases 1.2.1 and 1.3.1.

**Comment by danielsf** [comment]
Speaking for LSST (because I am totally empowered to do that...) I have no objections.

**Comment by cwwalter** [comment]
So, I'm having problems making this work so I can actually run GalSim..  The LD_LIBRARY_PATH is being set but not the DYLD_LIBRARY_PATH.  

This is what is in the repo now:

```
envPrepend(PYTHONPATH, ${PRODUCT_DIR})
envPrepend(LD_LIBRARY_PATH, ${PRODUCT_DIR}/lib)
envPrepend(PATH, ${PRODUCT_DIR}/bin)
```

And this is what is in Scott's stack version from (https://github.com/lsst/galsim/blob/master/ups/GalSim.table):

```
envPrepend(PYTHONPATH, ${PRODUCT_DIR})
envPrepend(LD_LIBRARY_PATH, ${PRODUCT_DIR}/lib)
envPrepend(DYLD_LIBRARY_PATH, ${PRODUCT_DIR}/lib)
envPrepend(PYTHONPATH, ${PRODUCT_DIR}/lib/python)
envPrepend(PATH, ${PRODUCT_DIR}/bin)
``

The effect of not having the DYLD is that at run time it can't load the module.  I think we might have fixed this by hand at SLAC.  I'm not sure why it is working for Josh..

**Comment by cwwalter** [comment]
One note is that after I fixed this by hand after some testing I found a DYLD_LIBRARY_PATH line in gs_scons.conf.

So Josh may want to see if he has something actually in there instead.

**Comment by jmeyers314** [comment]
>So Josh may want to see if he has something actually in there instead.

My gs_scons.conf is still empty, as is my $DYDL_LIBRARY_PATH before running "setup GalSim".

**Comment by cwwalter** [comment]
what does it look like after you do the setup of your own version?

**Comment by jmeyers314** [comment]
>what does it look like after you do the setup of your own version?

```
$ echo $DYLD_LIBRARY_PATH
/Users/josh/miniconda2/opt/lsst/tmv/lib:/Users/josh/miniconda2/opt/lsst/fftw/lib:/Users/josh/miniconda2/opt/lsst/boost/lib```

**Comment by cwwalter** [comment]
Right.. your galsim library location isn't in there.  It could be loading them from a "standard" place .

Is there a galsim lib around  in /usr/local/lib/ ?

**Comment by jmeyers314** [comment]
Looks like you're right.

```
[josh@Trogdor ~]$ lsa /usr/local/lib/libgalsim.*
-rwxrwxr-x 1 josh admin 3.1M Oct 26 10:59 /usr/local/lib/libgalsim.1.3.dylib
-rwxrwxr-x 1 josh admin 2.8M Mar 12 15:11 /usr/local/lib/libgalsim.1.4.dylib
lrwxrwxr-x 1 josh admin   34 Mar 12 15:12 /usr/local/lib/libgalsim.dylib -> /usr/local/lib/libgalsim.1.4.dylib
```

**Comment by cwwalter** [comment]
This should show you where it is really loading it from:

python -v -c "import galsim" | & grep _galsim.so

For me I get:

```
dlopen("/Users/walter/LSST/GalSim/galsim/_galsim.so", 2);
import galsim._galsim # dynamically loaded from /Users/walter/LSST/GalSim/galsim/_galsim.so
```

**Comment by cwwalter** [comment]
Oops checked the wrong thing...

Not sure yet how to check for the actual .dylib.

**Comment by jmeyers314** [comment]
I think this does what you want:

```
[josh@Trogdor ~/src/GalSim (#723-better-repr|✚3…)]$ otool -L galsim/_galsim.so
galsim/_galsim.so:
	@rpath/../opt/lsst/boost/lib/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/josh/miniconda2/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	@rpath/../opt/lsst/tmv/lib/libtmv_symband.0.dylib (compatibility version 0.70.0, current version 0.72.0)
	@rpath/../opt/lsst/fftw/lib/libfftw3.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	@rpath/../opt/lsst/tmv/lib/libtmv.0.dylib (compatibility version 0.70.0, current version 0.72.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libgalsim.1.4.dylib (compatibility version 1.4.0, current version 1.4.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
[josh@Trogdor ~/src/GalSim (#723-better-repr|✚3…)]$ 
```

**Comment by cwwalter** [comment]
That's what was trying to figure out.  Somehow, that command isn't doing the right thing.  I have the same output as you  but I don't have a file in /usr/local. It only works for me if I have DYLD_LIBRARY_PATH pointing to the correct place in my local directory.  But that isn't reflected in this command output for some reason.

**Comment by cwwalter** [comment]
In any case, the quick check is to move the /usr/local files.  I predict galsim won't run.

**Comment by jmeyers314** [comment]
Yep.  I tried that and yes, it doesn't run.

**Comment by cwwalter** [comment]
OK, so the solution is to modify the table file with the two extra lines like above.

**Comment by jmeyers314** [comment]
I updated the table file (name change + 2 additional lines) on master, releases/1.2, and releases/1.3.  I also bumped the release branch version numbers to 1.2.1 and 1.3.1 and tagged and pushed these as such.  @rmjarvis , can you double check I didn't mess anything up?  Anything else left to do?

**Comment by rmjarvis** [comment]
All looks fine to me Josh.  I think this can be closed.  Thanks.  

@cwwalter, @danielsf If either of you notice any further issues with the ups table, please feel free to reopen this.
