### ISSUE TITLE
Containerizing GalSim with Docker: temp. solutions and problems

### ISSUE THREAD

**Issue by karenyyng** [GalSim-developers/GalSim#728]
I tried to write a [DockerFile](https://gist.github.com/karenyyng/afe01af8ac60bbeab5d1) to build Galsim for Ubuntu 14.04 LTS. For some obscure reasons, the Scon Galsim build failed due to some C++ error not documented in the Installation FAQ page.

I found this [Docker build](https://hub.docker.com/r/esuchyta/valarauko/)  for another DES project, 
which also includes GalSim as one of the dependencies. 
It can get `GalSim` up and running after installing and starting docker daemon with the command:
```
docker run -t -i esuchyta/valarauko:y1a1
```
I hope this helps 
* anyone who wants to use `GalSim` quickly without potentially breaking their own software environment
* `GalSim` developers to get started with an official Docker build of `GalSim` 

Thanks.

**Comment by rmandelb** [comment]
Pretty cool!  One quick thing that jumps out at me in the failed build is that GalSim definitely requires TMV 0.72, whereas you are using 0.70.  So I think the code should not be able to compile, and perhaps this is the reason it�s failing for you?  Can you see whether upgrading the TMV version makes it work?

**Comment by rmjarvis** [comment]
Even better, use the latest version, 0.73, here: https://github.com/rmjarvis/tmv/releases/tag/v0.73

**Comment by rmjarvis** [comment]
I also updated the version on sourceforce, so you can get it there as well if you like.  (I kind of forgot there was a listing there...)

**Comment by karenyyng** [comment]
I updated my Dockerfile [here](https://gist.github.com/karenyyng/afe01af8ac60bbeab5d1) with an updated version of `tmv-cpp0.73` but `GalSim` still fails during the build. 

The error log can be found in [gs.error](https://gist.github.com/karenyyng/19ddcc4386d848ccb355)

**Comment by rmandelb** [comment]
Sorry if I am being clueless but the comments in the updated Dockerfile seem to indicate that TMV is failing to build (line 44 says "the following line fails" - but the following line is TMV installation, not GalSim).  So is this actually a GalSim problem or a TMV problem?  The error log you are sending is for GalSim, if I understand correctly, so I am a little confused about where the problem is coming in.

**Comment by karenyyng** [comment]
Oops I put the comment on the wrong line. 
[Updated Dockerfile](https://gist.github.com/karenyyng/afe01af8ac60bbeab5d1) should show that line 49 is the offending command.

**Comment by rmandelb** [comment]
OK.  I'm not really the build guru around here but since scons is complaining about an implicit dependency that wasn't found, can you do 

```
RUN ls /usr/src/tmv-0.73/lib/
```

before you try to do the GalSim build?

If that directory has libtmv_symband.so in it, then there is a weird scons problem.  If it doesn't have it, then something did go wrong with TMV somehow.

**Comment by rmandelb** [comment]
(Mike will probably have better ideas, but this one at least isn't too costly in terms of time/effort... :)

**Comment by rmjarvis** [comment]
Get rid of TMV_DIR for the GalSim installation command.  You installed tmv in /usr/local, so that's where you want it to look for the tmv library and header files.  Right now, you're telling it to look in the TMV source directory, which is not correct.

**Comment by karenyyng** [comment]
Oh yes @rmjarvis you are right. I was such an idiot. Thanks for all the help. 
The Docker build is finally successful. :)
I have put the final Dockerfile in this [GitHub repo](https://github.com/karenyyng/GalSim_dockerfile)
And the push to the GitHub dockerfile will automatically trigger a build on the [Dockerhub image](https://hub.docker.com/r/karenyng/galsim_dockerfile/).

**Comment by rmjarvis** [comment]
Cool.  Thanks Karen.

BTW, this bit here will be unnecessary for future GalSim release versions (and is already unnecessary for the master branch):
```
ENV SHELL /bin/bash
RUN mv /bin/sh /bin/sh.orig && ln -s /bin/bash /bin/sh
```

**Comment by rmandelb** [comment]
@rmjarvis - think it's worth mentioning this in INSTALL.md as another option for installation of GalSim on Ubuntu?

**Comment by karenyyng** [comment]
I have updated the README.md in my [GitHub repo](https://github.com/karenyyng/GalSim_dockerfile) so people can get started with using the built image / dockerfile.

**Comment by karenyyng** [comment]
@rmjarvis now the dockerfile uses the master branch of GalSim and the lines creating the symbol link have been commented out.

**Comment by rmjarvis** [comment]
I wasn't actually suggesting that...   We usually prefer that users stick to release versions.  The master branch is not as thoroughly tested and so can occasionally have bugs.

Maybe you could have two files?  `galsim_current` and `galsim_master` or something?  Unfortunately, the `current` version would still need that workaround for dash/bash until our next release.

**Comment by rmjarvis** [comment]
BTW, I added a mention of your repo in the INSTALL file.  cf. e8c828a

Also on the [Install FAQ wiki page](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ#can-i-use-docker-to-containerize-galsim)

**Comment by karenyyng** [comment]
Thanks. Now there are different Docker tags for building `v1.3.0` and the `master` branch separately. Usage instructions are also updated in the GitHub repo.
