### ISSUE TITLE
metacal tests and psf shear

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#730]
regarding branch #720 

It would be nice to see another feature here in the test.  This is when 
we shear the psf, but not the galaxy, to get a correction for the
psf anisotropy.

It would be nice to see scenario 4 work for this case as well.

I can send pull requests for this sort of thing if desired.

**Comment by rmjarvis** [comment]
Likewise, this comment belongs on the Issue #720 thread.
