### ISSUE TITLE
problem with image.order=random in config

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#738]
I think I found either (a) a problem with the implementation of image.order=random in config or (b) an undesirable feature of how the GREAT3-like example scripts ```cgc.yaml``` etc. were set up.

Here is the issue:
- ```cgc.yaml``` has ```image.order=random``` so that the 90-degree rotated pairs aren't right next to each other.
- The output images indeed don't have 90 degree pairs next to each other.
- The output truth tables DO list the 90 degree pairs right next to each other, and there's no information that one could use to figure out where they actually live in the image.

So I'm not sure if this is a bug in ```image.order=random``` implementation, where the locations aren't getting propagated into the truth catalog part of the code, or if it's just that the truth catalogs should have another output column in this example that tells you where to find the galaxies.  But something weird is definitely going on.

**Comment by rmjarvis** [comment]
I see.  I guess we didn't include the real x,y position.  Just the offset.  Probably ought to make x,y = image_pos.x, image_pos.y, and give another name (dx,dy?) to the offset values.  Assuming I didn't screw something up, that should accurately tell you which object is which in the image.

**Comment by rmjarvis** [comment]
Oh, and currently, the cosmos_index value in the truth catalog will tell you which pairs go together.  They'll have the same index.

**Comment by rmandelb** [comment]
> I see. I guess we didn't include the real x,y position. Just the offset. Probably ought to make x,y = 
> image_pos.x, image_pos.y, and give another name (dx,dy?) to the offset values. Assuming I didn't 
> screw something up, that should accurately tell you which object is which in the image.

I tried doing
```
            x: image_pos.x
            y: image_pos.y
            dx: image.offset.x
            dy: image.offset.y
```
but that failed with an exception:
```
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 840, in MultiProcess
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 222, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 427, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image.py", line 232, in BuildImage
    image = builder.buildImage(cfg_image, config, image_num, obj_num, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image_tiled.py", line 157, in buildImage
    xsize=self.stamp_xsize, ysize=self.stamp_ysize, do_noise=self.do_noise_in_stamps)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 104, in BuildStamps
    except_func = except_func)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 808, in MultiProcess
    raise res
TypeError: argument of type 'PositionD' is not iterable
```

Out of only a vague and poorly-justified sense that this might work, I tried
```
            x: "$(@image_pos).x"
            y: "$(@image_pos).y"
            dx: image.offset.x
            dy: image.offset.y
```
and this time it ran (but um, I sure would like to know why that was right and the other was wrong?).  When I looked at the output catalogs, the results were at least semi-plausible, in the sense that the x and y didn't march along rows/columns but rather went in a somewhat random order.  I didn't confirm explicitly that they were correct, but I don't have any reason to think they would be wrong.

Question: is ```cosmos_index``` supposed to be the index in the COSMOS catalog, or the ident value in the COSMOS catalog?  I noticed that for some random image I'm using the maximum value is around 24,000, which is confusing either way, considering that the idents go into the millions and the indices should go into the 57k range.  Is it possible it's storing the index after imposing some pre-selection, which is not what we want it to do, but could explain the lower maximum value?

Once this is sorted, I'll fix all x/y stuff in the GREAT3-like scripts on a branch (not created yet), and make a PR.  But if something is wrong with ```cosmos_index``` that requires fixes inside config, will you do that part?

> Oh, and currently, the cosmos_index value in the truth catalog will tell you which pairs go together. 
> They'll have the same index.

Yes, that's how I knew that the galaxies in the truth catalog had been stored with pairs right next to each other in a way that clearly didn't correspond to the image.  :)

**Comment by rmjarvis** [comment]
In meds.yaml, they would be identical.  But I didn't do the same trick with the Sum of 1 item in cgc.yaml, so it wouldn't work here yet.  However, after doing that trick in meds.yaml I realized that it was unnecessary, since you can access the original from a transformed object via the `original` attribute.  So probably the `$(@gal).original.index` would be the most sensible thing to do here.

**Comment by rmjarvis** [comment]
> Re: the image.pos.x bug, is that something you can easily fix? 

No idea.  I probably won't have a chance to investigate until Friday.

**Comment by rmandelb** [comment]
OK.  In the meantime, I pushed a branch with the updates to cgc.yaml.  Whenever you're ready to tackle the bug, please go for it (I have nothing else to do on here right now).  I hope you don't mind, I added this to the v1.4 milestone.

**Comment by rmandelb** [comment]
Oh wait, never mind, I think your solution for the index doesn't work.  I temporarily got it going when using ```stamp.retry_failures=100```, but it doesn't work with the default value of ```retry_failures```, and I get exceptions like this:
```
Traceback (most recent call last):
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 840, in MultiProcess
    result = job_func(**kwargs)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 222, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/output.py", line 427, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image.py", line 232, in BuildImage
    image = builder.buildImage(cfg_image, config, image_num, obj_num, logger)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/image_tiled.py", line 157, in buildImage
    xsize=self.stamp_xsize, ysize=self.stamp_ysize, do_noise=self.do_noise_in_stamps)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/stamp.py", line 104, in BuildStamps
    except_func = except_func)
  File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/galsim/config/process.py", line 808, in MultiProcess
    raise res
ValueError: Unable to evaluate string '(temp_variable_gal).original.index' as a None
'Sersic' object has no attribute 'index'
```
Given that I never had an issue with ```retry_failures``` being too low before, and now I can't get the script to run without increasing it a lot, here is my thinking on what's wrong:

- When it's making bulge+disk galaxies (about 1/5 of the time), somehow the original index is getting saved properly.
- When it's making sersic galaxies, it's not getting saved properly.
- As a result, with sersic galaxies, it keeps having to retry until it happens to get a bulge+disk galaxy.  And that's why the default ```retry_failures``` no longer works.

Do you have any idea about this?  I am a bit confused because in scene.py, the ```_makeSingleGalaxy``` routine is indeed setting the ```index``` attribute for parametric galaxies, and then when we have a transformed version of the parametric galaxies, it should have the original as an ```original``` attribute with its own ```index```.  So I don't understand why that wouldn't work, and why it might only work for bulge+disk but not for sersics.  Is my whole idea of what's going on here wrong?

**Comment by rmandelb** [comment]
OK, I think I actually figured it out.  The issue, I think, is that our ```_makeSingleGalaxy``` results are not single objects like Sersics, but rather transformations (due to the intrinsic shape, flux rescaling, etc.).  So if we add an ```index``` attribute, then when we do any later transformations to apply the lensing shear, it doesn't get propagated through; instead, the original ```original``` attribute (which was index-free) got propagated.  I think I fixed this in https://github.com/GalSim-developers/GalSim/commit/2697f70e4c4003df8d456efff1e79e7b7cd1796e, but the question is whether there are other places where this is also relevant?

**Comment by rmandelb** [comment]
And by "I think I fixed this", I mean I definitely fixed at least part of the problem (it runs just fine now, without needing me to change ```retry_failures```) but I wonder if there could be some corner cases I'm missing, or would miss when using real galaxies, or whatever.

**Comment by rmandelb** [comment]
Oh, and I think I understand why this was hitting the Sersic but not b+d models:

- Sersic models were transformed by shearing etc.  So they were actually ```galsim.Transformation```s, with an ```original``` attribute already.  Adding an ```index``` to them didn't help, because when they got further transformed by the lensing shear, their already-present ```original``` attribute was copied over, and it didn't have an ```index```.  That's why my latest commit fixed those.
- B+D models were compound/sum objects.  Each component had been transformed, but then they were added together.  The sum doesn't have an ```original``` attribute, but it had been getting an ```index```.  So, when the sums went into a later shearing operations, they didn't have an ```original``` attribute yet, and the final ```galsim.Transformation``` ended up with the compound object (which did have an ```index```) as its ```original``` attribute.

Anyway, since I have talked to myself enough, I will summarize the questions that I think are left for @rmjarvis -

- To think about whether this issue could be a problem elsewhere?  I think it's OK for realistic galaxies, but I'm wondering if it also could be a problem at the end of ```makeGalaxy```?

- The bug discussed in https://github.com/GalSim-developers/GalSim/issues/738#issuecomment-208665396

No rush.

**Comment by rmjarvis** [comment]
> The bug discussed in #738 (comment)

The problem was just that you do need the $.  So `"$image_pos.x"` works fine.  Or `image_pos` will automatically make `image_pos.x` and `image_pos.y` in the output catalog (cf. demo9).

I admit the error message was pretty unhelpful about this, so I've made that a little bit better now:
```
ValueError: Invalid key in GetCurrentValue = image_pos.x
```

**Comment by rmandelb** [comment]
OK - in that case, is there any reason not to make a PR for this?  If it seems all ready, I will make the PR this weekend.

**Comment by rmjarvis** [comment]
Sure.  Let's get this into 1.4 too.
