### ISSUE TITLE
Problem with near-flat probabilities in DistDeviate

### ISSUE THREAD

**Issue by msimet** [GalSim-developers/GalSim#741]
There is a bug in the DistDeviate implementation for near-flat probabilities.  I have a fix for this already and will be making a PR in a few minutes; I include the details here for historical reference.

As a reminder, the DistDeviate works by building the cumulative distribution function from a given PDF, then inverting it to draw an x value given a probability between 0 and 1.  Because we invert the function, it has to be always increasing; however, the true PDF may have regions of p=0.  We can't just collapse them to a single point. If we have a two-peaked distribution, say a series of p-values 
`0.5, 0, 0, 0, 0, 0.5`
for x-values of
`1, 2, 3, 4, 5, 6`
then collapsing to, say, only the x=2 point would mean a constantly-increasing probability between 2 and 6.  But we also can't keep the end points as-is, because x=2 and x=5 would both have a value of 0, so the function would not be invertible.  In the current implementation, we add epsilon to the upper edge of a range of zeros and delete all the points in the middle. That makes the function always increasing, but the region of zeroes is essentially never probed by the inversion, and we maintain the two-peaked distribution.

Here's the problem I just found: p-values of something like
```0.5, 0, 0, 0, 0, epsilon, 0.5-epsilon.```
Now when we add epsilon to the upper end of the range of zeroes, we still produce something non-increasing--we've just shifted up by one the indices where the function is constant.  

The solution here, I think, is to delete the upper edge `n` and let that epsilon at `n+1` stand for the whole range.

**Comment by rmandelb** [comment]
> Here's the problem I just found: p-values of something like

You mean when you give it input that already looks like this, that's when the problem kicks in?  So the idea is to check whether a sequence of zeros has a tiny number after it, and if so, the tiny number can stand for the whole range?  But if there isn't a tiny number after the sequence of zeros then you enforce one, as before?

Just trying to make sure I understand what you're trying to do before I read the code.

**Comment by msimet** [comment]
@rmandelb : Yes, exactly.
