### ISSUE TITLE
Fourier-space Sqrt GSObject/SBProfile (proposed contribution)

### ISSUE THREAD

**Issue by TallJimbo** [GalSim-developers/GalSim#748]
I'd like to implement a the Kaiser algorithm for coaddition (see [Zackay & Ofek 2015](http://adsabs.harvard.edu/abs/2015arXiv151206879Z)) within GalSim.  I think all this requires is a Fourier-space `sqrt` operator on GSObjects, since all of the other operations (autocorrection and sums) already exist.

 - I'm thinking the `AutoConvolve` or `AutoCorrelate` `SBProfiles` look best as as examples to start from, but I'd love any recommendations for a simple Fourier-space only operator.
 - `Sqrt` probably isn't an appropriate name, since it's not a sqrt in real-space.  But it's also not an operation that has a name in real space.  Any other recommendations?

**Comment by rmjarvis** [comment]
Maybe FourierSqrt would be clear and not too verbose?

I'd probably recommend Deconvolve as your template, since it can't be photon shot, and I guess that restriction applies to this too.

**Comment by rmandelb** [comment]
+1 for FourierSqrt

**Comment by TallJimbo** [comment]
Thanks for the excellent suggestions; copying `Deconvolve` made this really easy.  PR will be up shortly.

**Comment by rmjarvis** [comment]
#749 merged.
