### ISSUE TITLE
Version in library

### ISSUE THREAD

**Issue by PaulPrice** [GalSim-developers/GalSim#750]
LSST's meas_extensions_shapeHSM uses HSM from the GalSim library, but doesn't use any of the python.  However, the GalSim version is currently only reported through python.  Please consider adding the code version in the library as well (either through a function or a variable).

**Comment by rmjarvis** [comment]
We do provide command-line versioning via `galsim --version`, so would the following be sufficient for your needs?
```
std::string getGalSimVersion()
{
    // Open the command for reading.
    FILE* fp = popen("galsim --version", "r");
    if (fp == NULL) throw std::runtime_error("Failed to run galsim executable\n" );

    // Read the output into a buffer.
    char buf[1024];
    fgets(buf, 1024, fp);

    // Parse the output.  Should look like: GalSim Version 1.x.x
    std::stringstream ss(buf);
    std::string s1, s2, s3;
    ss >> s1 >> s2 >> s3;
    if ((s1 != "GalSim") || (s2 != "Version"))
        throw std::runtime_error("galsim command gave incomprehensible output.");

    return s3;
}
```

**Comment by rmjarvis** [comment]
(At least until we get around to doing something more direct, that is.)

**Comment by PaulPrice** [comment]
Urgh, that's a dirty hack!  But maybe better than nothing?

**Comment by rmjarvis** [comment]
Paul, I think I implemented what you need, but please take a look at commit e70d3ba.

There are three ways to access the version information from C++.

1. There are #defined values `GALSIM_MAJOR`, `GALSIM_MINOR`, and `GALSIM_REVISION` that are available if you #include "GalSim.h".
2. There are compiled functions that return these same values called `galsim::major_version()`, `galsim::minor_version()`, and `galsim::revision()`.
3. There is a compiled function that returns a string of the form e.g. "1.4.2" that combines all three numbers.

There is also an inline function called `check_version()` that can be used to check that the compiled version information matches the information in the header file you are including.

Let me know if these meet your needs or if you'd like me to add anything else here.

**Comment by PaulPrice** [comment]
Awesome!  I made a couple of super-trivial comments on the commit.

I especially appreciate how complete this is, with macros, constants, and functions so the user can use what he needs; and there's a function to check everything's consistent.  Just bewdaful!

**Comment by rmjarvis** [comment]
Great.  Thanks Paul.  I'll go ahead and merge this then.

**Comment by PaulPrice** [comment]
A student building the LSST stack reports a bug building GalSim, which looks to be related to this:

    :::::  [2016-06-13T21:57:05.464291Z] ValueError: need more than 2 values to unpack:
    :::::  [2016-06-13T21:57:05.464408Z]   File "/Users/lusiawings/Projects/Fan/LSST/lsstsw/build/galsim/SConstruct", line 1869:
    :::::  [2016-06-13T21:57:05.464431Z]     DoConfig(env)
    :::::  [2016-06-13T21:57:05.464487Z]   File "/Users/lusiawings/Projects/Fan/LSST/lsstsw/build/galsim/SConstruct", line 1746:
    :::::  [2016-06-13T21:57:05.464509Z]     DoCppChecks(config)
    :::::  [2016-06-13T21:57:05.464553Z]   File "/Users/lusiawings/Projects/Fan/LSST/lsstsw/build/galsim/SConstruct", line 1624:
    :::::  [2016-06-13T21:57:05.464580Z]     major, minor, rev = platform.mac_ver()[0].split('.')

**Comment by rmjarvis** [comment]
That's not from this.  But it's odd.  Could you have them tell me what the following gives them on their machine?
```
>>> import platform
>>> platform.mac_ver()
('10.10.5', ('', '', ''), 'x86_64')
```
This line is mostly just to give appropriate diagnostic information, so we can guard it with a try/except block and do something sensible, but I'm curious what their version string is that is giving the problem.

**Comment by PaulPrice** [comment]
>>> import platform
   >>> platform.mac_ver()
   ('10.11', ('', '', ''), 'x86_64')

No `rev` for an initial release, apparently.

**Comment by rmjarvis** [comment]
OK, I think this 1517220 should fix it for you.  Done on master.
