### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by timj** [GalSim-developers/GalSim#754]
I am having trouble building GalSim when I am working in a directory that includes a space in the parent. I haven't quite tracked down whether it's Scons or GalSim that is causing the problem. This is with `scons DYLD_LIBRARY_PATH="$LSST_LIBRARY_PATH"` (ie I have quoted the path in the scons call and GalSim reports the correct value and quotes it properly later on:

Lines in `config.log` give a clue:
```
bash -c "DYLD_LIBRARY_PATH='/Volumes/G-RAID with Thunderbolt/transient/lsstsw/src/galsim/lib:/Users/timj/work/lsstsw/stack/DarwinX86/tmv/0.73+a0e9a6df0f/lib:/Users/timj/work/lsstsw/stack/DarwinX86/fftw/3.3.4.lsst2+da39a3ee5e/lib:/Volumes/G-RAID with Thunderbolt/transient/lsstsw/src/qserv/lib:/Users/timj/work/lsstsw/stack/DarwinX86/xrootd/4.3.0a.lsst1+da39a3ee5e/lib:/Users/timj/work/lsstsw/stack/DarwinX86/sphgeom/12.0.rc1+6bbdc56f4c/lib:/Users/timj/work/lsstsw/stack/DarwinX86/protobuf/2.6.1.lsst3+fbf04ba888/lib:/Users/timj/work/lsstsw/stack/DarwinX86/partition/12.0.rc1+144e0d2e07/lib:/Users/timj/work/lsstsw/stack/DarwinX86/libevent/2.0.16.lsst2+da39a3ee5e/lib:/Users/timj/work/lsstsw/stack/DarwinX86/mariadb/10.1.11.lsst2+da39a3ee5e/lib:/Users/timj/work/lsstsw/stack/DarwinX86/mariadbclient/10.1.11.lsst2+da39a3ee5e/lib:/Users/timj/work/lsstsw/stack/DarwinX86/base/12.0.rc1+0a04801fb9/lib:/Users/timj/work/lsstsw/stack/DarwinX86/apr_util/1.5.4+f7ed051de0/lib:/Users/timj/work/lsstsw/stack/DarwinX86/apr/1.5.2+da39a3ee5e/lib:/Users/timj/work/lsstsw/stack/DarwinX86/log4cxx/0.10.0.lsst6+1cc8a4a234/lib:/Users/timj/work/lsstsw/stack/DarwinX86/log/12.0.rc1+8b859c332d/lib:/Users/timj/work/lsstsw/stack/DarwinX86/boost/1.60+fbf04ba888/lib' /Volumes/G-RAID with Thunderbolt/transient/lsstsw/src/galsim/.sconf_temp/conftest_11" > .sconf_temp/conftest_11.out
bash: /Volumes/G-RAID: No such file or directory
```
so the temp executable path is not being quoted properly.

Yes, the external disk on my Mac has a space in the volume name. I do work in a soft-linked directory that doesn't have a path but the soft link is read through and the space comes back in some cases:

```
$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import os.path
>>> os.path.realpath(".")
'/Volumes/G-RAID with Thunderbolt/transient/lsstsw/src/galsim'
>>> 
milo:galsim (master) $ pwd
/Users/timj/work/lsstsw/src/galsim
```

**Comment by rmjarvis** [comment]
I see.  I was able to reproduce this by putting my GalSim into a directory that has spaces.  I think the solution is pretty simple.  cf. 3c273b447c2574ef9deacb827270b6e0375b8438

I'm not sure this works if the directories are even more arcane with escaped quotes or back slashes in them.  (Or even if those are allowed in Macs!)  But at least for spaces, I think this is working.

Let me know if this works for you, and if so, I think we can just merge it to master directly.

**Comment by rmjarvis** [comment]
Tim, is there more to do for this, or should I merge and close this?

**Comment by timj** [comment]
This seems right to me.

**Comment by rmjarvis** [comment]
Great.  I'll go ahead and merge it to master now then.  If you notice any problems with this, of course go ahead and reopen this.
