### ISSUE TITLE
running vs. not running unit tests

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#756]
On @arunkannawadi 's latest pull request, there was an issue with `scons tests` not running the python unit tests.

I just noticed on our Linux cluster that if I'm on the master branch or branch #556, `scons tests` behaves as usual, but if I'm on branch #549 or #748 and do `scons tests`, it does not run the python unit tests:

```
Starting python tests...
Nosetests terminated by signal  11
```

Any ideas based on this additional information?

**Comment by danielsf** [comment]
I just tried branch #549 on my Mac Laptop and the unit tests ran fine.

You might try using git bisect

https://git-scm.com/docs/git-bisect

to isolate the commit that caused the unit tests to break.

**Comment by rmjarvis** [comment]
Did you do the usual things of /bin/rm -rf .scon* to clear out the scons cache to make sure it's correctly recompiling everything it needs to?  Sometimes it gets confused when switching between branches not recognizing things that need to be recompiled.

**Comment by rmandelb** [comment]
@danielsf - they all run fine on my laptop too.  It's just this linux cluster that has the problem.  I was not aware of git-bisect - that's pretty nifty!  Will check it out and report back.

@rmjarvis - Yes, I did do ```rm -rf .scon*``` and then recompile everything.

**Comment by arunkannawadi** [comment]
Well, it was the other way for me. The tests ran on the cluster and did not
run on my laptop.

On Thu, Jun 2, 2016 at 12:35 PM, Rachel Mandelbaum <notifications@github.com
> wrote:

> @danielsf <https://github.com/danielsf> - they all run fine on my laptop
> too. It's just this linux cluster that has the problem. I was not aware of
> git-bisect - that's pretty nifty! Will check it out and report back.
>
> @rmjarvis <https://github.com/rmjarvis> - Yes, I did do rm -rf .scon* and
> then recompile everything.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/756#issuecomment-223348084>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE3fHvQR22gyS-FPlr7YBDys_2IvkYJqks5qHwZegaJpZM4IsoJW>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by jmeyers314** [comment]
Hmmm.... I could definitely be wrong, but signal 11 sounds like a c++ layer kind of error to me.  If it's GalSim's fault, and not some other package, then for \#549, this would be the new LookupTable2D.  Does running `python tests/test_table.py` directly work?

**Comment by rmandelb** [comment]
I happened to be on #748 when I tried the bisect process.  (I did not try this on #549 but I should do that later!)  It told me this commit is responsible:
https://github.com/GalSim-developers/GalSim/commit/37d99ab959c52d7ff09c9b7cf36d92a125e31e22

When I compile and install GalSim at this commit (a completely clean compilation after doing ```rm -rf .scon*```) and try to import galsim, I get this:
```
>>> import galsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: galsim/_galsim.so: undefined symbol: _ZNK6galsim13SBFourierSqrt6getObjEv
```
So if it can't import galsim, this might explain why nosetests exits instead of running any of the python tests!

I wonder if this has something to do with the change in ```__init__.py```, where it's importing from ```compound``` and ```chromatic``` instead of ```.compound``` and ```.chromatic``` like the other imports?  But why would this be a problem on Linux cluster and not my Mac?

**Comment by rmandelb** [comment]
Ah never mind, those imports are not responsible.  I'm confused.

**Comment by rmandelb** [comment]
On #549, starting at https://github.com/GalSim-developers/GalSim/commit/baf3543ea90710929623bb138e2d700d2b499387 , I get the following error when importing galsim on the Linux cluster (not on my Mac):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: galsim/_galsim.so: undefined symbol: _ZNK6galsim7Table1DIddE6lookupEd
```

So that's where it starts.  When I move to the latest version of the branch, it's
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "galsim/__init__.py", line 94, in <module>
    from .position import PositionI, PositionD
  File "galsim/position.py", line 22, in <module>
    from . import _galsim
ImportError: galsim/_galsim.so: undefined symbol: _ZNK6galsim7Table2DIddE14interpManyMeshEPKdS3_Pdii
```

**Comment by rmandelb** [comment]
@arunkannawadi -What happens (on your laptop, on master) if you start up python and do ```import galsim```?  For me, this particular failure is always accompanied by not being able to import galsim.

Did you check whether this happens after you do a clean installation (```rm -rf .scon*```, then compile and install)?

**Comment by rmjarvis** [comment]
I've been trying, but I'm afraid I haven't been able to reproduce this anywhere.  All the linux boxes I have access to do just fine on branch #549.  

My best guess is that somehow there is a mismatch between the `_galsim.so` file that is being imported and the libgalsim.so` library that is being installed.  You can check where galsim is being imported from using imp:
```
>>> import imp
>>> imp.find_module('galsim')
(None, '/home/mjarvis/lib/python2.7/site-packages/galsim', ('', '', 5))
```
(Normally, you would just `import galsim`, then look at `galsim.__file__`, but that doesn't work when the import fails.)

You can then check (with ldd) which `libgalsim.so` `_galsim.so` is trying to use at run time.  Make sure that's the one that is the first one found in your LD_LIBRARY_PATH.

**Comment by rmandelb** [comment]
Thanks.  You are right about the source of this problem.

Using imp, I found that galsim is being imported from the place I expected.  When I used ldd to check out the ```_galsim.so``` at that location, it was pointing to a *completely different* ```libgalsim.so``` from when I used to install shared software elsewhere.

I'm not really sure why it is pointing there, and my initial attempts at fixing this failed.  I'll dig into it more tomorrow.

**Comment by arunkannawadi** [comment]
I started a clean install at 9:40pm. It is still not done yet. But good to
know at least that the source of the problem has been found in the meantime
:)

**Comment by rmandelb** [comment]
Since I couldn't get this to work by messing around with the ordering of directories in my path, I used the super-fancy trick of deleting the old library that was living in the old location where I used to put software, so that the only one it could possibly find is the correct one.  That did indeed fix the problem; sorry for the false alarm about there possibly being a code issue.  

@arunkannawadi - what's your situation?  It would be good to make it possible for you to run unit tests on your laptop on master, considering that running them is something that happens very often whenever you are developing new code...

**Comment by arunkannawadi** [comment]
I did a clean install of GalSim once again on my laptop on the master
branch. I did not have any issues with importing galsim, and no Python
tests run when I type `scons tests`. When I type `nosetests` in the tests/
folder, I get this

```
----------------------------------------------------------------------
Ran 0 tests in 0.022s

OK
```

On Fri, Jun 3, 2016 at 8:40 AM, Rachel Mandelbaum <notifications@github.com>
wrote:

> Since I couldn't get this to work by messing around with the ordering of
> directories in my path, I used the super-fancy trick of deleting the old
> library that was living in the old location where I used to put software,
> so that the only one it could possibly find is the correct one. That did
> indeed fix the problem; sorry for the false alarm about there possibly
> being a code issue.
>
> @arunkannawadi <https://github.com/arunkannawadi> - what's your
> situation? It would be good to make it possible for you to run unit tests
> on your laptop on master, considering that running them is something that
> happens very often whenever you are developing new code...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/756#issuecomment-223568120>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE3fHkZKsGNuDU--ogu-ssA2JSICfcS6ks5qICC5gaJpZM4IsoJW>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
Can you do the checks Mike suggested to confirm which galsim you're using and which library it's trying to use at run time?

**Comment by rmjarvis** [comment]
You can also look at the file tests.log in the tests directory.  It might have something helpful to say about why the tests aren't running.  

You can also try running nosetests yourself from the command line.  The full command line that `scons tests` is using will be in tests.log, but you can also just run `nosetests` with no arguments.

Another thing to check is `which nosetests`.  Sometimes the nosetests that is first in the path does not correspond to the correct python version.  e.g. if you are using anaconda python, you need to use their nosetests, not the one in /usr/local/bin.  (You can see all the ones anywhere in your path with `which -a nosetests`.  Although the one you want might not even ben in your path at all.)  To change which nosetests gets used run `scons tests NOSETESTS=/path/to/nosetests`.

**Comment by rmjarvis** [comment]
I'm assuming this problem has been resolved.  Please reopen the issue if you are still having trouble with this.
