### ISSUE TITLE
test_wfirst.py currently fails

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#757]
Running test_wfirst.py from the command line to get the extra, slightly more time-consuming tests is currently failing:
```
$ python test_wfirst.py
time for test_wfirst_wcs = 1.04
time for test_wfirst_backgrounds = 0.08
time for test_wfirst_bandpass = 0.06
time for test_wfirst_detectors = 0.02
Traceback (most recent call last):
  File "test_wfirst.py", line 519, in <module>
    test_wfirst_psfs()
  File "test_wfirst.py", line 468, in test_wfirst_psfs
    filename=test_file)
  File "/Library/Python/2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 319, in storePSFImages
    method='no_pixel')
  File "/Library/Python/2.7/site-packages/galsim/chromatic.py", line 2003, in drawImage
    wmult, integrator, self.gsparams)
  File "/Library/Python/2.7/site-packages/galsim/utilities.py", line 932, in __call__
    result = self.user_function(*key)
  File "/Library/Python/2.7/site-packages/galsim/chromatic.py", line 1805, in _get_effective_prof
    method='no_pixel')
  File "/Library/Python/2.7/site-packages/galsim/chromatic.py", line 1002, in drawImage
    int_im = self._get_interp_image(bandpass, image=image, integrator=integrator, **kwargs)
  File "/Library/Python/2.7/site-packages/galsim/chromatic.py", line 930, in _get_interp_image
    np.max(self.waves)))
RuntimeError: Requested wavelength 300.0 is outside the allowed range: 900.0 to 1230.0 nm
```
It looks like this is related to the changes in the default thinning/truncation stuff.  The 900-1230 range was designed to match the wavelength range for Y106, but now that filter goes from 300-2200, although most of those values are zeros.

The wfirst `getBandpasses` now has a kwarg `default_thin_trunc` which defaults to False, but given what this bandpass looks like, it seems like either that should probably default to True or we should store versions of the bandpasses that remove the extraneous zeros.

However, even if I do switch that to True, then it's still not quite right.  I need to change the 900 -> 885 on line [433 of test_wfirst.py](https://github.com/GalSim-developers/GalSim/blob/master/tests/test_wfirst.py#L433).  

And then the test still doesn't pass, but I'm not sure if this is a real problem or not:
```
Traceback (most recent call last):
  File "test_wfirst.py", line 519, in <module>
    test_wfirst_psfs()
  File "test_wfirst.py", line 453, in test_wfirst_psfs
    err_msg='PSF at a given wavelength and interpolated chromatic one evaluated at that '
  File "/Users/Mike/lib/python2.7/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/Users/Mike/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 3 decimals
PSF at a given wavelength and interpolated chromatic one evaluated at that wavelength disagree.
(mismatch 0.00629881582263%)
 x: array([[  1.295e-06,   3.367e-06,   3.891e-06, ...,   4.184e-06,
          3.012e-06,   1.152e-06],
       [  2.681e-06,   1.978e-06,   1.822e-06, ...,   1.622e-06,...
 y: array([[  7.226e-07,   1.001e-06,   2.299e-06, ...,   2.268e-06,
          8.914e-07,   7.136e-07],
       [  6.530e-07,   8.959e-07,   2.281e-06, ...,   2.115e-06,...
```
It's only 0.006% of the pixels, so my guess is this is just a numerical fluctuation, not an error.

**Comment by rmandelb** [comment]
Thanks for checking on this.

1. I think you're right that ```default_thin_trunc``` should be True by default; will do this.

2. The change to 885 is needed because that's the ```blue_limit``` of the newly thinned / truncated bandpass.   Really, the answer is that lines 433-434 should not be hardcoded, but rather should be set to the ```blue_limit``` and ```red_limit``` so that even if the bandpasses change, we shouldn't have this problem.  Poor test design on my part, sorry; will fix.

3. Not sure what to do about this 0.006% mismatch; does sound like numerical fluctuations, but I'm reluctant to change the required precision to 2 decimal places.  Let me play around a bit.

**Comment by rmjarvis** [comment]
It all looks fine to me.  I'm happy to just consider this the code review if you want and merge directly to master.

**Comment by rmandelb** [comment]
Thanks.  Will do.  Closing #757.
