### ISSUE TITLE
Testing linkage to static TMV fails

### ISSUE THREAD

**Issue by pmelchior** [GalSim-developers/GalSim#758]
I have tried to help with an install on windows/cygwin, but ran into problems with the linkage test to TMV, which only allows static compilation on the windows platform.

All other libraries and the TMV headers are found, then scons attempts to test the TMV linkage, which takes forever. Eventually, it fails (I don't recall having seen an informative error message). Any ideas how we can solve this (other than moving to linux)?

**Comment by rmjarvis** [comment]
First, GalSim is not supported for Windows.  If you'd like to work to make it run on Windows, that would be a nice service, but we don't have anyone on the team who currently uses it, so I'd expect lots of problems beyond just this one.

Second, GalSim (or any python module) is never going to work linking against a static library.  We have a [FAQ item](https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ#why-does-scons-report-some-error-about-a-bad-value-and-recompile-with--fpic) about it.  I don't think there is any getting around that.  So I'm inclined to close this issue as "won't fix".  Or you could rephrase the title as a feature request that someone work out how to make GalSim run on cygwin (and assign yourself maybe?).

But the question at hand here is really, why can't you install TMV as a shared library?  I'd suggest trying to figure out why that failed and proposing a fix to that.  If you figure something out please submit a PR (or issue with suggested code change) to the [TMV repo](https://github.com/rmjarvis/tmv).

**Comment by rmjarvis** [comment]
I'm assuming by the lack of response here that you're not interested in trying to figure this out.  So I'm content to close this as "won't fix" for the reasons given above.  Feel free to reopen if you're inclined to work on it in the context of getting GalSim working on Windows platforms.

**Comment by esheldon** [comment]
This person seems to have figured out how to get extension packages working on windows.   We could probably learn from it

http://www.lfd.uci.edu/~gohlke/pythonlibs/
