### ISSUE TITLE
boost 1.60 shared_ptr registration

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#764]
I encountered the error 

```
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<galsim::GSParams>
```

in dozens of unit tests when switching from boost 1.59.5 to boost 1.60.0.  This appears to be related to a change in the way the GSParams shared_ptr gets registered.  Inserting the following line at then end of `PyGSParams::wrap` solves the issue under boost 1.60:

```
            bp::register_ptr_to_python< boost::shared_ptr<GSParams> >();
```

but then I start getting the following warning (at least it's not an error!) back under boost 1.59.5:

```
RuntimeWarning: to-Python converter for boost::shared_ptr<galsim::GSParams> already registered; second conversion method ignored.
```

So probably there's a more elegant solution...

**Comment by jmeyers314** [comment]
Just found relevant boost issue: https://github.com/boostorg/python/issues/56

**Comment by rmjarvis** [comment]
I guess wrap that line in
```
#if BOOST_VERSION > 106000
    bp::register_ptr_to_python< boost::shared_ptr<GSParams> >();
#endif
```
