### ISSUE TITLE
config output options: more flexibility with respect to noise

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#774]
Hi again @rmjarvis - another config question for you:

I have a case where I might want to make two versions of the same simulation: one noise-free and one with added noise.  I was looking at the output options on [here](https://github.com/GalSim-developers/GalSim/wiki/Config-Output) to see if there is an obvious way to do this - e.g., to put the noise-free image in one HDU and the noisy one in another.  But that doesn't seem to be possible.  I would guess I could make a custom output type, but I don't think this is a totally crazy thing to want to do, so I was wondering if it would be possible (maybe even easy?) to add this as a config option?  We could disable it if using realistic galaxies rather than parametric ones, since the realistic galaxies will already have noise and there really is no "noise-free" option.

**Comment by rmjarvis** [comment]
Well, there's nothing in the can that does that, although it's not too hard to do this with an "extra output" item.  I mocked up a version you can check out.  I put it on the cgc.yaml example script, where it seems like an appropriate example to include in the repo.  (On branch #774.)  If you think useful, we can merge that to master as part of version 1.4.

**Comment by rmjarvis** [comment]
Here is a screen shot of the output for your viewing pleasure.
<img width="714" alt="noise_free" src="https://cloud.githubusercontent.com/assets/623887/16867668/51cc0cee-4a73-11e6-9b3e-08fe2752fd7d.png">

**Comment by rmandelb** [comment]
Nice!  Thank you.  I think this would be really useful, and suggest merging to master before we tag 1.4.  I also suggest mentioning this example on the wiki page that I linked above, as an example of a potentially useful custom config type for which code is already available.

**Comment by rmjarvis** [comment]
OK.  Merged this to master.  I'll add a mention of it on the wiki page too.
