### ISSUE TITLE
LSST module testing error

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#780]
As part of my v1.4 checks, I tried running the lsst tests on the master branch and got the following test error:

```
ERROR: Test that you can pass a camera from one WCS to another
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/src/GalSim/tests/galsim_test_helpers.py", line 412, in f2
    result = f(*args, **kwargs)
  File "/Users/josh/src/GalSim/tests/test_lsst.py", line 799, in test_passing_camera_by_hand
    self.assertEqual(str(ww[0].args[0]),
AttributeError: 'WarningMessage' object has no attribute 'args'
```

I'm guessing something in the LSST API changed and this needs to follow suit?  (I re-installed the sims from conda just before running the GalSim tests.)  @danielsf, can you take a look?  Also, should the `self.assertEqual`s in this method be inside the `with` block?

Finally, I'm also seeing a deprecation warning:

```
/Users/josh/src/GalSim/tests/test_lsst.py:377: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  for ii in rng.random_integers(0,3,n_samples)]
```

Looks like this would also be pretty easy to address now.

**Comment by danielsf** [comment]
What version of python are you running?

**Comment by jmeyers314** [comment]
Anaconda 2.7.11

**Comment by danielsf** [comment]
This is not an LSST problem.  It is a shift in python warnings API between python 2 and python 3.  See commit 229045e5.  I will look into whether there is a python-version-agnostic way to fix it.

**Comment by danielsf** [comment]
I can't even get as far as you did running test_lsst.py
```
D-173-250-159-162:GalSim danielsf$ python tests/test_lsst.py
Traceback (most recent call last):
  File "tests/test_lsst.py", line 24, in <module>
    import galsim
  File "/Users/danielsf/GalSim/galsim/__init__.py", line 100, in <module>
    from .table import LookupTable, LookupTable2D
  File "/Users/danielsf/GalSim/galsim/table.py", line 530, in <module>
    _galsim._LookupTable2D.__getinitargs__ = lambda self: \
AttributeError: 'module' object has no attribute '_LookupTable2D'
```

**Comment by danielsf** [comment]
oops.  Sorry.  Forgot that this wasn't pure python
