### ISSUE TITLE
'Unable to import future using the python executable' 

### ISSUE THREAD

**Issue by brgillis** [GalSim-developers/GalSim#785]
I'm trying to compile the master branch right now, and I'm getting the error "Unable to import future using the python executable:
/usr/bin/python"

I'm using python version 2.7.9, to there shouldn't be any issues with it. It looks like the problem is that this version doesn't have a module specifically named 'future'. It does, however, have '\_\_future\_\_'.

**Comment by rmandelb** [comment]
You need to install the future module directly (see directions in INSTALL.md).  This is a new GalSim dependency, so you would not have encountered this before.

**Comment by brgillis** [comment]
This seems to work, thanks - I was only looking at the installation instructions from here: https://github.com/GalSim-developers/GalSim/wiki/Installation-Instructions , which doesn't list it yet (I'm guessing because this is targeted at v1.3).

**Comment by rmandelb** [comment]
Hmmm, where did you get to that page from?  If I go to the front page of the wiki, and click on the link for installation instructions, it takes me somewhere up-to-date (the INSTALL.md file on master).  I can delete that old file that you found - it's from years ago - but was it actually linked from anywhere?

**Comment by brgillis** [comment]
That's the page that comes up first for me (and I imagine others) when doing a Google search for "galsim installation"

**Comment by rmandelb** [comment]
Ah, that's not good, since it was last edited in 2012.

I think my best bet for now is to make it so that page displays the current INSTALL.md as well.  I'll go do that.

**Comment by rmandelb** [comment]
Thanks for helping us ensure that our documentation that people are finding is up to date :)

**Comment by brgillis** [comment]
No problem. Wasn't the problem I was expecting to help solve here, but glad we got it done.
