### ISSUE TITLE
Change SED units from photons/nm to photons/nm/s/meter^2

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#789]
This is a proposal to change the units of SEDs from photons/nm, which is a joint property of a particular object *and* the telescope aperture / exposure time used to observe it, to photons/nm/s/m^2, which is a property of just the object itself.  I think this will make it less confusing to calculate what the same object would look like using different telescopes / exposure times than in our current setup where you have to actually create distinct ChromaticObjects to get this right.  That said, this may lead to a number of downstream changes, such as under what circumstances a Bandpass requires a `.zeropoint` attribute.  I think we should try it and see what breaks though.

**Comment by rmandelb** [comment]
If we were designing this functionality from scratch again, I would be inclined to say that you are right.  So for me, I think it's a question of how many things would break if you do that...

**Comment by jmeyers314** [comment]
> I think it's a question of how many things would break if you do that...

I think the switch is the right thing to do almost regardless, but I'm certainly going to try and make the transition as seamless as possible.  We may be able to get pretty far just by having default zeropoints that assume an exposure time of 1s and a collecting area of 1m^2.

I'll report here which things start to break, and we can discuss further.

**Comment by jmeyers314** [comment]
I think I got this working now, and it did turn out to be most transparent.  I actually decided to go with photons/nm/cm^2/s instead of photons/nm/m^2/s since this is more cgs-consistent, and share/vega.txt is already in cgs units, for example.

I did run into a bit of trouble with one of the wfirst unit tests comparing the expected WFIRST photon flux given an SDSS-normalized SED.  I had to degrade the tolerance of the test from 10% to 15%.  I think this may have been a case where the previous code was actually not doing the right thing though, and may have even passed by virtue that WFIRST and SDSS have similar collecting areas.  I like the current test better.

Finally, this change has made me aware of some other dimensionally inconsistent things.  For example, since I'm now hiding the collecting area and exposure time in the `Bandpass` (btw, I'm now hiding the collecting area and exposure time in a `Bandpass` object), multiplying a `Bandpass` by an `SED` no longer yields an `SED`  (photons/nm/cm^2/s  != photons/nm).  Similarly, I think some of the logic in the Chromatic deconvolution/autoconvolution/etc doesn't make sense.  For example, ChromaticDeconvolution has a line: `self.SED = lambda w: 1./obj.SED(w)`, which is dimensional nonsense.

I think the issue here is that we effectively have two types of `ChromaticObject`s that aren't currently being distinguished.  Some chromatic objects, such as `galsim.Gaussian() * galsim.SED()`, effectively represent a profile with units of [photons / nm / cm^2 / s / arcsec^2], while others, such as `galsim.OpticalPSF` only represent a profile with units [1/arcsec^2].  To make an image, we generally convolve one of the former types (SED'd ChromaticObjects) with some number of the latter types (non SED'd ChromaticObjects).  I don't think it ever makes sense to convolve two or more SED'd ChromaticObjects, or add together an SED'd and non-SED'd ChromaticObject.  Similarly, ChromaticDeconvolution/AutoConvolution/etc only make sense for the non-SED'd ChromaticObjects.

Probably we can keep distinguish the two types above and make things consistent just by using a default `ChromaticObject.SED = None` instead of `SED = galsim.SED('1')`  and appropriate introspection for when `self.SED is None`.  I think I'll try this out today, but I'm curious, @rmandelb, if you have thoughts about this since I think we've (politely) collided on related issues in the past. :).

**Comment by rmjarvis** [comment]
I think the `sed=None` solution for PSFs makes a lot of sense.  They don't really have a flux in the same sense as galaxies do.  They are a function that preserves the flux of the galaxy, so we've called that flux=1, but that doesn't have any units.  It's not even 1 ADU, the normal units of flux for galaxies.  It's just a dimensionless normalization of the profile.

So for chromatic things where the "flux" (aka SED) has non-trivial units, I think it makes more sense to not give it any SED and just have PSF(lambda) always return an object with dimensionless "flux" = 1.

>  multiplying a Bandpass by an SED no longer yields an SED (photons/nm/cm^2/s != photons/nm).

Does this imply that we should have a new class that encapsulates the concept of photons/nm?  It seems like this is a useful thing to want to calculate, and I thought there were even use cases already where we performed that multiplication...  We want it to have a well-defined return type.

**Comment by jmeyers314** [comment]
>So for chromatic things where the "flux" (aka SED) has non-trivial units, I think it makes more sense to not give it any SED and just have PSF(lambda) always return an object with dimensionless "flux" = 1.

Yep.  That was exactly my plan.

>Does this imply that we should have a new class that encapsulates the concept of photons/nm? 

Sure.  I'm not exactly sure what to call it though.  `IntegratedSED`?  Or maybe the product is `SED` and the old class is `SpecificSED`?  I don't really like either of those to be honest.  Suggestions appreciated.

>It seems like this is a useful thing to want to calculate, and I thought there were even use cases already where we performed that multiplication... We want it to have a well-defined return type.

I thought we were using it too, but when I prohibited it in `Bandpass.__mul__`, nothing broke.  I think what we're actually doing is always evaluating the product one wavelength at a time: `blah = lambda w: sed(w) * bandpass(w)`, for example.

**Comment by jmeyers314** [comment]
Another option for `sed * bandpass` would be to ignore the collecting area and exposure time so that the product is still an `SED`.  We could then use `bandpass.exptime` and `bandpass.area` explicitly in `ChromaticObject.drawImage()`, instead of relying on getting these through `sed * bandpass`.  I.e., we'd integrate `self.gsobject * (self.sed * bandpass)(w) * bandpass.area * bandpass.exptime)`.

**Comment by rmjarvis** [comment]
Then you'd still need the bandpass after multiplying sed*bandpass.  That seems clunky to me.

Also, it's not clear why area and exptime are appropriately attributes of bandpass.  Seems like they should be parameters to drawImage if we aren't going to keep them in SED (which was implicitly the old way of doing things).

**Comment by jmeyers314** [comment]
>Seems like they should be parameters to drawImage

Yeah, I thought of that too.  My reluctance was that the number of parameters sent to drawImage then gets larger, and the bandpass, collecting area, and exposure time are almost always needed together so it was nice to package them together.

**Comment by rmandelb** [comment]
At the risk of complexifying the class hierarchy, could we make a class called something like ```Observation``` or ```ObservingParameters``` that includes the bandpass, exposure time, and collecting area, and then send that as a kwarg to ```drawImage``` (instead of 3 separate kwargs).

I didn't read this whole thread in detail due to various things going on today, but this might be one way to help the situation you are discussing in the last few comments?

**Comment by jmeyers314** [comment]
>could we make a class called something like Observation or ObservingParameters that includes the bandpass, exposure time, and collecting area, and then send that as a kwarg to drawImage

...and for backwards compatibility, `drawImage()` could still accept a bare `Bandpass` too, in which case it would just use default values for exptime and area...

**Comment by rmjarvis** [comment]
I think I prefer just adding exptime and area as kwargs that each have a default value of 1 rather than adding a new Observation class.  Mostly because I think these should probably be kwargs of the achromatic drawImage function too.  Then people can have objects with flux in units of photons/cm^2/s and render them with different exposure times or on different telescopes.  I don't think this discussion is only relevant in the chromatic context.

Also, it leads back into David Kirkby's recommendation that we use the astropy units module to keep track of all these things in a coherent way.  But perhaps that's still a job for another day.

**Comment by jmeyers314** [comment]
>Then people can have objects with flux in units of photons/cm^2/s and render them with different exposure times or on different telescopes. I don't think this discussion is only relevant in the chromatic context.

Good point.

Any thoughts on how/where best to propagate `area` and `exptime` into `.noise` attributes?  I guess CorrelatedNoise.drawImage() needs to accept the same new kwargs as GSObject.drawImage().  I notice that the former ignores `gain`, but I think we would want it to scale with `area` and `exptime` though, right?

**Comment by jmeyers314** [comment]
I think it would be nice if `ChromaticObject` had similar methods for calculating/rescaling flux as `SED`: e.g., `.withFlux()`, `.withFluxDensity()`, `.withMagnitude()`, `.calculateFlux()`, `.calculateMagnitude()`.  These would get/set the spatially-integrated normalizations.  It would also be nice if the calculate methods agreed with the associated chromatic_object.SED methods though:

```
assert chromatic_object.calculateFlux(bandpass) == chromatic_object.SED.calculateFlux(bandpass)
```
For this to hold and make sense, I think we’ll need to move the flux normalization from being a joint property of `chromatic_obj.gsobect.flux` and `chromatic_obj.SED`, to being a property of just of `chromatic_obj.SED` (and making `chromatic_obj.gsobject.flux = 1`).  We could still accept mixed normalization when creating objects, the normalization would just be stored internally in a more constrained manner.  E.g., `Chromatic.__init__` would change from

```
def __init__(self, gsobj, SED):
    self.obj = gsobj
    self.SED = SED
```

to

```
def __init__(self, gsobj, SED):
    flux = gsobj.getFlux()
    self.obj = gsobj/flux
    self.SED = SED*flux
```

Some of the `ChromaticTransformation` and compound object logic will also be affected.  

Thoughts?

**Comment by rmjarvis** [comment]
That makes sense to me.  The SED is really the correlate of flux for chromatic objects, and in fact "flux" doesn't really have any meaning for them other than in the context of a particular bandpass.  So I think this all seems sensible.

**Comment by jmeyers314** [comment]
It occurs to me that we can't assume that the normalization of `ChromaticObject`s with `.SED = None` is unity.  For example, the following is a contrived, but presumably valid, chromatic PSF:

```
f1 = lambda w: w
f2 = lambda w: 1-w

psf1 = galsim.Gaussian(fwhm=1) * f1  # Makes a ChromaticTransformation
psf2 = galsim.Gaussian(fwhm=2) * f2

psf = psf1 + psf2
```

The final psf above is properly normalized, but the components are not.  The components still need to be constructible though.  So I think this implies that `ChromaticObject`s need both a `.SED` attribute and a `._flux_ratio` attribute, though presumably only one or the other should be meaningful (or even non-`None`) for a given object.

It also occurs to me that instead of keeping track of both a `._flux_ratio` and a `.SED`, we could instead have both `ChromaticObject`s and `FluxedChromaticObject`s (something like this might work for distinguishing `GSObject`s too).  That would be kind of a big change, but I think it's one that would be mostly transparent to users, since they presumably interact mostly with the derived classes and not `ChromaticObject` or `GSObject` directly.  I'm not currently planning on implementing this here, but I'm curious what others' thoughts are.

**Comment by jmeyers314** [comment]
Just realized today that we have a bug with the way chromatic transformations revert InterpolatedChromaticObjects back to their uninterpolated versions.  There's a check in ChromaticTransformation that attempts to catch these.  It will miss though if an achromatic transformation is applied first, and then a chromatic transformation.  For example:

```
    def dilate_fn(w):
        return (w/500.0)**0.2
    gsobj = galsim.Gaussian(fwhm=1)
    chrom = galsim.ChromaticObject(gsobj).dilate(dilate_fn).interpolate(waves=[400., 700.0, 1000.0])
    caught = chrom.dilate(dilate_fn)  # This raises a warning and undoes the .interpolate in the line above.
    uncaught = chrom.shear(g1=0.1).dilate(dilate_fn)  # This does not raise the warning or undo the interpolation.
```

The best solution I've thought of so far is to just raise the warning and undo the interpolation even if the transformation is achromatic.

**Comment by rmjarvis** [comment]
I think it's possible to at least catch this case with something like this:
```
if isinstance(obj, Transformation) and isinstnace(obj.original, InterpolatedChromaticObject):
    warnings.warn(...)
    obj = galsim.Transform(obj.original.original, jac=obj.jac, ...)
```
But this does seem like a rather specific hack, so it's probably pointing out a design flaw in how we're keeping track of the interpolation.  I don't have a particularly better idea about how to do this though.

**Comment by jmeyers314** [comment]
I've thought a bit more about this now.  I think keeping track of an `.interpolated` boolean attribute, and implementing a `.deinterpolate()` method should both be feasible.

**Comment by jmeyers314** [comment]
I think I'm almost done with this issue.  In addition to the unit change mentioned in this issue's title, I've reworked the way chromatic objects are amplitude normalized so that they obey the following invariant (comment extracted from chromatic.py):

```
    # ChromaticObjects should adhere to the following invariants:
    # - Objects should define the attributes:
    #   * .SED, ._norm, .separable, .wave_list, .interpolated
    # - Exactly one of the attributes .SED and ._norm should be None.
    #   * If ._norm is not None, then:
    #     - ._norm should be one of:
    #       * a callable function of wavelength, returning a float normalization
    #       * a scalar float normalization
    #     - obj.evaluateAtWavelength(lam).drawImage().array.sum() == obj._norm(lam)  (callable)
    #     - obj.evaluateAtWavelength(lam).drawImage().array.sum() == obj._norm  (scalar)
    #     - obj.evaluateAtWavelength(lam).drawImage().array.sum() ==
    #       obj.evaluateAtWavelength(lam).getFlux()  # Like all GSObjects
    #     - obj.drawImage(bandpass) raises a ValueError
    #     - Note that ._norm is essentially unitless in this case, and the units of the GSObject
    #       returned by evaluateAtWavelength are 1/arcsec^2 (or 1/scale_unit^2 if not using arcsec
    #       as the implicit angle units).
    #   * If .SED is not None, then:
    #     - .SED should be a galsim.SED instance
    #     - obj.SED.calculateFlux(bandpass) == obj.calculateFlux(bandpass) ==
    #       obj.drawImage(bandpass).array.sum()
    #     - obj.evaluateAtWavelength(lam).drawImage().array.sum() == obj.SED(lam)
    # - .separable is a boolean indicating whether or not the profile can be factored into a
    #   spatial part and a spectral part.
    # - .wave_list is a numpy array indicating wavelengths of particular interest, for instance, the
    #   wavelengths at which SED is explicitly defined via a LookupTable.  These are the wavelengths
    #   that will be used (in addition to those in bandpass.wave_list) when drawing an image of the
    #   chromatic profile.
```

I have a few more ideas that may or may not be worth pursuing including:

- Deprecate `galsim.Chromatic` since `galsim.ChromaticTransformation` can now accomplish the same thing.
- Deprecate `galsim.ChromaticObject.__init__()`, i.e., keep `ChromaticObject` as an abstract base class, but deprecate its direct instantiation.  Instantiating this class is currently only needed just prior to applying a wavelength-dependent transformation to a `GSObject`.  I think it would be more natural, however, for the `GSObject` transformation methods to just accept wavelength-dependent arguments and construct `ChromaticTransformation` objects directly.
- Create a `ChromaticNormalization` type, which `SED` could inherit from.  The difference between `ChromaticNormalization` and `SED` would be that the former is unit-less and the latter has units of photons/nm/cm^2/s.  `ChromaticNormalization` could then replace the `lambda`s I'm currently using to track non-SED wavelength-dependent normalizations, which _might_ lead to nicer looking, better picklable code.
- Add a `size_fac` kwarg to `InterpolatedChromaticObject.__init__()`, to adjust the size of the stored images being interpolated.  I think some of the loss of flux accuracy we see in `InterpolatedChromaticObject` is just due to flux leaking past the edge of the stored images.  This new kwarg would be a more convenient way to recover this flux than manipulating the object-to-be-interpolated's `gsparams.folding_threshold`.

Thoughts?

**Comment by jmeyers314** [comment]
Merged.
