### ISSUE TITLE
boost python 3 on ubuntu

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#790]
On recent ubuntu, the boost python library is named

    libboost_python-py35.so

however galsim expects 

    libboost_python3.so

There is a bug for this in ubuntu (https://bugs.launchpad.net/ubuntu/+source/boost1.53/+bug/1231609) but it is three years old, so unlikely to be fixed.

I  had to add a sym link.  However on many systems the user won't be able to add the sym link due to privilege restrictions, and compiling boost separately is daunting.

Does it make sense to add a check for this library name?

**Comment by rmjarvis** [comment]
Sure.  Try branch '#790'.  I think this should fix it for you.

**Comment by esheldon** [comment]
This works.

But soon there will be a py36, then a py37...   So maybe it would be better to check for a version that matches the one being used to run the setup.py?

**Comment by esheldon** [comment]
Actually any thing with the pattern `-py3*` would probably work fine.  If one is using anaconda one may not have a perfect match anyway.

**Comment by rmjarvis** [comment]
> Actually any thing with the pattern -py3* would probably work fine. 

I don't know an easy way to have SCons check for libraries using a wildcard.  We could generate the name from the python target (not the one used to run scons, since that doesn't have to match the target python -- remember we're not using setup.py here).

**Comment by esheldon** [comment]
right, this is getting complicated.   Might have to bite the bullet and add a long list of possibilities.

**Comment by rmjarvis** [comment]
I switched it to test for the targeted python version.  I think this should work for the current Ubuntu distros and be relatively future-safe for upcoming python versions.

I should mention that it's also possible to manually add library names for SCons to use with `scons EXTRA_LIBS=boost_python-py35` if a user has some other unexpected name for their boost-python library.  I'm happy with adding this as a standard check, but the `EXTRA_LIBS` option should provide a workaround for whatever your system has if it's not one of our standard checks.

**Comment by rmjarvis** [comment]
Closed via #800
