### ISSUE TITLE
Conda install of galsim

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#794]
Is it now possible to use the LSST conda channels to perform a conda installation of GalSim that does not pull in a lot of unrelated LSST packages?  That would be great, so this issue is to document the current status and hopefully get it working.

As a first test, I created a conda environment containing only the LSST galsim package:

```
% conda create -n galsim14 --channel http://conda.lsst.codes/sims --channel defaults --override-channels lsst-galsim
```

This looks promising:

```
% source activate galsim14
(galsim14) % conda --list
# packages in environment at /Users/david/anaconda/envs/galsim14:
#
astropy                   1.2.1               np111py27_0  
eups                      2.0.2                         0    http://conda.lsst.codes/sims
lsst-astropy-eups-configs 0.0.1.2                       0    http://conda.lsst.codes/sims
lsst-boost                1.60.post1                    0    http://conda.lsst.codes/sims
lsst-fftw                 3.3.4.2                       0    http://conda.lsst.codes/sims
lsst-galsim               1.3.2.2.post2                 0    http://conda.lsst.codes/sims
lsst-numpy-eups-configs   0.0.2.post1                   0    http://conda.lsst.codes/sims
lsst-pyfits               3.4.0.post4                   0    http://conda.lsst.codes/sims
lsst-python-d2to1         0.2.12.1                      0    http://conda.lsst.codes/sims
lsst-python-eups-configs  0.0.4                         0    http://conda.lsst.codes/sims
lsst-scons                2.5.0.1                       0    http://conda.lsst.codes/sims
lsst-stsci-distutils      0.3.7.1                       0    http://conda.lsst.codes/sims
lsst-tmv                  0.73.post2                    0    http://conda.lsst.codes/sims
nomkl                     1.0                           0  
numpy                     1.11.1             py27_nomkl_0  [nomkl]
openssl                   1.0.2h                        2  
pip                       8.1.2                    py27_0  
python                    2.7.12                        1  
readline                  6.2                           2  
setuptools                25.1.6                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  
```

Note that I named my env `galsim14` expecting to get the new version 1.4 but I actually got 1.3.x. Also note that the LSST stack uses nomkl versions of numpy, etc, but that is hopefully a temporary issue (more details [here](https://github.com/DarkEnergyScienceCollaboration/WeakLensingDeblending/issues/17#issuecomment-239213187)).

Unfortunately, I cannot `import galsim` in this new environment.  My first test using ipython failed because I did not install ipython in the new environment (which is easy to fix), so ipython ran in my conda root environment and picked up my previously non-conda-installed galsim.

My second test used the plain python shell, so runs within the new environment, but now cannot find galsim.  My module search path looks ok:

```
>>> import sys ; sys.path
['', ...,
'/Users/david/anaconda/envs/galsim14/lib/python27.zip', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/plat-darwin', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/plat-mac', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/plat-mac/lib-scriptpackages', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/lib-tk', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/lib-old', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/lib-dynload', 
'/Users/david/.local/lib/python2.7/site-packages', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/site-packages', 
'/Users/david/anaconda/envs/galsim14/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg']
```

but it looks like galsim is installed under `/Users/david/anaconda/envs/galsim14/opt/lsst/galsim` which is not being search.  Perhaps some EUPS magic is required here?

**Comment by dkirkby** [comment]
The EUPS magic wasn't too hard after all:
```
(galsim14) % source eups-setups.sh
(galsim14) % setup galsim
```
Note that the first line is finding `eups-setups.sh` in `~/anaconda/envs/galsim14/bin/` which is the first entry on `$PATH` in the `(galsim14)` environment.  The second line is finding `setup` from the same path, and creates the following `$PYTHONPATH`:
```
/Users/david/anaconda/envs/galsim14/opt/lsst/galsim/lib/python:
/Users/david/anaconda/envs/galsim14/opt/lsst/galsim:
/Users/david/anaconda/envs/galsim14/opt/lsst/stsci_distutils/lib/python:
/Users/david/anaconda/envs/galsim14/opt/lsst/python_d2to1/lib/python:
/Users/david/anaconda/envs/galsim14/opt/lsst/pyfits/lib/python:
/Users/david/anaconda/envs/galsim14/opt/eups/python
```
This prescription is specific to `bash`, but there are also `.csh` and `.zsh` scripts available to source.

To undo the steps above and get back to your original conda environment:
```
(galsim14) % setup -u galsim
(galsim14) % source deactivate
```
This still leaves `~/anaconda/envs/galsim14/opt/eups/python` on `$PYTHONPATH`, which was put there by `source eups-setups.sh`.

**Comment by danielsf** [comment]
FYI: GalSim 1.4 should become available when we publish the next lsst_sims conda release, which will hopefully be this week.

**Comment by dkirkby** [comment]
@danielsf Any chance that the nomkl issues will be resolved by then?

**Comment by danielsf** [comment]
Are you running Mac or Linux?  I ask because my understanding is that the nomkl problem has already been fixed for Mac.  Unfortunately, it is not fixed for Linux and no one has yet been assigned to workon fixing it for Linux.

Of course, if you are running Mac and still getting the nomkl versions, that is another problem.

**Comment by cwwalter** [comment]
This keeps coming up but I think no binary version with this implemented has been pushed yet.

**Comment by cwwalter** [comment]
(I meant for Mac)

**Comment by danielsf** [comment]
Sorry.  I thought the conclusion of our last discussion was that the binary on the sims channel was going to be replaced with an mkl-compliant version.  Apparently that did not happen.  Sorry for sowing confusion.

**Comment by cwwalter** [comment]
No problem... I think somehow Josh H. is responsible for this? Is that right?  We should make sure that when the sims build happens this is actually included.

**Comment by dkirkby** [comment]
I did an initial conda install of lsst-sims to Mac on Aug 10 (see DarkEnergyScienceCollaboration/WeakLensingDeblending#17) and got nomkl versions then.  Its a pain because every subsequent conda install wants to replace my nomkl versions.

**Comment by danielsf** [comment]
JMatt Peterson is now in charge of the conda builds of LSST software.

@dkirkby the new version will fix the nomkl problem on Macs.

**Comment by cwwalter** [comment]
Note (if someone else is watching this) this gives you a binary version..  Scott also updated the eups table file so that if you the galsim installation first like above you can also just clone the galSim source build it and then declare it to be the working version.  This is needed for GalSim development.

**Comment by danielsf** [comment]
FYI: the from-source sims_2.3.0 has been available since last week.  Just use these directions

https://pipelines.lsst.io/install/newinstall.html

except do ```eups distrib install lsst_sims -t sims``` instead of ```eups distrib install lsst_apps -t v12_0```

We have been unable to publish a binary install due to conda-specific issues.

**Comment by cwwalter** [comment]
> conda create -n galsim14 --channel http://conda.lsst.codes/sims --channel defaults --override-channels lsst-galsim

Just for my information:  What does the --override-channels do here given that you are also adding default to the list explicitly?

**Comment by dkirkby** [comment]
Without `--override-channels`, any channels listed with `--channel` args are added to your existing conda channels, but I wanted a recipe that was independent of your existing channels.

**Comment by josePhoenix** [comment]
Has there been any progress on this? I have been experimenting with [Binder](https://mybinder.org) and would like to be able to use GalSim in my binders, but building/installing in a Dockerfile seems daunting.

**Comment by rmjarvis** [comment]
No.  Nor is it likely that there will be, at least by the developers of GalSim.  We're moving toward a pip installation, but that's still several months out at least.

**Comment by cwwalter** [comment]
For non-LSST people who might be confused by material earlier in the issue: the LSST binary installs no longer use conda.  They use a conda python distribution but the binaries of the LSST software itself will now be installed via eups (like for source builds). So, there is also no (recent) LSST supplied conda based GalSim.

**Comment by rmjarvis** [comment]
I think this issue is now obsolete.  We will fairly shortly be releasing GalSim version 2.0, which will be easy to install on conda.  Instructions for installing the `noboost` branch with conda are given [here](https://github.com/GalSim-developers/GalSim/blob/noboost/INSTALL.md).  Anyone who has been having trouble installing GalSim in Anaconda can give that a try.  That branch will become GalSim version 2.0 probably in the next month or two.
