### ISSUE TITLE
config bug or config documentation confusion

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#802]
I have run into a few issues recently while generating some simulations for HSC.  One of them is either a config bug or a problem with the config documentation.

The impression I get from the examples/great3/ yaml files and the config wiki is that there are three ways to use a template .yaml file and configure some of the details afterwards.

-  suck in the entire .yaml file as a template, then change some details, for example as in examples/great3/rgc.yaml where it does stuff like
```
template : cgc.yaml
gal.gal_type : real
image.noise.whiten : True
output.dir : real/ground/constant
```
thereby modifying the galaxies from parametric to real, whitening the noise, and changing the output location.

- suck in parts of the .yaml file as a template.  For example as in cgc_psf.yaml
```
psf:
    template : 'cgc.yaml:psf'
```
and as on [the wiki](https://github.com/GalSim-developers/GalSim/wiki/Config-Documentation#template), "The template field may appear anywhere in the config file. Wherever it appears, the contents of the other file will be a starting point for that part of the current config dict, but you can replace or add values by specifying new values for some of the fields."  So this suggests one could later do something like ```psf.index_key : obj_num``` or some such thing, just as in the first case when you suck in the whole file as a template and modify bits later.

- Suck in your template and/or specify things in the .yaml file, but then modify bits when you call the galsim executable at the command line.

The crux of the problem I identified is that the first and third option work, and the second one does not.  It just quietly ignores later modifications if you have sucked in parts of another .yaml file as a template.

Is this the intended behavior?  If so, then the config documentation needs some updating.

Or if it's not the intended behavior, would it be possible to fix the bug and also tag a v1.4.3 so we can used a tagged version for HSC sims?

**Comment by rmjarvis** [comment]
> So this suggests one could later do something like psf.index_key : obj_num or some such thing, just as in the first case when you suck in the whole file as a template and modify bits later.

Not quite.  It should look like this:
```
psf:
    template : 'cgc.yaml:psf'
    index_key : obj_num
```

**Comment by rmjarvis** [comment]
It looks like I don't have any examples of that (in the great3 directory or in the docs on the wiki).  So assuming that this works as it's supposed to, and there's not a bug in config, we should add an example like this to the docs to try to clarify the admittedly confusing text that's there now.

**Comment by rmandelb** [comment]
Huh.  That seems inconsistent from the first case.  In the first case, you suck in the entire template, so you implicitly have already defined the entire ```gal```, ```psf```, etc. blocks.  Then you can come back later and edit bits of the already-defined blocks.  But in this case, when you suck in a template for a given block, you can't come back later and edit bits of the already-defined blocks?

At minimum, I think this needs a documentation update and preferably a working example.  But I recommend changing it so the functionality is not so completely different in spirit, unless there is something about this that I'm missing and it's not as inconsistent as I think?

**Comment by rmandelb** [comment]
Oh, another thing that would be useful: would it be possible to make config tell you if you've done something that it intends to completely ignore?  That would also have made this problem apparent if it had said "hey, you tried to modify this ```gal``` block but I'm not letting you do that" instead of just quietly ignoring it.  Or would this break something else?

**Comment by rmjarvis** [comment]
> Oh, another thing that would be useful: would it be possible to make config tell you if you've done something that it intends to completely ignore?

That's very difficult to do, since you are allowed to define additional blocks at the config top level that you can use for whatever you want.  e.g. a custom stamp type could use a top-level `agn` field or something like that.   `demo4.yaml` shows an example that defines a top-level `some_variables` field.

**Comment by rmandelb** [comment]
What about doing that for the required blocks?

**Comment by rmjarvis** [comment]
> But in this case, when you suck in a template for a given block, you can't come back later and edit bits of the already-defined blocks?

In all cases, you can modify things at the same level as the template specification, so I think things are actually consistent.  The config processing handles the modifications at the same dict level as the template, so for instance the following should also work:
```
psf:
    template : 'cgc.yaml:psf'
    index_key : obj_num
    items.0.ellip.e.max : 0.05
    items.1.nstruts : 1
    items.1.strut_angle : { type : Random }
```
Note the lack of the `psf.` prefix on these, since you are already in the `psf` field.

**Comment by rmandelb** [comment]
OK - it's consistency of a different sort (at the level of template specification).

So... documentation/examples update?  Maybe both?

**Comment by rmjarvis** [comment]
I added the above example to the documentation on the [wiki](https://github.com/GalSim-developers/GalSim/wiki/Config-Documentation#template).  Please feel free to edit further if you think it could be made clearer.

**Comment by rmjarvis** [comment]
> What about doing that for the required blocks?

Here is a compromise that I think would generally give people the information they need to diagnose problems.  On #580 I added a warning about any top-level items that are not expected by config:
```
$ galsim demo4.yaml
Using config file demo4.yaml
Warning: config dict contains the following unexpected fields: ['some_variables'].
         These fields are not (directly) processed by the config processing.
Start file 0 = output_yaml/multi.fits
File 0 = output_yaml/multi.fits: time = 8.719869 sec
Done building files
```

**Comment by rmandelb** [comment]
Yes, that sounds good.
