### ISSUE TITLE
Can we get rid of wmult?

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#810]
I'm working on #799 to reorganize how the draw commands work in order to provide the hooks for the sensor effects we want for LSST, and it occurs to me that the wmult parameter is a bit arcane, and is probably rarely (never?) used by end users.

I think it served a useful purpose when @gbernstein originally put it in, since we sometimes wanted to quickly tell GalSim to use a larger FFT size than the default.  But I think now that we have the gsparams stuff (in particular folding_threshold), that's really the more reliable way to adjust the behavior of stepk, and thus the FFT grid size.  wmult seems like a hack that we don't need anymore.

Any objections to my removing it in the reorg?

**Comment by rmandelb** [comment]
Good idea.

**Comment by jmeyers314** [comment]
I think it's safe to remove.

**Comment by rmjarvis** [comment]
The only place anywhere in the code that used wmult other than just to check that it behaves as expected is a single test in test_interpolated.py that used wmult=5 (!) without any explanation of why it was deemed necessary.  But when I removed it the test still passes.  So presumably the various accuracy improvements we've made over the years in various places have made this parameter largely obsolete.

**Comment by esheldon** [comment]
I use it in code like this

    wmult=1.0
    dim = ii.SBProfile.getGoodImageSize(
        ii.nyquistScale(),
        wmult,
    )

Is this something that would transition naturally in the new code?

-e

On 10/8/16, Mike Jarvis <notifications@github.com> wrote:
> The only place anywhere in the code that used wmult other than just to check
> that it behaves as expected is a single test in test_interpolated.py that
> used wmult=5 (!) without any explanation of why it was deemed necessary.
> But when I removed it the test still passes.  So presumably the various
> accuracy improvements we've made over the years in various places have made
> this parameter largely obsolete.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GalSim-developers/GalSim/issues/810#issuecomment-252406258


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by rmjarvis** [comment]
Well, in your case, wmult=1, so you're not actually using it other than to conform to the requirements of the C++ call signature.  In the new version it would probably be simply:
```
dim = ii.SBProfile.getGoodImageSize(ii.nyquistScale())
```
If you wanted to use some value of wmult **other** than 1, then that would be equivalent to
```
dim = ii.SBProfile.getGoodImageSize(ii.nyquistScale()/wmult)
```

**Comment by rmjarvis** [comment]
FYI, on #799, I made `getGoodImageSize` a method of GSObject directly, so you don't have to make the C++ call directly:
```
dim = obj.getGoodImageSize(pixel_scale)
```
