### ISSUE TITLE
Add a truncation radius option to InclinedExponential profiles

### ISSUE THREAD

**Issue by brgillis** [GalSim-developers/GalSim#811]
Following up on #782, it would be useful if we could make the profiles a bit more realistic by including an option for a truncation radius (observations have shown that the disc seems to be truncated at approximately 4.5 times the scale radius).

I think Lance's code (the hankelcode.c file included in the tests as reference) already does this, so hopefully it won't be too hard to implement.

**Comment by rmandelb** [comment]
I think we should use the same conventions for defining truncation radii at the python layer as we use for truncated Sersic profiles, to avoid confusion/inconsistency.  (That�s not to say we can�t take advantage of what Lance has done, just that the bit we expose to the user should define the relevant kwargs in a way that is consistent to how truncation is done elsewhere in GalSim.)

**Comment by brgillis** [comment]
I have some time to look into this now. Unfortunately, it looks like Lance's code doesn't have an easy solution we can reapply here; it just brute-forces the Fourier transform. I haven't been able to figure out any easy or clever way to do this, so I think the only possibility is to go in a similar direction as with the Sersic profile, except with an extra operation in Fourier space to handle the fact of inclination.

This probably means that it would be more efficient to separate this into a different profile. And seeing as the exponential profile is a special case of a Sersic profile, perhaps it could be generalized a bit. My current thought is to make a new profile, called InclinedSersic, which will handle the truncation and inclination of a Sersic profile, and can be used as a truncated, inclined exponential profile if desired.

Before I go ahead with this, I'd like to check if you have any thoughts on this or alternative recommendations, @rmandelb and @rmjarvis?

**Comment by rmjarvis** [comment]
Sure.  Sounds fine to me.

**Comment by rmjarvis** [comment]
Merged via PR #843
