### ISSUE TITLE
update unhelpful error message

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#813]
Someone I am working with ran into a distinctly unhelpful error message when he tried to do something that seems like a potentially common failure mode, and this issue is for improving the error message to be more obvious.

The code in question was something like:

```
gal = galsim.Sersic(...)
psf = galsim.fits.read(filename)
gal = galsim.Convolve(gal, psf)
```

So what was missing was turning the PSF image into an InterpolatedImage.  I would expect an error message like "arguments to Convolve are not GSObjects or ChromaticObjects" or some such thing, but instead it just tried to do it's usual thing and crashed with an AttributeError because `psf` did not have a `hasHardEdges` attribute.

We can't anticipate all problems that could ever arise, but I think checking the type for inputs to Add/Convolve and raising a more obvious/useful exception if they are not among the allowed types would make sense.

**Comment by rmjarvis** [comment]
This is done on branch #799.  cf. 89f9667

**Comment by rmandelb** [comment]
Thanks!
