### ISSUE TITLE
defining H0?

### ISSUE THREAD

**Issue by rutudas** [GalSim-developers/GalSim#816]
Hi,

Can someone please point me to where GalSim defines the value of H0 (or h) and/or how we can set the value?  I am trying to use the cosmology class defined in the nfw_halo module.

There are bits of comments here and there that suggest H0 is set to 100 (km/s)/Mpc, but I can't tell for sure.  If this is the case, is there a way to change it?

Thank you!

**Comment by rmandelb** [comment]
There's no way to set the value, because all distances simply come out in units of Mpc/h given this choice of H_0=100*h km/s/Mpc, and you can set your own value of H_0 when you get the outputs.

**Comment by rutudas** [comment]
Ah yes, I see.  Thank you!

**Comment by rmandelb** [comment]
Closing #816.
