### ISSUE TITLE
Add ability to draw from arbitrary distributions in RandomWalk profile

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#821]
Currently we take the limit `nsep -> infinity` in order to draw from a Gaussian rather than actually doing a step-by-step random walk.  This is a very good approximation, even for low number of steps.

Consider extending this to allow drawing from other distributions, the most natural being other surface brightness profiles.

**Comment by rmjarvis** [comment]
It occurs to me that you could probably do this for any photon-shootable profile by shooting npoints photons and use the (x,y) values as the locations of the knots.  This functionality is accessible in python now in branch #799.

So the code would look something like this:
```
ud = UniformDeviate(rng)
photons = knot_profile.SBProfile.shoot(npoints, ud)
self._points = np.array([ photons.getX(i), photons.getY(i) for i in range(npoints) ])
```
Currently, the PhotonArray class doesn't have accessors for the x,y arrays, but we could add that to improve the efficiency.  But that's the gist of the idea anyway.

**Comment by esheldon** [comment]
That's pretty cool.

When #799 gets merged, lets revisit.  It should be easy to implement from there.

**Comment by rmjarvis** [comment]
Done.  #973
