### ISSUE TITLE
Add raytracing mode for realistic atmospheric PSFs.

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#824]

**Comment by jmeyers314** [comment]
Here's an example comparing fft mode to photon shooting mode for an optical psf.

![psf_comparison](https://cloud.githubusercontent.com/assets/3650485/20225412/2c211420-a811-11e6-9d35-65a83e4afc53.png)

**Comment by jmeyers314** [comment]
Left is FFT-mode, Right is photon-shooting mode with the refractive approximation.

**Comment by jmeyers314** [comment]
I've been thinking more about how to properly delay computation for atmospheric PSFs and also making an intuitive API for this.  Currently, the way to draw multiple PSFs corresponding to the same atmosphere over the same time interval (but at different field angles) is something like this:

```python
atm = function_to_make_atmosphere()
thetas = function_returning_field_angles_of_interest()
psfs = atm.makePSF(..., theta=thetas)  # returns list of PSFs

for psf, gal in zip(psfs, gals):
    obj = galsim.Convolve(psf, gal)
    obj.drawImage(...)
```

Note that this is different than:
```python
atm = function_to_make_atmosphere()
thetas = function_returning_field_angles_of_interest()
psfs = []
for theta in thetas:
    psfs.append(atm.makePSF(..., theta=theta)

for psf, gal in zip(psfs, gals):
    obj = galsim.Convolve(psf, gal)
    obj.drawImage(...)
```

since the latter increments the clock each time `makePSF` is called.  I think it may be more intuitive, however, to have these two code snippets perform the same computation.  To make the latter efficient, I also think we need to delay the actual computation of the PSF to drawImage (currently all the Fourier optics math occurs at initialization).  For photon-shooting, I think this has more-or-less already been accomplished by pulling `SBProfile.shoot()` into the python layer and overriding `PhaseScreenPSF.shoot()`.  I guess something similar could be accomplished for FFT-mode by pulling `SBProfile.drawK()` into the python layer and adding a custom `PhaseScreenPSF.drawK()`?

For boiling atmospheres, where the outer loop ought to be time and the inner loop the object, I think we should mark, in `makePSF`, which PSFs should be computed in FFT-mode.  The first `drawImage(method='fft')` would then trigger Fourier-optics computation for all PSFs currently attached to the `atm` object and marked `fft=True`.  Marked PSFs could still be drawn using photon-shooting, I think, and maybe unmarked PSFs could even still be drawn in FFT-mode, they just wouldn't trigger the time-saving outer-loop = time, inner-loop = PSF computation.

We'd need to think carefully about how to track the atmospheric clock for all of this.  Currently the clock advances for each call to `makePSF`.  Two mutually exclusive potential improvements may be

- Having the user explicitly manage the clock with `atm.advance()`, `atm.rewind()`, `atm.reset()`.  Note that `rewind` wouldn't be available for a boiling atmosphere.
- Passing a `t_start` argument to `makePSF` indicating the starting clock time for each PSF.

**Comment by rmjarvis** [comment]
> I guess something similar could be accomplished for FFT-mode by pulling SBProfile.drawK() into the python layer and adding a custom PhaseScreenPSF.drawK()?

Pulling `drawK` into the python layer would be very simple (much simpler than shoot was, that is).  Nothing in the C++ layer calls drawK, so you could change the couple places in gsobject.py that calls `prof.SBProfile.drawK` to call `prof.drawK` instead and override it for PhaseScreenPSF.

> Passing a t_start argument to makePSF indicating the starting clock time for each PSF.

Wouldn't the typical case be that t_start = 0 for all PSFs?  If so, this seems much simpler from a user's standpoint.

**Comment by jmeyers314** [comment]
>Pulling drawK into the python layer would be very simple

Great.  Will do then.

>Wouldn't the typical case be that t_start = 0 for all PSFs?

Yep.  That would definitely be the default setting.

**Comment by jmeyers314** [comment]
I think I've got this mostly working now.  The remaining piece is shooting multiple PSFs through a boiling atmosphere.  There's a minor(?) design problem with this:  when looping over both PSFs and time, it's preferable to make the time loop the outer loop when boiling, since boiling updates are slow and we should aim to do as few as possible.  The tricky bit is figuring out how to handle the `rng` for this case.  Currently, the `rng` is passed directly to `shoot` from `drawImage(method='phot')`.  I'd like to set the code up to compute all pending PSF `PhotonArray`s during the first call to `drawImage` for any of the pending PSFs though, which means I need to know all PSF `rng`s at the time of the first PSF `drawImage`.  One possible solution is to specify `rng` during initialization of the `PhaseScreenPSF` instead of in `drawImage`.

I.e., old version:

```
psf1 = atm.makePSF(**stuff)
psf2 = atm.makePSF(**stuff)
psf1.drawImage(**other_stuff, rng=rng1)
psf2.drawImage(**other_stuff, rng=rng2)
```

new version:
```
psf1 = atm.makePSF(**stuff, rng=rng1)
psf2 = atm.makePSF(**stuff, rng=rng2)
psf1.drawImage(**other_stuff)  # computes both PhotonArrays
psf2.drawImage(**other_stuff)
```

I'm not sure what other pieces of code this would break though, and we'd presumably want to unify this API across other `GSObject`s, which would be a bit of a pain.  

Another possible solution could be to just ignore `rng` (maybe configurably?) on calls to `drawImage` when the object's `PhotonArray` has been precomputed during an earlier call to `drawImage`.

Or maybe the efficient looping doesn't happen automatically, but only via a special function?  I.e., 

```
precomputePhotonArrays([psf1, psf2], [rng1, rng2])
```

Thoughts?

**Comment by rmjarvis** [comment]
I don't think you can efficiently precompute the photon arrays, since you won't typically know how many photons to shoot.  This is (typically) based on the galaxy flux, which isn't necessarily a trivial quantity that would be known in advance.

However, I don't think we want the rng for the boiling to be associated with the object anyway.  Shouldn't that use the rng associated with the Atmosphere?  i.e. the same rng that was originally used to set up the random realization of the atmosphere in the first place?

Using an rng associated with an object means that you will get different boiling realizations depending on which object asks for that time step first.  Which won't necessarily be deterministic if we want this to work in a multiprocessing context.

Of course, I may very well be completely misunderstanding something, so please correct me if so.

**Comment by jmeyers314** [comment]
>This is (typically) based on the galaxy flux, which isn't necessarily a trivial quantity that would be known in advance.

Right.  Forgot about those pesky galaxies...

>However, I don't think we want the rng for the boiling to be associated with the object anyway. 

Agreed.  I meant just meant the rng passed to `shoot` (say, to randomly sample the pupil plane).  The rng that boils the atmosphere is still separate.  As you say, though, n_photons is also a problem.

I guess I'll implement things the slow way here, and leave efficient looping for a future issue.  In principle, I think it should still be possible to loop efficiently, just not in a way that's easily compatible with the current API.  We'd have to do something like delay all work until the Image array is accessed, which sounds tricky...

**Comment by rmjarvis** [comment]
This was merged a while ago now.  #847
