### ISSUE TITLE
Implement random choice method of BaseDeviate

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#825]
Pick items from a list, with replacement.  Bonus feature: pick items congruently from multiple lists.

**Comment by rmandelb** [comment]
@jmeyers314 - this is all done with #787 except I didn't make it a method of BaseDeviate.  Should I close anyway, or is that something you're still interested in?

**Comment by jmeyers314** [comment]
Feel free to close.  I think this addresses everything I had in mind.

**Comment by rmandelb** [comment]
Closing #825.
