### ISSUE TITLE
FindAdaptiveMoments output depends on ordering of input image array

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#833]
While comparing galsim optical PSFs to Aaron Roodman's donutlib optical PSFs, I noticed that visually consistent images were giving inconsistent HSM measurements.  I believe the problem is related to the ordering (FORTRAN vs. C) of the numpy arrays wrapped by galsim.Image.  For example:

```python
import numpy as np
import galsim

gal = galsim.Gaussian(sigma=0.5).shear(g1=0.1)
img = gal.drawImage(nx=32, ny=32, scale=0.2)
print(galsim.hsm.FindAdaptiveMom(img).observed_shape)
# galsim.Shear(g1=0.0986737815706,g2=-7.749890904e-18)

# Transpose the image, which should just flip the sign of g1.
# Note, though, that this changes the ndarray from C-ordering to FORTRAN-ordering.
img2 = galsim.Image(img.array.T, scale=img.scale)
print(galsim.hsm.FindAdaptiveMom(img2).observed_shape)
# galsim.Shear(g1=-3.65148834574e-16,g2=-0.609263416273)  #  huh?

# Restore C-ordering without changing the logical contents of the ndarray
img3 = galsim.Image(np.ascontiguousarray(img2.array), scale=img2.scale)
print(galsim.hsm.FindAdaptiveMom(img3).observed_shape)
# galsim.Shear(g1=-0.0986737815706,g2=-3.6084271443e-18)  # That's better

# Verify that FORTRAN-ordering was inducing the problem.
img4 = galsim.Image(np.asfortranarray(img3.array), scale=img3.scale)
print(galsim.hsm.FindAdaptiveMom(img4).observed_shape)
# galsim.Shear(g1=-3.65148834574e-16,g2=-0.609263416273)
```

This may not be a problem for images created by drawImage(), but clearly can become a problem for images created directly from an ndarray.

**Comment by rmjarvis** [comment]
I suspect that's new from my changes in #799.  I think before, if the array wasn't C-contiguous, we recast it (ie. allocated new memory) as a C-contiguous array.  In #799, I added code to allow the Image class to work with non-unit stepped arrays (mostly so cimage.real and cimage.imag didn't require copying), but probably there is something in the HSM code that implicitly assumes C-contiguousness.

So I'll take a look and try to fix it.  The above is a good start for a unit test for this.
