### ISSUE TITLE
Various tests failing on master branch

### ISSUE THREAD

**Issue by brgillis** [GalSim-developers/GalSim#845]
Various tests are failing for me on the master branch. I've tested on two different machines, and get the same results. I've attached a log of the tests. For some reason, these aren't showing as failures with Travis, though.

[testlog.txt](https://github.com/GalSim-developers/GalSim/files/649643/testlog.txt)

**Comment by rmandelb** [comment]
What numpy version?
Generally a discrepancy between your system and Travis means different versions of some dependency.

**Comment by brgillis** [comment]
The machine I used for this log is version 1.7.1, and the other it failed on is 1.8.2

**Comment by rmandelb** [comment]
Hmmm, I think numpy version 1.7 is 3 years old or so.  It wouldn�t surprise me if none of our machines used for testing has that version.

**Comment by rmjarvis** [comment]
OK, I can reproduce this by rolling back to old versions of a bunch of things.  I'll take a look at whether the tests ought to be changed to allow these numerical differences or if we should just require a newer numpy version than this.

**Comment by rmjarvis** [comment]
@brgillis Try branch #845.  If it works for you, I'll make a PR.

**Comment by brgillis** [comment]
@rmjarvis Everything passes now for me (on numpy v1.7.1).

**Comment by rmjarvis** [comment]
Closed via #846
