### ISSUE TITLE
Drop support for gcc < 4.3

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#849]
Does anyone still use a machine that has gcc older than 4.3 as the default compiler?  

4.1.2 used to be fairly common, but I can't even find a machine that has it installed at all, much less has it as the default compiler.  So is there anyone who anticipates needing to install GalSim using gcc 4.1, or any other release prior to 4.3?

The reason I'm asking specifically is that one of the easier steps along the path to ridding ourselves of boost will be to switch from using `boost::shared_ptr` to `std::tr1::shared_ptr`.  gcc 4.3 is when they transitioned to making that relatively painless.

I was planning to also try to make that work with gcc 4.1.2 where the requisite includes are somewhat different, but I can't find a machine to test that on.  So I'm hoping I can just use the newer API and not worry about it.

**Comment by rmandelb** [comment]
No issue with this on the linux machine I use.

Question: is there any concern with clang versions on a Mac and/or do I need to worry about the relation between clang and gcc?

**Comment by jmeyers314** [comment]
No problem from me.  The oldest gcc I use is 4.4.7.

**Comment by rmjarvis** [comment]
The clang I have on my laptop is LLVM 7.0.2 and that works just fine for the shared_ptr thing I'm planning to do.  Not sure about older versions.

**Comment by rmjarvis** [comment]
Since no one shouted about this, I'm assuming this is not a problem for anyone.  

I think everyone pretty much has access to 4.4.  The current plan (being implemented on the noboost branch) is to keep things working for gcc < 4.8 the way they are now, but have a `python setup.py install` installation that works with gcc 4.8+ (and clang).  This will give *most* people the ability to `pip install galsim`, but preserve the possibility of installing on legacy systems with 4.4.

**Comment by esheldon** [comment]
I'm not sure of the statement that *most* people will be ok with this.  I think a lot of people that use galsim in production are on redhat ahd have 4.4.  I can say, as one such person, I would be thrilled to use the noboost version and a setup.py

**Comment by rmjarvis** [comment]
But you use Anaconda.  And Anaconda has its own gcc that is 4.8+, so you should be fine.  (You can check by doing `pip install pybind11 --user`.  If it works, you're good.)

**Comment by esheldon** [comment]
I have run into issues in the past installing packages using setup.py where the compiler used is the system compiler 4.4

why is that pip install the definitive test?

**Comment by esheldon** [comment]
Also, I'm n ot sure why you say "anaconda has its own gcc".  My install does not have its own gcc.  Perhaps that is true only in certain install configurations.

**Comment by rmjarvis** [comment]
Hard to say.  Maybe it's not.  But I'm pretty sure if you have Anaconda, you can install things with it that use c++11 even if your system gcc is 4.4.  It's possible that there is more involved than just what I wrote though.  I have systems like that, so I'll at least be able to figure out how to make it work before releasing v2.0.

**Comment by rmjarvis** [comment]
(e.g. you might need to do `conda install gcc` first.)

**Comment by esheldon** [comment]
That sounds like it could be a real problem, having to shuffle around gcc versions.  This is exactly where I have had problems in the past.
