### ISSUE TITLE
Use basestring instead of str

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#851]
Experienced a tricky issue trying to run through the examples yesterday on an officemate's newly-installed copy of GalSim:  

`Bandpass`, (via demo12) failed to recognize that one of the filter filenames was, in fact, a string.  The issue turned out to be that his home directory as returned by `os.path.split(__file__)` happened to be returned as a `unicode` instance instead of a `str` instance.  

(Actually, it was weirder than that, as it only came back as `unicode` when running through `ipython`, but came back as `str` when run through `python` (2.7).  Took a long time to debug that!) 

The unicode caused the `Bandpass.py` expression: `isinstance(self._orig_tp, str)` to return False, and so Bandpass fell through to initialize `self._tp` as a lambda expression with the unicode as part of the expression.  

The error message was not helpful.  (I believe it was something about blue_limit and/or red_limit not being defined).

I think part of the solution is to add `from past.builtins import basestring`, and then check against basestring instead of str.

We should also try to figure out a more helpful error message, and look through the rest of the code to see if there are any more places where we should replace str with basestring.

**Comment by rmjarvis** [comment]
> from past.builtins import basestring

That's fine with me.  We used to use basestring in a number of places, but in the conversion to python 3 support, I switched them to str and didn't see any problems.  I guess cases like this are probably why people recommend using basestring instead.  All my file systems apparently use regular ascii encoding, so it never showed up.

I suspect any place we do `isinstance(blah, str)` probably ought to switch to using `past.builtins.basestring`.
