### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#859]
master and v1.4.2 both test fine for me under python 3.6.  We should update INSTALL.md to say so.  Should we add py3.6 to travis-ci?

Also, README.md says v1.4.1 is latest release, but I think this should be v1.4.2.  

Finally, would this also be a good time to update copyrights to 2017?  Someone has a script for that, right?

**Comment by rmandelb** [comment]
I think that if we want to update INSTALL.md to mention python 3.6, we should definitely add it to travis (so we can make sure this statement is continuously true and not just instantaneously :)

README.md: that sounds like we just missed updating this and it should be fixed right away.

Mike has the copyright updating script.

**Comment by rmjarvis** [comment]
> Mike has the copyright updating script.

It's actually [here](https://github.com/GalSim-developers/GalSim/blob/master/devel/updatecr), just for the record, but I volunteer to do it, since I've done it in the past.

**Comment by rmjarvis** [comment]
> We should update INSTALL.md to say so. 

Done on master.

> Should we add py3.6 to travis-ci?

Done by Josh via #858.

> Also, README.md says v1.4.1 is latest release, but I think this should be v1.4.2.

Done on releases/1.4

> Finally, would this also be a good time to update copyrights to 2017? Someone has a script for that, right?

Done on master.
