### ISSUE TITLE
assert failure in galsim::SBProfile::drawShoot function

### ISSUE THREAD

**Issue by jchiang87** [GalSim-developers/GalSim#866]
Running the `.drawImage` method, I am occasionally getting the following failure:
```
$ python drawImage_test_case.py 
galsim.__version__: 1.4.1

python: src/SBProfile.cpp:1005: double galsim::SBProfile::drawShoot(galsim::ImageView<T>, double, galsim::UniformDeviate, double, double, bool, bool) const [with T = float]: Assertion `!add_to_image' failed.
Aborted (core dumped)
$
```
The `drawImage_test_case.py` script and pickled inputs are attached.
[drawImage_assert_fail.zip](https://github.com/GalSim-developers/GalSim/files/778149/drawImage_assert_fail.zip)

**Comment by rmandelb** [comment]
Hmmmm.  I reproduce this on my  system for v1.4.1 and v1.4.2, but not the latest version on the master branch.

**Comment by rmjarvis** [comment]
Yep.  I figured out the problem.  And why it works on the master branch.  PR soon, just writing up a unit test for it now.

**Comment by rmandelb** [comment]
Cool.  If Jim needs a tagged version, should we make v1.4.3?

**Comment by jchiang87** [comment]
This will be rolled into the LSST sims distribution, so a tagged version would be great.  Thanks!
Pinging @danielsf

**Comment by rmjarvis** [comment]
Yep.  I was planning on making the PR into releases/1.4 with the aim of rolling a 1.4.3 with the fix.  Then we can cherry-pick the unit test over to master.

**Comment by danielsf** [comment]
Excellent.  I will package 1.4.3 up for LSST when it comes out,@jchiang87.  Thanks, @rmjarvis.

**Comment by rmjarvis** [comment]
v1.4.3 is tagged with this fix.

https://github.com/GalSim-developers/GalSim/releases
