### ISSUE TITLE
Error in documentation of demo11.yaml

### ISSUE THREAD

**Issue by NiallMac** [GalSim-developers/GalSim#868]
Lines 204-207 are commented out:

    # image_pos :
    #     type : XY
    #     x : { type : Random , min : 0 , max : xsize-1 }
    #     y : { type : Random , min : 0 , max : ysize-1 }

but presumably are there to demonstrate how one would scatter galaxies within some range different to the default (e.g. in my case I did not want galaxies within some number of pixels of the edge of the image). The syntax there is not correct however - an eval is required for the 'xsize-1', and xsize would need to be defined.

**Comment by rmjarvis** [comment]
I addressed this on branch #865, currently in PR (#872).
