### ISSUE TITLE
Jupyter kernel crashes when importing galsim

### ISSUE THREAD

**Issue by hsnee** [GalSim-developers/GalSim#870]
Hello, I'm a new grad student at Carnegie Mellon working with @rmandelb on testing the psf modelling errors for lsst. 

I installed galsim and it's working fine but when I try to use it in a jupyter notebook, every time I import it, the kernel crashes immediately and restarts. I'm on macOS Sierra 10.12.3, using Python 2.7.9 (Apple's build). 

I tried debugging it with `ipdb`, but it didn't provide any information at all. Any ideas what may be causing this?

**Comment by rmjarvis** [comment]
It's hard to say without more information, but it sounds like there is some kind of mismatch in either the python kernel or the search path between Jupyter and the command line Python.  I found [this](https://github.com/conda/conda/issues/2953) discussion on an Anaconda issue page that mentions some of the kinds of issues that can arise.  Not sure if any of that is relevant here, but maybe reading through it will give you some things to try.

Also, maybe worth trying a different Jupyter platform.  e.g. [Pineapple](https://nwhitehead.github.io/pineapple/)  Not sure which Jupyter you are using, but I typically use the `pip install jupyter` version, which should use the same Python version as pip, which by default is your system Python.  So if you did something different, maybe try the pip version to see if that works better.

**Comment by hsnee** [comment]
Thanks @rmjarvis, that helped a lot -- It was indeed a mismatch problem, both the python version and path were mismatched. It's working now after pointing it to the appropriate paths. I should probably do something about having 5 coexisting python versions installed...

**Comment by rmjarvis** [comment]
Thanks for the update.  Glad it's working now.  I similarly have quite a few different Pythons installed on my laptop so I can test code against each of them.  But it means sometimes things get completely borked and it's not always obvious how to get back to a working state...
