### ISSUE TITLE
Use fast exp, fast inverse sqrt, etc. when possible

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#873]
@esheldon and I have been discussing some ways that the k-space rendering in GalSim could be sped up.  One of the ideas is to use faster exp and invsqrt functions when possible.  We have parameters xvalue_accuracy and kvalue_accuracy that tell how accurate we need to be.  I suspect in many cases, we can use quick and dirty versions of various functions that are faster than the native functions.  

e.g. the famous [Quake inverse sqrt](https://www.beyond3d.com/content/articles/8/) (although the [SSE inverse sqrt is probably faster nowadays](http://stackoverflow.com/questions/15175654/sqrt-vs-rsqrt-vs-sse-mm-rsqrt-ps-benchmark)).

Another thought I had was possibly using SSE commands in the fillKValue functions.  Some of the profile types may be amenable to this.  Particularly Exponential if we're able to use rsqrtps.

Anyway, this issue is basically to profile and optimize the drawK operations for Exponential, Spergel, and maybe a few other classes.

**Comment by esheldon** [comment]
Some examples
```C

#include <stdio.h>
#include <math.h>
#include <xmmintrin.h>


static inline void sse_rsqrt( float * restrict pOut, float * restrict pIn )
{
   __m128 in = _mm_load_ss( pIn );
   _mm_store_ss( pOut, _mm_rsqrt_ss( in ) );
   // compiles to movss, movaps, rsqrtss, mulss, movss
}

// plus one newton raphson step
static inline void sse_rsqrt_nr( float * restrict pOut, float * restrict pIn )
{
    const float threehalfs = 1.5F;
    float y, x2;

    x2 = *pIn * 0.5F;

    __m128 in = _mm_load_ss( pIn );
    _mm_store_ss( &y, _mm_rsqrt_ss( in ) );

    *pOut  = y * ( threehalfs - ( x2 * y * y ) );

    // compiles to movss, movaps, rsqrtss, mulss, movss
}


// straight from wikipedia
static inline float carmack_rsqrt( float number )
{
    long i;
    float x2, y;
    const float threehalfs = 1.5F;

    x2 = number * 0.5F;
    y  = number;
    i  = * ( long * ) &y;                       // evil floating point bit level hacking
    i  = 0x5f3759df - ( i >> 1 );               // what the fuck? 
    y  = * ( float * ) &i;
    y  = y * ( threehalfs - ( x2 * y * y ) );   // 1st iteration
    //y  = y * ( threehalfs - ( x2 * y * y ) );   // 2nd iteration, this can be removed

    return y;
}

// with extra NS step
static inline float carmack_rsqrt_ns2( float number )
{
    long i;
    float x2, y;
    const float threehalfs = 1.5F;

    x2 = number * 0.5F;
    y  = number;
    i  = * ( long * ) &y;                       // evil floating point bit level hacking
    i  = 0x5f3759df - ( i >> 1 );               // what the fuck? 
    y  = * ( float * ) &i;
    y  = y * ( threehalfs - ( x2 * y * y ) );   // 1st iteration
    y  = y * ( threehalfs - ( x2 * y * y ) );   // 2nd iteration, this can be removed

    return y;
}


int main(int argc, char** argv)
{

    float x = atof(argv[1]);

    float r, rc, rc2, rsse, rssenr;


    r = 1.0/sqrt(x);
    rc  = carmack_rsqrt(x);
    rc2 = carmack_rsqrt(x);

    sse_rsqrt(&rsse, &x);
    sse_rsqrt_nr(&rssenr, &x);

    printf("carmack 1 nr: %g %g %.16g\n", r, rc, (double)rc/(double)r-1.0);
    printf("carmack 2 nr: %g %g %.16g\n", r, rc, (double)rc/(double)r-1.0);
    printf("sse:          %g %g %.16g\n", r, rsse, (double)rsse/(double)r-1.0);
    printf("sse:    1nr   %g %g %.16g\n", r, rssenr, (double)rssenr/(double)r-1.0);


}
```

**Comment by esheldon** [comment]
note I got the sse stuff from here:  http://stackoverflow.com/questions/1528727/why-is-sse-scalar-sqrtx-slower-than-rsqrtx-x

**Comment by esheldon** [comment]
It turns out there were bugs; need to use 32 bit integer but they were using long, which on x86_64 is 8 byte, which caused havoc
```C
#include <stdio.h>
#include <math.h>
#include <stdint.h>
#include <xmmintrin.h>


static inline void sse_rsqrt( float * restrict pOut, float * restrict pIn )
{
   __m128 in = _mm_load_ss( pIn );
   _mm_store_ss( pOut, _mm_rsqrt_ss( in ) );
}

// plus one newton raphson step
static inline void sse_rsqrt_nr( float * restrict pOut, float * restrict pIn )
{
    const float threehalfs = 1.5F;
    float y, x2;

    x2 = *pIn * 0.5F;

    __m128 in = _mm_load_ss( pIn );
    _mm_store_ss( &y, _mm_rsqrt_ss( in ) );

    *pOut  = y * ( threehalfs - ( x2 * y * y ) );
}


float carmack_rsqrt( float number )
{
    int32_t i;
    float x2, y;
    const float threehalfs = 1.5F;

    x2 = number * 0.5F;
    y  = number;
    i  = * ( int32_t * ) &y;
    i  = 0x5f3759df - ( i >> 1 );
    y  = * ( float * ) &i;
    y  = y * ( threehalfs - ( x2 * y * y ) );

    return y;
}

// with extra newton raphson step
float carmack_rsqrt_nr2( float number )
{
    int32_t i;
    float x2, y;
    const float threehalfs = 1.5F;

    x2 = number * 0.5F;
    y  = number;
    i  = * ( int32_t * ) &y;
    i  = 0x5f3759df - ( i >> 1 );
    y  = * ( float * ) &i;
    y  = y * ( threehalfs - ( x2 * y * y ) );
    y  = y * ( threehalfs - ( x2 * y * y ) );

    return y;
}



int main(int argc, char** argv)
{

    float x = atof(argv[1]);

    float r, rc, rc2, rsse, rssenr;

    printf("sizeof(long): %d\n", sizeof(long));

    r = 1.0/sqrt(x);
    rc  = carmack_rsqrt(x);
    rc2 = carmack_rsqrt_nr2(x);

    sse_rsqrt(&rsse, &x);
    sse_rsqrt_nr(&rssenr, &x);

    printf("carmack 1 nr: %g %g %.16g\n", r, rc, (double)rc/(double)r-1.0);
    printf("carmack 2 nr: %g %g %.16g\n", r, rc2, (double)rc2/(double)r-1.0);
    printf("sse:          %g %g %.16g\n", r, rsse, (double)rsse/(double)r-1.0);
    printf("sse:    1nr   %g %g %.16g\n", r, rssenr, (double)rssenr/(double)r-1.0);


}
```

**Comment by esheldon** [comment]
I ran a fitting routine with and without the fast inverse sqrt for
Exponential, and it makes no clear difference.  This is just generating lots
of Exponential K images over and over with different parameters as the fitter
runs.

The profiler does indicate that `drawKImage` is the dominant routine, but
apparently the `sqrt` buried in the Exponential is not the cause.  The
profiler can't dig into the C++ to profile in more detail (see below).

I don't really know all what is going on in `drawKImage` but a quick check
shows that the time spent before calling `drawK` takes about 2.6 times longer
than `drawK` itself, so maybe there is something more that can be done here, I
don't know.

Here is a breakdown

```
seconds per call numbers

parameter checking
7.249358e-05

figuring out scale/dk etc.
6.819001e-06

real_prof stuff 
2.428259e-05

prepping the image (if re is not None ...)
6.148104e-05

drawK
6.125523e-05
```



```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    41862    3.697    0.000    9.909    0.000 gsobject.py:1750(drawKImage)
     2000    1.773    0.001    1.990    0.001 gsobject.py:1415(drawFFT)
     1000    1.442    0.001   18.018    0.018 {scipy.optimize._minpack._lmdif}
     2000    1.385    0.001    1.385    0.001 {ngmix._gmix.em_run}
    38862    1.025    0.000   18.206    0.000 gsfit.py:113(_calc_fdiff)
    89724    0.945    0.000    1.547    0.000 transform.py:119(__init__)
   168448    0.933    0.000    1.692    0.000 utilities.py:108(parse_pos_args)
    39862    0.823    0.000    0.823    0.000 gsfit.py:484(_complex_multiply)
    47862    0.773    0.000    1.410    0.000 image.py:1420(Image_mul)
    38862    0.673    0.000    1.059    0.000 joint_prior.py:1151(fill_fdiff)
```

**Comment by esheldon** [comment]
I should also point out that `drawK` itself does not speed up noticeably using the fast exp

**Comment by esheldon** [comment]
the reason I didn't see a change in speed of `drawK` is that I didn't realize there were two different overloaded `fillKimage ` implementations, I only updated one.

Now the fitting code takes considerably longer because of the extra noise introduced by the noisy sqrt, so this will need some more careful work.

**Comment by esheldon** [comment]
In terms of the overhead in `drawKImage`, I was able to improve that some by moving to the new `ImageC` rather than separate real and imag parts.

The overhead is still  larger than the underlying `drawK`  itself

**Comment by esheldon** [comment]
The two biggest overheads are

- the stuff with `real_prof` 
- `setCenter`!

**Comment by esheldon** [comment]
The overhead comes down to this for my example
```python
   dk = kmodel.scale
   dx = numpy.pi/( max(kmodel.array.shape) // 2 * dk )

   real_prof = galsim.PixelScale(dx).toImage(gal)
   kmodel = real_prof._setup_image(
       kmodel, None, None, None, False, numpy.complex128,
       odd=True,wmult=1.0,
   )
   kmodel.setCenter(0,0)
   gal.SBProfile.drawK(kmodel.image.view(), dk)
```
In my case I know the scale I want; can any of this be removed in that case?

**Comment by rmjarvis** [comment]
A few other places, we've introduced variants that have a leading underscore to skip the normal overhead.  e.g. `_Image(array, bounds, wcs)` creates an image with those values with very little overhead.  Similarly, `_Transform` is a quicker version of Transform when you don't want to do the normal checks.

So I think it would be very reasonable to add a `_drawKImage` that does very little besides call out to `gal.SBProfile.drawK`.  We can look into what the most bare bones version would be.

**Comment by esheldon** [comment]
Note, I've already got the complex image I'm writing into as well.

**Comment by rmjarvis** [comment]
I didn't try it out, but I think this would be sufficient:
```
    def _drawKImage(self, image, add_to_image=False):
        """Equivalent to drawKImage(image, add_to_image), but without the normal sanity checks
        or the option to create the image for you.
        
        The input image must be provided as an ImageC instancec, and the center should be set to
        coordinate (0,0).  This is not checked (in the interest of efficiency).

        @param image        The ImageC onto which to draw the k-space image. [required]
        @param add_to_image Whether to add to the existing images rather than clear out
                            anything in the image before drawing.  [default: False]

        @returns image
        """
        if not add_to_image: image.setZero()
        self.SBProfile.drawK(image.image, image.scale)
        return image
```

**Comment by esheldon** [comment]
This doesn't seem to work for me, it creates the wrong profile.  It does work if I do the `real_prof` steps beforehand.

**Comment by rmjarvis** [comment]
I made a simple script to try to work on this in devel/time_expon_k.py.  It just uses scipy.minimize to fit an Exponential by drawing it in k space.  Mostly I just wanted a plausible wrapper around calls to drawKImage to see how it behaves in a realistic scenario.

Switching to the `_drawKImage` function does speed things up a bit, although it wasn't the dominant part of the running time.
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      723    0.127    0.000    0.169    0.000 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1750(drawKImage)

```
->
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      723    0.120    0.000    0.129    0.000 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1886(_drawKImage)
```
The overhead was around 25%.  Worth doing, but it wasn't exactly prohibitive.  

So that tells me that this script might not be exactly representative of your use case.  Could you try modifying it to be closer to the scenario that you are doing so I have something more representative to hack on?

**Comment by rmjarvis** [comment]
Branch '#873', btw.

**Comment by rmjarvis** [comment]
Two updates.
1. You can already gain some speed by using kvalue_accuracy=1.e-3
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      718    0.086    0.000    0.095    0.000 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1886(_drawKImage)
```
(cf. 0.129 before)

2. I don't think the fast sqrt will gain us much.  I ran timings of the 4 invsqrt functions you listed above along with normal sqrt (both float and double varieties):
```
$ ./time_invsqrt 
carmack 1 nr: 11.459 msec, max error = 0.00169283
carmack 2 nr: 12.102 msec, max error = 4.35114e-06
sse:          8.642 msec, max error = 0.000254273
sse 1 nr:     9.868 msec, max error = 1.19209e-07
1./sqrt(x):   10.313 msec, max error = 0
1./sqrtd(x):  10.64 msec, max error = 0
```
(This is called devel/time_invsqrt.c on this branch.)  So not much to be gained over the current double precision 1./sqrt(x) that we currently do.  At least not at accuracy levels that we would probably want to tolerate.

**Comment by esheldon** [comment]
I had come to the same conclusion for the fast sqrt, and for fitting it was causing so much noise that the fitting was actually taking much longer.

**Comment by rmjarvis** [comment]
One thing that I think could help would be to do real sse operations, which can do 4 at a time.  Here is an updated output that includes tests of doing 4 at once with sse:
```
$ time_invsqrt 
carmack 1 nr: 0.88795 msec, max error = 0.00169283
carmack 2 nr: 1.15905 msec, max error = 4.35114e-06
sse:          0.7422 msec, max error = 0.000254273
sse 1 nr:     0.9266 msec, max error = 1.19209e-07
1./sqrt(x):   0.60455 msec, max error = 5.96046e-08
1./sqrtd(x):  1.24985 msec, max error = 0
sse4 rsqrt:   0.1566 msec, max error = 0.000254273
sse4 1 nr:    0.4284 msec, max error = 1.19209e-07
sse4 invsqrt: 0.26825 msec, max error = 5.96046e-08
```
The last one just does a real 1/sqrt(x), but with sse commands, not the approximate rsqrt.

**Comment by rmjarvis** [comment]
That was fun.  I hadn't done SSE stuff in a while.  Kind of like writing assembler.  Not that I ever actually learned assembler, but it has that kind of low level feel to the code.  :)

Anyway, here's what I get when I use complex<float> images with a custom SSE implementation for the inner loop of fillKImage.
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      538    0.019    0.000    0.023    0.000 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1903(_drawKImage)
```
It now takes less time than whatever the internals of scipy.optimize are doing.  (The total running time for the fitting function is 0.095 sec.)

**Comment by rmjarvis** [comment]
@esheldon I finished adding SSE stuff for SBSpergel.  It was also helpful to do some SSE specialization for the centroid bit in SBTransform, since it involves multiplying 3 complex numbers, and complex multiplication with the std library is horribly inefficient.  (They way they write the op* function for the complex class makes it really hard for the compiler to figure out how to vectorize it.)

Here is a summary of the timings in the time_expon.py function (which now tests Exponential, Spergel and Sersic):

Exponential:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      860    0.218    0.000    0.243    0.000 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1957(_drawKImage)
```
Spergel nu = 0.5:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      752    0.320    0.000    0.345    0.000 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1957(_drawKImage)
```
Sersic n=1
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1207    1.717    0.001    1.753    0.001 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1957(_drawKImage)
```
Those are all really Exponential, but done in the different ways (i.e. Spergel is doing exp(-1.5 log(ksqp1)) and Sersic is doing a lookup table interpolation).

On master, here is what these look like:
Exponential:
```
     1201    2.271    0.002    2.443    0.002 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1855(drawKImage)
```
Spergel:
```
     1200    3.802    0.003    3.971    0.003 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1855(drawKImage)
```
Sersic:
```
     1200    2.885    0.002    3.055    0.003 /Users/Mike/lib/python2.7/site-packages/galsim/gsobject.py:1855(drawKImage)
```
So around an order of magnitude speed up for the first two.  Not to mention the Python-layer edits I made that let you avoid some of the regular sanity checks and such by adding the leading underscore to some function names.  That helps speed things up a bit too.

Anyway, please check it out and see how things go when interfacing with your code.  See if there are any other tall poles that should be tackled here before making a PR.

**Comment by esheldon** [comment]
the current  of branch #837 has a bug for my gcc `(g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609)`
```C++
src/Image.cpp:908:15: error: ‘memset’ was not declared in this scope
         memset(this->getData(), 0, this->getNElements() * sizeof(T));
```

**Comment by rmjarvis** [comment]
Sorry.  Try it now.

**Comment by esheldon** [comment]
that works, thank you.

For my test application (simulating bulge+disk+knots and then fitting a spergel profile with free `nu`) I'm seeing an overall speed up of 50%, nice.

for the fitting part in k space I see about a 10% improvement.  My draw for each model currently looks like this

```python
                                                                                                                                                                                                                                               
                real_prof = galsim.PixelScale(dx).toImage(gal)                                                                                                                                                                                 
                kmodel = real_prof._setup_image(                                                                                                                                                                                               
                    kmodel, None, None, None, False, numpy.complex128,                                                                                                                                                                         
                    odd=True,wmult=1.0,                                                                                                                                                                                                        
                )                                                                                                                                                                                                                              
                kmodel.setCenter(0,0)                                                                                                                                                                                                          
                gal.SBProfile.drawK(kmodel.image.view(), dk) 
```

I did not use just `_drawK()` by itself because without the real_prof stuff I get the wrong profile.

**Comment by esheldon** [comment]
here is the output of the profiler
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      200    8.581    0.043    8.583    0.043 gsobject.py:1957(_drawKImage)
      200    0.619    0.003    0.643    0.003 interpolatedimage.py:256(__init__)
      200    0.587    0.003    0.587    0.003 {built-in method ngmix._gmix.em_run}
      200    0.431    0.002    0.431    0.002 compound.py:116(__init__)
     7024    0.377    0.000    1.147    0.000 galsimfit.py:224(_fill_models)
      100    0.175    0.002    1.625    0.016 {built-in method scipy.optimize._minpack._lmdif}
     7024    0.135    0.000    1.496    0.000 galsimfit.py:168(_calc_fdiff)
      200    0.103    0.001    0.103    0.001 {method 'normal' of 'mtrand.RandomState' objects}
    14772    0.089    0.000    0.153    0.000 transform.py:119(__init__)
     6936    0.076    0.000    0.121    0.000 joint_prior.py:1842(fill_fdiff)
    14572    0.063    0.000    0.117    0.000 utilities.py:108(parse_pos_args)
    31296    0.059    0.000    0.059    0.000 {built-in method numpy.core.multiarray.array}
      300    0.059    0.000    0.075    0.000 gsobject.py:1819(drawKImage)
     7224    0.058    0.000    0.069    0.000 base.py:1360(__init__)
      100    0.048    0.000    0.049    0.000 guessers.py:398(__init__)
    74/43    0.047    0.001    0.085    0.002 {built-in method _imp.create_dynamic}
     7436    0.044    0.000    0.049    0.000 shear.py:85(__init__)
     7136    0.044    0.000    0.057    0.000 image.py:1444(Image_imul)
     7436    0.043    0.000    0.074    0.000 shear.py:318(getMatrix)
      200    0.039    0.000    0.044    0.000 gsobject.py:1496(drawFFT_finish)

```

**Comment by esheldon** [comment]
I think the top two there are from the simulation part of this app, so can be ignored.  Note the `em_run` is also not counted in my fitting times.  The top from my fitting times comes in `_fill_models` which is dominated by the code I posted above.

**Comment by rmjarvis** [comment]
I thought you had a fixed kimage.  If the `real_prof` bit matters then it means that `kimage` is changing from the call to `setup_image`.  Print kimage before and after to see.  If you give it the right `kimage` (size, scale) at the start, then you don't need that bit.

**Comment by esheldon** [comment]
OK, it might be I'm doing something wrong somewhere, I'll look.

**Comment by esheldon** [comment]
Indeed, I had a bug. this works now.

And now the fitting is faster by 20%.  Pretty good.

**Comment by rmjarvis** [comment]
```
    14772    0.089    0.000    0.153    0.000 transform.py:119(__init__)
     7436    0.044    0.000    0.049    0.000 shear.py:85(__init__)
```
It looks like you can also save a bit more time by using the new `obj._shear(_Shear(g1 + 1j*g2))` syntax to save some of the sanity checks normally in that step.  

If you see any other Python functions that would benefit from a leading-underscore version without the kruft, let me know.  I'm not averse to adding more as appropriate.  (Maybe Add?  It looks like that's another tall-ish pole, although only on the simuluation stage I guess.)

**Comment by esheldon** [comment]
I'm having trouble compiling this branch at SLAC

```bash
file /nfs/slac/des/fs1/g/sims/esheldon/git/GalSim/SConstruct,line 1936:
        Configure(confdir = .sconf_temp)
scons: Configure: Checking for C++ header file fftw3.h... 
.sconf_temp/conftest_0.cpp <-
  |
  |#include <fftw3.h>
  |
  |
g++ -o .sconf_temp/conftest_0.o -c -O2 -std=c++98 -march=native -fno-strict-aliasing -Iinclude -I/u/ki/esheldon/local/include .sconf_temp/conftest_0.cpp
.sconf_temp/conftest_0.cpp:1: error: CPU you selected does not support x86-64 instruction set
scons: Configure: no

```

**Comment by esheldon** [comment]
forgot to say compiler version:  `g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)`

**Comment by rmjarvis** [comment]
I guess that would be from the `-march=native` flag that I added to make sure that SSE commands are enabled.  Strange.  I thought that was always supposed to work.

To see, you can try that command that failed without the -march=native piece to see if that works.  And if so, (and you want the new SSE commands to work) it would probably be worth figuring out what flag to replace it with that still keeps the SSE stuff enabled.

cf. 
```
$ gcc -Q -march=native --help=target | grep sse
  -mno-sse4                   		[disabled]
  -msse                       		[enabled]
  -msse2                      		[enabled]
  -msse2avx                   		[disabled]
  -msse3                      		[enabled]
  -msse4                      		[disabled]
  -msse4.1                    		[enabled]
  -msse4.2                    		[disabled]
  -msse4a                     		[disabled]
  -msseregparm                		[disabled]
  -mssse3                     		[enabled]
```
vs.
```
$ gcc -Q --help=target | grep sse
  -mno-sse4                   		[enabled]
  -msse                       		[disabled]
  -msse2                      		[disabled]
  -msse2avx                   		[disabled]
  -msse3                      		[disabled]
  -msse4                      		[disabled]
  -msse4.1                    		[disabled]
  -msse4.2                    		[disabled]
  -msse4a                     		[disabled]
  -msseregparm                		[disabled]
  -mssse3                     		[disabled]
```
You'll want to find something with at least sse and sse2 that works on that system.

**Comment by esheldon** [comment]
Here is what I get for that system. First the default
```
(nsim-work) [esheldon@rhel6-64k GalSim] gcc -Q -march=native --help=target | grep sse
  -mno-sse4                             [enabled]
  -msse                                 [disabled]
  -msse2                                [disabled]
  -msse2avx                             [disabled]
  -msse3                                [disabled]
  -msse4                                [disabled]
  -msse4.1                              [disabled]
  -msse4.2                              [disabled]
  -msse4a                               [disabled]
  -msseregparm                          [disabled]
  -mssse3                               [disabled]

```
now specifically enabling sse2
```
(nsim-work) [esheldon@rhel6-64k GalSim] gcc -Q -msse2 --help=target | grep sse
  -mno-sse4                             [enabled]
  -msse                                 [enabled]
  -msse2                                [enabled]
  -msse2avx                             [disabled]
  -msse3                                [disabled]
  -msse4                                [disabled]
  -msse4.1                              [disabled]
  -msse4.2                              [disabled]
  -msse4a                               [disabled]
  -msseregparm                          [disabled]
  -mssse3                               [disabled]
```

**Comment by esheldon** [comment]
compiling as so seems to have worked:
```
scons FLAGS="-O2 -std=c++98 -msse2 -fno-strict-aliasing" ...
```

**Comment by rmjarvis** [comment]
OK.  I was hoping -march=native would always enable sse2 on machines that could handle it and not on machines that don't.  I'm having trouble finding online anyone telling me a reliable compiler directive other than that one, which would do so.  (Many places recommend that to get all the available sse stuff for a particular system.)

So maybe the best solution is to have SCons try compiling with `-msse2` and if it works, go with it, otherwise don't.

**Comment by rmjarvis** [comment]
@esheldon Could you check that the recent commit correctly figures out that `-march=native` doesn't work on the SLAC machines and uses `-msse2` instead?  (None of the machines I tried this on have a problem with the march version, so I can't test this myself.)

**Comment by esheldon** [comment]
Yes I will check.

Does it work at bnl?  they are using nearly identical compilers

slac: `gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)`
bnl:  `gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3)`

**Comment by rmjarvis** [comment]
Yes.  BNL had no trouble with -march=native.  I don't think it's the compiler.  Something different about the environment.  Some places online suggest that `-march=native` fails when running in virtual machines.  I don't know if that's relevant or not.

**Comment by esheldon** [comment]
Actually, that is relevant.  Each "login node" at SLAC is actually a VM.

```
(nsim-work) [esheldon@rhel6-64k lsf] cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 1
cpu MHz         : 3058.998
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm unfair_spinlock pni cx16 hypervisor lahf_lm
bogomips        : 6117.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 1
cpu MHz         : 3058.998
cache size      : 4096 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm unfair_spinlock pni cx16 hypervisor lahf_lm
bogomips        : 6117.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

```

**Comment by esheldon** [comment]
That does work at SLAC.

Is this right though?
```
sse_flags = ['-march=native', '-msse2', 'msse']
```
Should there be a dash in that `-msse` ?

**Comment by rmjarvis** [comment]
> Should there be a dash in that -msse ?

Yes.  Thanks for catching that.

**Comment by rmjarvis** [comment]
Merge via #879
