### ISSUE TITLE
Stable RNG and Poisson noise

### ISSUE THREAD

**Issue by brgillis** [GalSim-developers/GalSim#878]
I've found an interesting issue when trying to generate simulated images with the same noise realizations. Due to the way generating Poisson noise works, it uses an indeterminate number of random values per generation, and this number depends on the lambda of the distribution. What this means is, if I take two different noise-free images and add Poisson noise to them with the same seed, the noise realizations will look completely different (even in regions where the initial images are the same).

See the attached files for two images with only slightly different galaxies, and the difference between them:
[pois_noise_diff.zip](https://github.com/GalSim-developers/GalSim/files/862244/pois_noise_diff.zip)

I'm using the CCDNoise class here, so read noise is applies entirely after Poisson noise. It should at least be possible to make read noise stable if it's generated first in this class, which is at least a partial solution. As for the Poisson noise, I'm not sure there's a perfect solution, simply due to the nature of a Poisson distribution - if a pixel has an expected extra 0.1 e- hitting it, the generated number can't simply be 0.1 more. The best ideal I can think of would be if pixels with the same value would always get the same Poisson deviate, and if the same pixel is changed between images, the change in the deviate is proportional. The former part is at least theoretically attainable, but I don't know about the latter.

A compromise might be to put in a "stable_rng" option for the CCDNoise class which would result in it using Gaussian noise for each pixel with the correct sigma. It's not quite the right distribution, but it might be good enough for many use cases.

**Comment by rmjarvis** [comment]
You're doing something wrong.  The CCDNoise class already has a stable rng.  See demo3 for an example.  It always produces the same image.

Or, for instance:
```
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import galsim
>>> gal = galsim.Exponential(half_light_radius=2.3)
>>> base_im = gal.drawImage()
>>> noise_im1 = base_im.copy()
>>> noise_im2 = base_im.copy()
>>> noise1 = galsim.CCDNoise(galsim.BaseDeviate(12345), sky_level=100, gain=2.3, read_noise=5)
>>> noise2 = galsim.CCDNoise(galsim.BaseDeviate(12345), sky_level=100, gain=2.3, read_noise=5)
>>> noise_im1.addNoise(noise1)
>>> noise_im2.addNoise(noise2)
>>> assert(noise_im1 == noise_im2)
>>> assert((noise_im1.array-noise_im2.array).sum() == 0.)
```
If you're not getting consistent results, then I suspect you are doing something wrong in your script.

**Comment by rmjarvis** [comment]
Oh.  Never mind.  You have different input images.  Yes, the noise will be different in that case.  

I think because of the splitting between Poisson and Gaussian in the Poisson part of the CCDNoise function.  I think this isn't actually necessary anymore.  The old numpy poisson generator was slow for large mean values.  But I think the version we now have in the repo has fixed that, so we could get rid of that "feature".

**Comment by rmjarvis** [comment]
Actually, that doesn't seem to be the culprit.  It seems that the boost implementation of the Poisson variate sometimes uses up more than one random number.
```
>>> p1 = galsim.PoissonDeviate(1234, mean=10)
>>> p2 = galsim.PoissonDeviate(1234, mean=20)
>>> [ p1(), p1(), p1() ]
[9, 11, 6]
>>> [ p2(), p2(), p2() ]
[17, 19, 26]
>>> p1.raw()
2256489288
>>> p2.raw()
584644678
```
The base rngs are not in sync anymore after 3 poisson draws.

But it's not every draw that uses up more than one:
```
>>> p1 = galsim.PoissonDeviate(1234, mean=10)
>>> p2 = galsim.PoissonDeviate(1234, mean=20)
>>> p3 = galsim.BaseDeviate(1234)
>>> p1.raw(), p2.raw(), p3.raw()
(545413819, 545413819, 545413819)          # in sync at the start.  good.
>>> p1(), p2(), p3.raw()
(11, 19, 968378552)
>>> p1.raw(), p2.raw(), p3.raw()
(1967362378, 1967362378, 1967362378)       # still in sync after 1 draw
>>> p1(), p2(), p3.raw()
(9, 17, 584644678)
>>> p1.raw(), p2.raw(), p3.raw()
(2256489288, 2256489288, 2256489288)       # and after 2
>>> p1(), p2(), p3.raw()
(17, 24, 1705690415)
>>> p1.raw(), p2.raw(), p3.raw()
(43326486, 3975120342, 3975120342)         # oops p1 is out of sync.
>>> p1.raw(), p2.raw(), p3.raw()
(1157805930, 43326486, 43326486)           # 1 ahead of the others apparently.
```

**Comment by brgillis** [comment]
Ah yes, this was the root problem I was referring to; sorry if that wasn't clear. This comes from the while(true) loop in boost's poisson_distribution.hpp, starting at line 275:

```
        while(true) {
            RealType u;
            RealType v = uniform_01<RealType>()(urng);
            if(v <= 0.86 * _ptrd.v_r) {
                u = v / _ptrd.v_r - 0.43;
                return static_cast<IntType>(floor(
                    (2*_ptrd.a/(0.5-abs(u)) + _ptrd.b)*u + _mean + 0.445));
            }

            if(v >= _ptrd.v_r) {
                u = uniform_01<RealType>()(urng) - 0.5;
            } else {
                u = v/_ptrd.v_r - 0.93;
                u = ((u < 0)? -0.5 : 0.5) - u;
                v = uniform_01<RealType>()(urng) * _ptrd.v_r;
            }

            RealType us = 0.5 - abs(u);
            if(us < 0.013 && v > us) {
                continue;
            }

            RealType k = floor((2*_ptrd.a/us + _ptrd.b)*u+_mean+0.445);
            v = v*_ptrd.inv_alpha/(_ptrd.a/(us*us) + _ptrd.b);

            RealType log_sqrt_2pi = 0.91893853320467267;

            if(k >= 10) {
                if(log(v*_ptrd.smu) <= (k + 0.5)*log(_mean/k)
                               - _mean
                               - log_sqrt_2pi
                               + k
                               - (1/12. - (1/360. - 1/(1260.*k*k))/(k*k))/k) {
                    return static_cast<IntType>(k);
                }
            } else if(k >= 0) {
                if(log(v) <= k*log(_mean)
                           - _mean
                           - log_factorial(static_cast<IntType>(k))) {
                    return static_cast<IntType>(k);
                }
            }
        }
```
Even if there is a way to change this to only ever draw one random value (I think there should be, but it might take a bit of work to figure out), doing so would break the promise to keep seeded RNG consistent across GalSim version.

**Comment by rmjarvis** [comment]
> Ah yes, this was the root problem I was referring to; sorry if that wasn't clear. 

No, you were clear.  I just read your post too quickly the first time and misunderstood your point.

> doing so would break the promise to keep seeded RNG consistent across GalSim version.

We don't actually have that promise.  The point of including the boost code in the GalSim repo is to have consistent seeding of the **same** GalSim version run on different machines.  i.e.  not dependent on the particular version of boost that a user happens to have installed on a system.  

So if you feel inclined to try to edit their code to make it always use up exactly 1 rng value, feel free.

**Comment by brgillis** [comment]
Okay, I've got an implementation which seems to be working in branch #878 now, but it might slow things down a bit, since the only way I could figure out to do it simply is to defer to a second generator (similar to how the seeding function works) to find a different state to start at for the generation. This requires a couple more calls to it, but I haven't tested yet just how much more time this takes.

Still have to set up tests for this; I'll get to that next week.

**Comment by brgillis** [comment]
After putting some more thought into this, I'm not convinced this is the best way to solve this issue. I think the best way would be to:

1) Revert this change.
2) Make sure in CCDNoise that read noise is always applied (or at least determined first), so it won't be affected by the changes to the engine from calculating Poisson Noise
3) Put in an option to the PoissonNoise and CCDNoise classes to use a Gaussian approximation for the Poisson noise, which will allow it to be determined with the same number of RNG calls each time and also scale consistently (which I can't guarantee with my current implementation). Not sure what to call this option though - I'm thinking "use_gaussian_approximation," but I'm open to other ideas.

**Comment by brgillis** [comment]
It looks like a Gaussian approximation can be done with the existing VariableGaussianNoise class, though it does require the user to do their own calculations of what the noise should be. This is fine for my purposes, and I'm not sure if my use case is going to be common enough that it's worth putting in options to eg. CCDNoise to make this easier for others. This might be something that can actually just be handled by adding an example of it being used this way, showing the calculations needed (perhaps in demo5).

Does this sound good, or do you think it's worth implementing an option to do this automatically in CCDNoise and PoissonNoise?

**Comment by rmjarvis** [comment]
I don't think this use case should be added to demo5.  First, that's still fairly early in the tutorial sequence, so we are trying to keep things relatively simple.  But also, the signal-to-noise option that is included there would be much more complicated with this kind of noise profile.  (And probably not actually correct -- I thnk it assumes constant noise over the postage stamp.)

It sounds to me like maybe this is just a case where you implement this for your own use case and not put it into GalSim.  We can revisit this if more people ask for this feature, or if you feel like it would be worth implementing as an option for either the PoissonNoise or CCDNoise classes.

**Comment by brgillis** [comment]
Okay, I think it's fine to leave it now, unless someone else comes along with the same issue.
