### ISSUE TITLE
cosmos download link doesn't work

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#886]
The link used by `galsim_download_cosmos` no longer works

the link is http://great3.jb.man.ac.uk/leaderboard/data/public/COSMOS_25.2_training_sample.tar.gz

**Comment by rmandelb** [comment]
@joezuntz - it seems the GREAT3 leaderboard and data site is still down?

(Erin, the site went down a few days ago due to some issue in their server room.)

**Comment by joezuntz** [comment]
Looks like they got around to fixing the air con but never told me.  I've restarted the server now - it should work.

**Comment by esheldon** [comment]
yep, downloading now, thanks @joezuntz
