### ISSUE TITLE
Python 3 support for Homebrew formula

### ISSUE THREAD

**Issue by josePhoenix** [GalSim-developers/GalSim#891]
Is the GalSim code Python 3 capable yet? Happy to move this question somewhere else if this isn't the right venue.

As a followup to this: Is there a version of the Homebrew formula that can build against Python 3?

**Comment by rmjarvis** [comment]
Yes.  GalSim works with Python 3.4, 3.5 and 3.6.  (All regularly tested on Travis.)  I don't use Homebrew, so I can't speak to the second question, but I suspect not.  I don't think it has even been updated to version 1.4.  Pinging @dstndstn who wrote the existing brew.

**Comment by josePhoenix** [comment]
:+1: Thanks. I can dig in to the formula, but wanted to verify that I wouldn't be following a dead-end.

**Comment by msyriac** [comment]
@rmjarvis If I try to build from a clone of the repo, the `scons` configuration file is not Python 3 compatible. After doing a 2to3 on the script, I get:
```
$ scons
scons: Reading SConscript files ...
SCons is version 3.0.0 using python version 3.6.2
Python is from /usr/include/python3.6m
Using the default scons options
Using python =  /usr/bin/python
Using default PYPREFIX =  b'/usr/lib/python3.6/site-packages'
Using compiler: /usr/bin/g++
TypeError: a bytes-like object is required, not 'str':
  File "/home/msyriac/repos/GalSim/SConstruct", line 2022:
    DoConfig(env)
  File "/home/msyriac/repos/GalSim/SConstruct", line 1855:
    GetCompilerVersion(env)
  File "/home/msyriac/repos/GalSim/SConstruct", line 539:
    if 'clang' in lines[0]:

``` 

which seems Python 3 specific, since the script works if I run scons with Python 2.

**Comment by dstndstn** [comment]
try changing the 'clang' to b'clang'... typical py 2 vs 3 bytes vs unicode issue.

**Comment by rmjarvis** [comment]
SCons 3.0 is kind of a bleeding edge release (released less than a month ago -- 9/18/2017).  There are fixes already on master to support it (cf. PR #894), but v1.4 expected SCons 2.x.  So if you are working on this expecting SCons 3.0 to work, you're probably better off waiting for v1.5, which should be out pretty soon now.

**Comment by msyriac** [comment]
Thanks, can confirm this issue is not in master.

**Comment by rmjarvis** [comment]
[v1.5](https://github.com/GalSim-developers/GalSim/releases/tag/v1.5.1) is released, so you should be able to make a brew that uses SCons 3.0 now if you want.

**Comment by rmjarvis** [comment]
Considering that v2.0 is pip installable, I'm guessing that there isn't a pressing need to update the homebrew formula anymore.  If you want to revisit this and have any issues to discuss here, please feel free to reopen.
