### ISSUE TITLE
INSTALL.md comments about numpy

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#898]
I'm finding that in the GalSim master branch, we use numpy.moveaxis, which first appeared in v1.11.  The INSTALL file says we regularly test on 1.11, but other versions may work.  I think we should explicitly say that numpy versions >=1.11 may work, but that versions below that definitely will not.  Please let me know if there are any objections to that change, otherwise I will make it on master.

**Comment by rmjarvis** [comment]
Actually, I just discovered that the numpy at nersc doesn't have moveaxis, so I think I'm in favor of fixing our code to not require this feature.  At least for now...

**Comment by rmandelb** [comment]
Closing #898.
