### ISSUE TITLE
demo13.py (WFIRST) does not work with master

### ISSUE THREAD

**Issue by josePhoenix** [GalSim-developers/GalSim#899]
I'm working on translating the [`demo13.py`](https://github.com/GalSim-developers/GalSim/blob/master/examples/demo13.py) file to a Jupyter notebook and finding that certain pieces of the API have changed.

First one, on [L252](https://github.com/GalSim-developers/GalSim/blob/master/examples/demo13.py#L252):

```
        # Generate a point source.
        point = galsim.DeltaFunction(flux=1.)
```

Looks like that should be `galsim.Delta()`.

Once I change that, I get as far as [L256](https://github.com/GalSim-developers/GalSim/blob/master/examples/demo13.py#L256):

```
star = galsim.Convolve(point*star_sed, PSF)
```

Which gives me this error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-29f086e5c293> in <module>()
     20     # Or a typical galaxy SED.  Depending on your purpose for drawing the PSF.
     21     star_sed = galsim.SED(lambda x:1, 'nm', 'flambda').withFlux(1.,filter_)  # Give it unit flux in this filter.
---> 22     star = galsim.Convolve(point*star_sed, PSF)
     23     img_psf = galsim.ImageF(64,64)
     24     star.drawImage(bandpass=filter_, image=img_psf, scale=wfirst.pixel_scale)

/opt/conda/lib/python3.6/site-packages/galsim/compound.py in Convolve(*args, **kwargs)
    218 
    219     if any([isinstance(a, galsim.ChromaticObject) for a in args]):
--> 220         return galsim.ChromaticConvolution(*args, **kwargs)
    221     else:
    222         return Convolution(*args, **kwargs)

/opt/conda/lib/python3.6/site-packages/galsim/chromatic.py in __init__(self, *args, **kwargs)
   1754             else:
   1755                 self.objlist.append(obj.copy())
-> 1756         if all([obj.separable for obj in self.objlist]):
   1757             self.separable = True
   1758             self._findSED()

/opt/conda/lib/python3.6/site-packages/galsim/chromatic.py in <listcomp>(.0)
   1754             else:
   1755                 self.objlist.append(obj.copy())
-> 1756         if all([obj.separable for obj in self.objlist]):
   1757             self.separable = True
   1758             self._findSED()

AttributeError: 'SED' object has no attribute 'separable'
```

I figured I'd stop here and see if the project had an updated demo13.py or could suggest a fix before digging in to it myself.

**Comment by rmandelb** [comment]
Are you sure you've run scons etc. on the master branch?  Your first suggested change is wrong; on master we have a new object called a DeltaFunction, and that line you pointed out is instantiating one.  If you haven't run scons on the master branch, then your older version of GalSim won't know about DeltaFunction.  (Delta is something else entirely.)

**Comment by josePhoenix** [comment]
Hmm, as far as I know, that's building off master. I can't build on my Mac, so I'm all tangled up in docker containers 😂

I'll investigate when I'm back at my computer and update this issue.

**Comment by josePhoenix** [comment]
Aha, I wasn't aware that changing the default branch on GitHub could change the branch that gets cloned with a `git clone https://...`. Looks like a version mismatch!

Actually, I thought I was building `master` because I didn't realize 1.4 would build against Python 3. So, I've been build the released version this whole time without issues... I'll just use that.
