### ISSUE TITLE
Travis broke with commit that has documentation changes only?

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#903]
I just pushed a commit to master because it was documentation changes only, and then got an e-mail that Travis broke:
https://travis-ci.org/GalSim-developers/GalSim/builds/265778912?utm_source=email&utm_medium=notification

Is this a fluke or ...?

**Comment by rmjarvis** [comment]
Travis switch their Ubuntu build from precise to trusty.  [Which doesn't have ffmpeg.](https://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04)  I just dealt with this on #853, so I'll also make the same fix on master.

**Comment by rmandelb** [comment]
Phew, not my fault.  :)  Thanks!

**Comment by rmjarvis** [comment]
Done.
