### ISSUE TITLE
Fits file reading issue

### ISSUE THREAD

**Issue by Ashlou** [GalSim-developers/GalSim#906]
I am using MacOS 10.12.6, Python 2.7, Galsim 1.4.4, Numpy 1.13.1, Astropy 1.3.3, and Fitsio

My goal is to take simulated wide field HST images (12288*12288 pixels, roughly 600MB in .fits format) and add the WFIRST detector features to it. Unfortunately, I have faced difficulties reading the fits files.

I have tried galsim fits method ‘galsim.fits.read(“fine_name.fits”)’ and I‘ve got :
""""
galsim.Image(bounds=galsim.BoundsI(xmin=1, xmax=12288, ymin=1, ymax=12288), array=
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32), wcs=galsim.PixelScale(1.0))
""""
Which clearly is not a GSObject!

I have tried ‘fitsio.read(“file_name.fits”)’ as well but still, I am not able to convolve PSFs through 'gals.Convolve' or add detector features.

Further, I have been trying to use 'galsim.RealGalaxyCatalog' but I need more info to build an appropriate catalog.

-Thanks

**Comment by rmjarvis** [comment]
No, reading in a fits file gives you an Image.  As you demonstrated above.  I'm not sure why you would expect this to be a GSObject.  A GSObject represents a surface brightness profile of a galaxy or star (typically).

Probably you should look through the [tutorials](https://github.com/GalSim-developers/GalSim/wiki/Tutorials), which culminate in demo13, which includes some WFirst detector effects.  And demos 6, 10, and 11 show different kinds of uses of the `RealGalaxyCatalog` class.  

Once you have a good idea of how these demos work, if you still have questions, [StackOverflow](https://stackoverflow.com/search?q=galsim) using the `#galsim` tag would probably be the better venue for that kind of question.  

If you think something in GalSIm isn't working properly or you want to make a feature request, then this would be the right place to post that as an Issue.

**Comment by Ashlou** [comment]
Thanks for your prompt response. I'll go through the tutorials again.
I appreciate your help
