### ISSUE TITLE
Don't double-allocate LookupTable2D

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#908]
Currently, when creating a `LookupTable2D`, the values array is stored as an attribute of the class (`.f`), and also gets sent down to c++ where it's stored again.  This isn't a huge problem for 1D arrays - where it also occurs, but are usually small - but adds up quickly for 2D arrays.  It's not hard to consume all 16 GB of my laptop's memory doing an atmospheric PSF simulation, for instance, and it would be great to recover ~50% of that.

We already have a `.getVals()` method for `_galsim._LookupTable2D` that returns a read-only view into the c++ layer values array.  I propose hooking `LookupTable2d.f` up to that as a property instead.  This saves RAM, and has the added benefit of making LookupTable2D more immutable in practice, not just principle.  I suppose hooking up `.x` and `.y` the same way would also be reasonable, as would be doing similar things to 1D `LookupTable`.  Thoughts?

**Comment by rmjarvis** [comment]
On my next `noboost` PR, I'll include edits that do the allocation for the lookup tables only in python and have the C++ layer not make a copy.  So if you're willing to wait until then, you can just use that.  Or if you want to get it sooner, I can try to separate those commits out into a separate PR onto master.

**Comment by rmjarvis** [comment]
This functionality is included in PR #911.
