### ISSUE TITLE
demo2 does not run in python 2.7

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#913]
I'm on master e135195c81cc365aa5daaf8a681b0afb83f223d5

I'm  using anaconda

For demo2.py I'm getting the following error in python 2.7.  It is related to HSM at the C/C++ level.  It works fine in python 3

```
[esheldon@forest examples] python demo2.py
Starting demo script 2 using:
    - sheared (0.10,0.20) exponential galaxy (flux = 1.0e+05, scale radius = 2.70),
    - circular Moffat PSF (beta = 5.0, re = 1.00),
    - pixel scale = 0.20,
    - Poisson noise (sky level = 2.5e+03).
Wrote image to 'output/demo2.fits'
Wrote effective PSF image to 'output/demo2_epsf.fits'
Traceback (most recent call last):
  File "demo2.py", line 149, in <module>
    main(sys.argv)
  File "demo2.py", line 136, in main
    results = galsim.hsm.EstimateShear(image, image_epsf)
  File "/home/esheldon/miniconda2/lib/python2.7/site-packages/galsim/hsm.py", line 459, in EstimateShear
    hsmparams = hsmparams)
Boost.Python.ArgumentError: Python argument types in
    galsim._galsim._EstimateShearView(ImageViewF, ImageViewF, ImageViewI)
did not match C++ signature:
    _EstimateShearView(galsim::BaseImage<float> gal_image, galsim::BaseImage<double> PSF_image, galsim::BaseImage<int> gal_mask_image, float sky_var=0.0, char const* shear_est='REGAUSS', std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > recompute_flux='FIT', double guess_sig_gal=5.0, double guess_sig_PSF=3.0, double precision=1e-06, galsim::Position<double> guess_centroid=galsim.PositionD(x=0.0, y=0.0), boost::shared_ptr<galsim::hsm::HSMParams> hsmparams=None)
    _EstimateShearView(galsim::BaseImage<double> gal_image, galsim::BaseImage<float> PSF_image, galsim::BaseImage<int> gal_mask_image, float sky_var=0.0, char const* shear_est='REGAUSS', std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > recompute_flux='FIT', double guess_sig_gal=5.0, double guess_sig_PSF=3.0, double precision=1e-06, galsim::Position<double> guess_centroid=galsim.PositionD(x=0.0, y=0.0), boost::shared_ptr<galsim::hsm::HSMParams> hsmparams=None)
    _EstimateShearView(galsim::BaseImage<double> gal_image, galsim::BaseImage<double> PSF_image, galsim::BaseImage<int> gal_mask_image, float sky_var=0.0, char const* shear_est='REGAUSS', std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > recompute_flux='FIT', double guess_sig_gal=5.0, double guess_sig_PSF=3.0, double precision=1e-06, galsim::Position<double> guess_centroid=galsim.PositionD(x=0.0, y=0.0), boost::shared_ptr<galsim::hsm::HSMParams> hsmparams=None)
    _EstimateShearView(galsim::BaseImage<float> gal_image, galsim::BaseImage<float> PSF_image, galsim::BaseImage<int> gal_mask_image, float sky_var=0.0, char const* shear_est='REGAUSS', std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > recompute_flux='FIT', double guess_sig_gal=5.0, double guess_sig_PSF=3.0, double precision=1e-06, galsim::Position<double> guess_centroid=galsim.PositionD(x=0.0, y=0.0), boost::shared_ptr<galsim::hsm::HSMParams> hsmparams=None)
```

**Comment by rmandelb** [comment]
If I'm on master, then demo2.py runs just fine for me (python 2.7.13).

Sorry if this is a silly question, but did you definitely redo `scons` and `scons install` after going there from some other branch?

**Comment by esheldon** [comment]
yes

**Comment by esheldon** [comment]
In fact I did a new git clone

**Comment by rmjarvis** [comment]
I haven't been able to reproduce this.  All the systems I have run demo2 just fine.  (Including the bnl machines.)

Is this the only failure you found on this system?  Does scons tests pass all tests?  Or are there a bunch of other errors there too?

I see some references to std:__cxx11 in the error message, which seems likely to be related to the problem.  Maybe you used a different compiler to compile galsim than anaconda used to compile python?  Or a different cstdlib linkage in the two cases?

If this is the only thing that is failing, I'll bet we could just swap out the `std::string` parameter with a `const char *` to avoid the problem.  That's already what we use for the `shear_est` parameter.  There's probably no good reason to use a `std::string` for `recompute_flux`.

**Comment by esheldon** [comment]
Yes the compilers are different versions of gcc (they usually will be since anaconda is a binary distro and tends to use older compilers).  But why would this only happen for python2 not python3?

I see it in other demos as well, e.g. demo3 (see below)

scons tests also fails with similar errors

```
Traceback (most recent call last):
  File "git/GalSim/examples/demo3.py", line 288, in <module>
    main(sys.argv)
  File "git/GalSim/examples/demo3.py", line 192, in main
    obscuration = opt_obscuration)
  File "/home/esheldon/miniconda2/lib/python2.7/site-packages/galsim/phase_psf.py", line 1588, in __init__
    ii_pad_factor=ii_pad_factor)
  File "/home/esheldon/miniconda2/lib/python2.7/site-packages/galsim/phase_psf.py", line 1097, in __init__
    _serialize_maxk=self._serialize_maxk)
  File "/home/esheldon/miniconda2/lib/python2.7/site-packages/galsim/interpolatedimage.py", line 292, in __init__
    self.x_interpolant = galsim.utilities.convert_interpolant(x_interpolant)
  File "/home/esheldon/miniconda2/lib/python2.7/site-packages/galsim/utilities.py", line 251, in convert_interpolant
    return galsim.Interpolant(interpolant)
Boost.Python.ArgumentError: Python argument types in
    Interpolant.__init__(Interpolant, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > str, double tol=0.0001)
```

**Comment by esheldon** [comment]
actually in this case the compiler used in anaconda is very new `7.2.0`

**Comment by esheldon** [comment]
and... the python 3 version I was using is `4.4.7`, probably a good clue

**Comment by esheldon** [comment]
Sorry, those last two messages were probably not easy to interpret

The anaconda python 2 used `gcc 7.2.0` for compiliation
The anaconda python 3 used `gcc 4.4.7` for compilation

**Comment by rmjarvis** [comment]
I think if you match the gcc you use for GalSim with what was used for anaconda, it should usually work.  At least matching the first digit, although in the 4.x branch, I think there are incompatibilities going before and after 4.8.

**Comment by esheldon** [comment]
The compiler used to compile galsim is in between: `6.2.0`

So it seems that `4.4.7` and `6.2.0` are an OK mix, but not `7.2.0` and `6.2.0`

**Comment by rmjarvis** [comment]
> So it seems that 4.4.7 and 6.2.0 are an OK mix,

In my experience, this isn't always true.  I've had trouble crossing the 4.8 version.  But that may also depend on the use of the `-std=c++98`, which may change where problems happen.

**Comment by esheldon** [comment]
Note I was still using python 3.5 anaconda which is why the older compiler was used.  The latest will use python 3.6 and also use gcc 7.2.0

that explains why it was working in python 3

**Comment by esheldon** [comment]
I converted the HSM stuff to use `const char*` and it works fine.

There are some other places where `std::string` is used, I could convert them as well and send a pull request.

**Comment by rmjarvis** [comment]
Please do.

**Comment by esheldon** [comment]
I've run into a different error, this time in Random.cpp  This one is not clear to me

I see this in demo9
```
RuntimeError: ('Cannot construct UniformDeviate from given seed.', <class 'galsim._galsim.UniformDeviate'>, ('1963951042 1526159089 3786128563 1502....<snip>
```

**Comment by esheldon** [comment]
actually this might also be related to `std::string`, it looks like seeds can be strings?  Is this a needed overload or could I just remove that entirely?

**Comment by rmjarvis** [comment]
That's what we use for serializing rngs.  We do need some kind of string constructor.  But you can try switching it to char* to see if that works.

**Comment by esheldon** [comment]
pull request sent #915
