### ISSUE TITLE
Can't find -lirc and -limf

### ISSUE THREAD

**Issue by gijzelaerr** [GalSim-developers/GalSim#921]
hi!

I'm trying to make a debian package out of Galsim.

results are here:

https://github.com/kernsuite-debian/galsim
http://kernsuite.info

problem is, on some systems somehow the packaging works but on others not. I puzzled why it doesn't work. If I try to build the package in an empty environment it fails:
```
TMV version is 0.74                                                                                                    
Using TMV_LINK file: /usr/share/tmv/tmv-link
     -L/usr/lib -ltmv -lcblas -lpthread -fopenmp
Checking for correct TMV linkage... (this may take a little while)
Checking for correct TMV linkage...
Error: TMV file failed to link correctly
Check that the correct location is specified for TMV_DIR
```
in config.log i find:
```
g++ -o .sconf_temp/conftest_23 -fopenmp -Wl,-rpath=/usr/lib .sconf_temp/conftest_23.o -Llib -L/usr/lib -ltmv_symband -lirc -limf -lfftw3 -lpthread -ltmv -lcblas -lpthread                                                                    
/usr/bin/ld: cannot find -lirc
/usr/bin/ld: cannot find -limf
collect2: error: ld returned 1 exit status
```

my compile command is:
```
scons PREFIX=/galsim/debian/tmp/usr TMV_LINK=/usr/share/tmv/tmv-link PYPREFIX=/galsim/debian/tmp/usr/lib/python2.7/dist-packages
```

**Comment by rmjarvis** [comment]
This isn't really the relevant test.  It tries adding `-lirc -limf` if the normal test fails, because occasionally these are necessary.  It also tries a bunch of different `-L` possibilities, so it can be a bit tricky to figure out which attempt by SCons is actually the one you expect to work.  If you post the `gs_error.txt` file that gets generated, I can take a look and give you a more specific recommendation about what the problem might be.

**Comment by gijzelaerr** [comment]
[config.log](https://github.com/GalSim-developers/GalSim/files/1456869/config.log)
[gs.error.log](https://github.com/GalSim-developers/GalSim/files/1456870/gs.error.log)

**Comment by rmjarvis** [comment]
The command that should have worked is
```
g++ -o .sconf_temp/conftest_13 -fopenmp .sconf_temp/conftest_13.o -Llib -L/usr/lib -ltmv_symband -lfftw3 -lpthread -ltmv -lcblas -lpthread
```
But it can't find the cblas library:
```
/usr/bin/ld: cannot find -lcblas
```
So you should investigate whether that library is actually there or not.  TMV apparently found it when you were installing that, but I can't say why the linker can't find it when you are installing GalSim.  But in any case, that's the actual problem for you to figure out.

**Comment by gijzelaerr** [comment]
ah yes! Adding a libatlas dependency solved the problem

https://github.com/kernsuite-debian/galsim/commit/47f19a4b565c74c38784e5d7176e37bda28f53bc#diff-d837a1c17de0268bcea321239ddbed47R11

we have happy packages again now. thanks!
