### ISSUE TITLE
WFIRST module zeropoint issues

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#923]
Issue reported by Rubab Khan:

The zeropoints in the WFIRST module are incorrect (in different ways for GalSim v1.4 and v1.5; they are around ~14 in v1.5 and ~32 in v1.4).

I'm guessing there is some consistent units issue in a few places, because the galaxy fluxes in images with sky background added seem totally reasonable.

**Comment by rmandelb** [comment]
@jmeyers314 - I wanted to run some things by you, to make sure I understand the SED/bandpass functionality properly.  

I believe I now understand why the WFIRST bandpass AB zeropoints were too faint in v1.4 and too bright in v1.5:

- Rubab is (I'm pretty sure) expecting the zeropoint for WFIRST bandpasses to be set for an object producing 1 count/sec as seen by WFIRST.

- In v1.4, the zeropoint was set for an object producing 1 count per 168 sec exposure as seen by WFIRST, so there was an extra +2.5*log10(168) compared to Rubab's expected convention, which gave something too faint.

- In v1.5, the new convention sets the zeropoint for an object producing 1 count/sec/cm^2, so we were missing that area factor (i.e., that WFIRST has a collecting area way larger than 1 cm^2) and the zeropoint was too bright.

First of all, does my logic here make sense? I confirmed that if I include that area factor in the WFIRST bandpass zeropoints (see branch for this issue), the zeropoints are now ~27.  So in principle, I could just wrap this up by adding some unit tests, but I have a few questions about this:

1. Do you know what the typical convention is for zeropoint definition?  For example, for ACS the norm is to use the "1 photon/sec" after including the factor of collecting area.  What I'm proposing to do for WFIRST is consistent with that.  Should we be including some examples in demos or some documentation to clarify that if people have a particular instrument in mind they must be careful to include that collecting area factor?  Should we perhaps include it as an option in the `withZeropoint` method rather than as a correction afterwards, as I've currently done?

2. Sorry if I missed something, but I want to make sure we self-consistently demonstrate or explain usage of SEDs with zeropoints and how to properly set the flux given some exposure time somewhere.  Where is this currently done?  Currently because of the way the flux is set in demo13.py, we sidestep this issue there.

**Comment by jmeyers314** [comment]
@rmandelb , I think your logic is sound.

I'm not sure if having the zeropoint mean "magnitude producing 1 photon/sec in this telescope" or "magnitude producing 1 photon/sec/cm^2 independent of telescope" is more typical.  I think the main advantage of using the latter definition is that it makes using the `area` kwarg in `drawImage` simpler, since you don't need to know what collecting area was used to set the bandpass zeropoint in that case.  Adding a kwarg to `withZeropoint` to handle convert from ACS-style definition to GalSim-style definition is probably a good idea.  Regardless of what we do, one convention that I think is worth maintaining (and potentially testing for if we aren't doing it already), is that SED amplitudes should be totally independent of telescope and exposure times, including setting their amplitudes via `withMagnitude`.

In theory, there's some documentation in demo12 in addition to demo13.  I see there that the `withFluxDensity` description there is a lie(!) though.  It should say "we normalize such that the photon density is 1 photon per nm per cm^2 per s" instead of just "1 photon per nm".  We could definitely use a more extensive demo for setting `SED` fluxes/magnitudes/flux-densities, `Bandpass` zeropoints, using the `drawImage` `area` and `exptime` kwargs, and using the `RealGalaxy` and `ChromaticRealGalaxy` `area_norm` kwarg.  I think a jupyter notebook might actually be a nice way to present this.

**Comment by rmandelb** [comment]
> I think the main advantage of using the latter definition is that it makes using the area kwarg in 
> drawImage simpler, since you don't need to know what collecting area was used to set the 
> bandpass zeropoint in that case.

Hmmm, good point.  Another question: am I right in thinking that if we use the "magnitude producing 1 photon/sec in this telescope" definition then things like calculateFlux (which wants to return photons/cm^2/sec) are also complicated (because if we set zeropoints this way it would return photons/sec *for this telescope given its collecting area*)?  I think it's not just drawImage that would be complicated by this.

But if we did want to allow it, then I guess we could give the bandpass a `zeropoint_area` attribute (default: None) that, if set, corresponds to the collecting area that was assumed.  And then we could update the docstrings for various things like drawImage and calculateFlux to clarify the units issues.  Hmmm.  Thoughts on that?

The alternative, I suppose, is to maintain our definition and then add documentation in various places (WFIRST routines to get bandpasses, demo13.py) clarifying how the zeropoints are set and how to convert to the other definition.

> In theory, there's some documentation in demo12 in addition to demo13.

Hmmm.  That's incomplete and, as you say, wrong in at least one place.  Let me recommend breaking this out into a separate issue to fix the demo12 documentation and add another demo or a jupyter notebook demonstrating more of the chromatic functionality, and not coupling this to this particular issue.

**Comment by rmandelb** [comment]
@rmjarvis - also curious to get your take on what we're discussing here.

**Comment by rmjarvis** [comment]
I don't claim any level of competence in dealing with zeropoints. 

That said, I think I like the idea that the photons/cm^2/sec units is a good standard to adopt in GalSim and just have the WFIRST code explicitly use `area=galsim.wfirst.collecting_area` in `drawImage`.  But I'm pretty open to whatever you two settle on if you think something else would be more appropriate.

**Comment by rmandelb** [comment]
Yeah, I'm sort of leaning that way.  Once it's already our standard and we have a well-defined way of dealing with it consistently to draw images that are properly normalized, leaving it as-is seems better.  In that case, maybe the thing to do is just emphasize in the WFIRST bandpass routine docstring that the zeropoint is defined using photons/cm^2/sec units.  I've just pinged Rubab to see how that sounds to him, since he's the one who raised this and I don't think he's on GitHub.

**Comment by rmandelb** [comment]
I did a bit more digging around and I think I have a better feel for the situation.

Astronomers more commonly use photons/sec to define zeropoints, in part because they are typically tying themselves to a particular instrument (e.g., they are using ACS bandpasses, or whatever, and assuming that all observations are with that chosen instrument, which means the only possible variation is exposure time, not collecting area).  So the convention there is that zeropoint is instrument-specific; you could perhaps think of it as a bandpass+instrument zeropoint rather than a bandpass zeropoint. They would find our convention odd/unusual despite the fact that there are clear advantages.  If a word has a common definition, and you redefine it, then no matter how good your logic is, you're going to confuse people, especially those who hadn't read every single line of the documentation.

I still can't think of a solution within our current framework that doesn't result in something kludgy happening somewhere.  So, I think the thing to do is:

- I update the WFIRST module documentation to more clearly indicate what the zeropoints mean and explain how you can convert to instrument-specific zeropoints if you wish.  (There are also some minor code updates because I found another small problem in the getBandpasses routine).

- We open another issue about (a) more broadly reconsidering the question of bandpass- vs. instrumental-zeropoints and the connection to common zeropoint definitions, (b) increasing/fixing documentation and usage examples for zeropoints and drawImage with kwargs such as area (c.f. what Josh mentioned in https://github.com/GalSim-developers/GalSim/issues/923#issuecomment-347282467).  Even if we decide to do nothing about (a), I think that (b) is important.

**Comment by rmandelb** [comment]
Closing #923.
