### ISSUE TITLE
cutout_row/cutout_col for MEDS output type when using offsets.

### ISSUE THREAD

**Issue by NiallMac** [GalSim-developers/GalSim#928]
I believe the cutout_row and cutout_col columns in the OBJECT_DATA extension of a MEDS file should give the (zero-offset) position of the object in pixel coordinates (@esheldon can confirm).  Currently this is set to the origin of the stamp wcs in WriteMeds in des_meds.py (called 'row0' and 'col0' in des_meds.py, see e.g. line 263). 

I think this behavior will become problematic as soon as you have more than one exposure of an object with different offsets. I think the solution is to have MEDSBuilder access the stamp offsets (I think this could be done with an extra output type, but maybe there is an easier way?), and make these an attribute of MultiExposureObject. Then WriteMEDS would also be able to access this info. I can go ahead and try to implement this, but keen to hear if @rmjarvis @esheldon or others have thoughts on this before I do so.

**Comment by rmjarvis** [comment]
This seems like a good place to use test-driven design.  Let's start by writing a unit test that uses a few different kinds of WCS types (both Celestial and not at least) and asserting what we think des_meds should be doing with the offsets in each case in terms of cutout_row and cutout_col.

Then we can try to work out what code would be required to make that work correctly.

**Comment by esheldon** [comment]
You are correct, see docs here: https://github.com/esheldon/meds/wiki/MEDS-Format

The "origin of the stamp" is to be stored in `orig_row, orig_col`

**Comment by NiallMac** [comment]
Thanks both. In that case the current wcs treatment is probably fine. I think the key point is that the MEDSBuilder needs to know about the offsets, as these determine cutout_row and cutout_col, whereas currently it only has accesses to the images (after the objects have been drawn with offsets). I'll take a look at the current test_des.py, I think a test of this behaviour should be straightforward to add.

**Comment by NiallMac** [comment]
@esheldon does 'zero-offset' mean the origin for cutout_row/col is at the center of pixel [0,0] or the bottom-left of pixel [0,0]?

**Comment by esheldon** [comment]
SExtractor uses 1.0 = center of the first pixel.

**Comment by NiallMac** [comment]
I'm not sure that answers my question - do you mean that cutout_row/col use the same convention as SExtractor?

**Comment by esheldon** [comment]
Yes, all calculations for the MEDS creation work in the sextractor coordinates, except for the subtraction of 1 to put things into zero offset.

**Comment by NiallMac** [comment]
Ok, so an object at the center of the first pixel should have (cutout_row, cutout_col) = (0., 0.)?

**Comment by esheldon** [comment]
Yes.

**Comment by rmjarvis** [comment]
Done.  via PR #930
