### ISSUE TITLE
cannot download des data

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#936]
For test_demo13 it requires downloading some data but the url doesn't seem work

```
wget http://www.sas.upenn.edu/~mjarvis/des_data.tar.gz
--2018-01-09 09:18:37--  http://www.sas.upenn.edu/~mjarvis/des_data.tar.gz
Connecting to 192.168.1.165:3128... failed: Connection timed out.
```

**Comment by rmjarvis** [comment]
I think this is actually a BNL firewall issue.  I can wget that url from everywhere I've tried except at BNL.  And I had trouble wgetting other file recently from BNL.

**Comment by rmjarvis** [comment]
This should be fixed now at BNL.  Just make sure you don't have http_proxy set in your .bash_profile (as used to be required).
