### ISSUE TITLE
run_all_tests fails

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#937]
Working on branch #809-pybind11  4a5dcb542b456b8eaa5fab5c327641cc28e2aaca

(galsim-test) [esheldon@astro0033 tests] bash run_all_tests 
test_airy.py
run_all_tests: line 6: ../bin/installed_python: No such file or directory

**Comment by rmjarvis** [comment]
Fixed on '#809-pybind11'.  Although there are still tests that fail on that branch, so don't expect it to run through to completion yet.  I'll make sure it does before making a pull request.
