### ISSUE TITLE
Porting homebrew install of galsim to Homebrew/homebrew-core 

### ISSUE THREAD

**Issue by wadawson** [GalSim-developers/GalSim#938]
It looks like [Homebrew/homebrew-science](https://github.com/Homebrew/homebrew-science), that you could tap to install galsim, was recently depreciated and all of the formulae were either migrated to Homebrew/homebrew-core, or deleted. It appears as though galsim was not migrated. I am not sure who created the galsim formula in the first place, but if possible can you follow the recommendations [here](https://github.com/Homebrew/homebrew-science) to try and get the galsim package added to Homebrew/homebrew-core. I am a bit new to this so I am not sure if it satisfies all the requirements.

**Comment by rmjarvis** [comment]
See Issue #891, where there is already some discussion about this.  AFAIK, none of the primary GalSim developers use homebrew, so if you would like to take responsibility of the GalSim brew, it's all yours.  (@dstndstn was the original author, but I don't think he wants to continue to maintain it.)  (Closing as duplicate -- further discussion should move to the #891 thread.)
