### ISSUE TITLE
Installation on cori (nersc) 

### ISSUE THREAD

**Issue by NiallMac** [GalSim-developers/GalSim#939]
I'm having some trouble installing on cori (at nersc). I know @rmjarvis has a working install using python 3, but I want to use the hpcports modules which rely on python 2.7. 
Below is the output of scons install. TMV linking is failing....I've checked /global/cscratch1/sd/maccrann/code/share/tmv/tmv-link does exit, any other suggestions? I've attached the gs_error.txt file. Cheers.
[gs_error.txt](https://github.com/GalSim-developers/GalSim/files/1628911/gs_error.txt)

scons: Reading SConscript files ...
SCons is version 2.3.4 using python version 2.7.12
Python is from /global/common/cori/contrib/hpcosmo/hpcports_gnu-4.0/python-2.7.12_e9e66748-4.0/include/python2.7
Using the following (non-default) scons options:
   PREFIX = /global/cscratch1/sd/maccrann/code/
   PYPREFIX = /global/cscratch1/sd/maccrann/code/
   TMV_DIR = /global/cscratch1/sd/maccrann/code/lib
   BOOST_DIR = /global/cscratch1/sd/maccrann/code/lib
   EXTRA_INCLUDE_PATH = /global/cscratch1/sd/maccrann/code/include
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /global/common/cori/contrib/hpcosmo/hpcports_gnu-4.0/python-2.7.12_e9e66748-4.0/bin/python
Using compiler: /opt/gcc/6.1.0/bin/g++
compiler version: 6.1.0
Determined that a good number of jobs = 20
Using SSE with flag -msse2
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for boost header files... yes
Boost version is 1.66.0
Checking for C++ header file TMV.h... yes
TMV version is 0.75
Using TMV_LINK file: /global/cscratch1/sd/maccrann/code/share/tmv/tmv-link
     -L/global/cscratch1/sd/maccrann/code/lib -ltmv -lmkl_intel_lp64 -lmkl_core -lmkl_gnu_thread -lgomp -ldl -liomp5 -lpthread -fopenmp
Checking for correct TMV linkage... (this may take a little while)

Checking for correct TMV linkage... 
Error: TMV file failed to link correctly
Check that the correct location is specified for TMV_DIR

**Comment by rmjarvis** [comment]
The hpcports stuff isn't really supported there anymore, so probably better to switch over to one of the regular python modules:
```
$ module avail python

--------------------------------- /usr/common/software/modulefiles ---------------------------------
python/2.7-anaconda              python/3.5-anaconda
python/2.7-anaconda-4.4(default) python/3.6-anaconda-4.4
```
But if you really want to use the hpcports one, let me know which modules you are currently using, and I'll see if I can duplicate and advise.

**Comment by rmjarvis** [comment]
In the meanwhile, I note that the problem reported it with TMV, which looks like is your own installation.  If you want, you could try using `TMV_DIR=/global/homes/m/mjarvis`.  That's my TMV installation, and it works for me when installing GalSim.

**Comment by NiallMac** [comment]
Thanks Mike, I didn't realize the hpcports stuff was no longer supported. I've switched over to the default python (python/2.7-anaconda-4.4) and loaded gcc and fftw as follows
`module load python
module load gcc
module load fftw
`
I then run with the following gs_scons.conf:
`PREFIX = '/global/cscratch1/sd/maccrann/code/'
PYPREFIX = '/global/cscratch1/sd/maccrann/code/'
TMV_DIR = '/global/homes/m/mjarvis'
FFTW_DIR = '/opt/cray/pe/fftw/3.3.4.6/x86_64/'
BOOST_DIR = '/global/homes/m/mjarvis/.conda/envs/my_root/'`

But now for some reason the fftw.h file is not found:
scons: Reading SConscript files ...
SCons is version 2.3.0 using python version 2.7.9
Python is from /usr/include/python2.7
Using the following (non-default) scons options:
   PREFIX = /global/cscratch1/sd/maccrann/code/
   PYPREFIX = /global/cscratch1/sd/maccrann/code/
   TMV_DIR = /global/homes/m/mjarvis
   FFTW_DIR = /opt/cray/pe/fftw/3.3.4.6/x86_64/
   BOOST_DIR = /global/homes/m/mjarvis/.conda/envs/my_root/
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /usr/common/software/python/3.6-anaconda-4.4/bin/python
Using compiler: /usr/bin/g++
compiler version: 4.8.5
Determined that a good number of jobs = 20
None of the possible SSE flags worked.
Checking for C++ header file fftw3.h... no

fftw3.h not found
You should specify the location of fftw3 as FFTW_DIR=...

**Comment by rmjarvis** [comment]
This is on cori right?  (Because edison has a different default fftw, so there you would need to use `module load fftw/3.3.4.6'.)  I guess check whether you can see a file called fftw3.h in `/opt/cray/pe/fftw/3.3.4.6/x86_64/include`.

**Comment by NiallMac** [comment]
Yeh, cori - fftw3.h is indeed there...

**Comment by rmjarvis** [comment]
In that case, there must be something weird going on with the compiler.  Send me the gs_error.txt file and I'll take a look.

**Comment by NiallMac** [comment]
Cheers Mike, attached.

[gs_error.txt](https://github.com/GalSim-developers/GalSim/files/1633269/gs_error.txt)

**Comment by rmjarvis** [comment]
It said there was a permission error on my include directory.  I had it world readable, but not executable.  So maybe that was required.  Try again now.

**Comment by NiallMac** [comment]
No change that I can tell, but here is the gs_errror.txt again. 
[gs_error.txt](https://github.com/GalSim-developers/GalSim/files/1633281/gs_error.txt)

**Comment by rmjarvis** [comment]
This time, I think you have the wrong FFTW_DIR.  It is listed as:
```
FFTW_DIR = /opt/cray/pe/fftw/3.3.4.6/x86_64/include/
```
It should just be
```
FFTW_DIR = /opt/cray/pe/fftw/3.3.4.6/x86_64/
```

**Comment by NiallMac** [comment]
oops...now:


scons: Reading SConscript files ...
SCons is version 2.3.0 using python version 2.7.9
Python is from /usr/include/python2.7
Using the following (non-default) scons options:
   PREFIX = /global/cscratch1/sd/maccrann/code/
   PYPREFIX = /global/cscratch1/sd/maccrann/code/
   TMV_DIR = /global/homes/m/mjarvis/
   FFTW_DIR = /opt/cray/pe/fftw/3.3.4.6/x86_64/
   BOOST_DIR = /global/homes/m/mjarvis/.conda/envs/my_root/
These can be edited directly in the file gs_scons.conf.
Type scons -h for a full list of available options.
Using python =  /usr/bin/python
Using compiler: /usr/bin/g++
compiler version: 4.8.5
Determined that a good number of jobs = 32
Using SSE with flag -msse2
Checking for C++ header file fftw3.h... yes
Checking for correct FFTW linkage... yes
Checking for boost header files... yes
Boost version is 1.61.0
Checking for C++ header file TMV.h... yes
TMV version is 0.74

No tmv-link file could be found

Please fix the above error(s) and rerun scons.
Note: you may want to look through the file INSTALL.md for advice.
Also, if you are having trouble, please check the INSTALL FAQ at 
   https://github.com/GalSim-developers/GalSim/wiki/Installation%20FAQ

If nothing there seems helpful, feel free to post an issue here:
   https://github.com/GalSim-developers/GalSim/issues
describing the problem along with the particulars of your system and
configuration.  Include a copy of the above output to the screen, and
post and copy of the file gs_error.txt, which will help people diagnose
the problem.
[gs_error.txt](https://github.com/GalSim-developers/GalSim/files/1633382/gs_error.txt)

**Comment by rmjarvis** [comment]
Sorry, probably another permission problem.  My share directory (where the tmv-link file is) wasn't world executable.  I fixed it, so try again now...  <fingers crossed>

**Comment by NiallMac** [comment]
So things are working now - scons tests runs successfully.

I ended up using my own conda environment (see the instructions [here](http://www.nersc.gov/users/data-analytics/data-analytics-2/python/anaconda-python/)). Then the usual installation steps worked fine. The only things I wasn't sure about was how to install galsim into somewhere on the PYTHONPATH. I ended up setting PYPREFIX=<path-to-anaconda-environment>/lib/python3.6/site-packages, and also setting PREFIX (otherwise it will use /usr/local for which I don't have permissions) when calling scons install. Not sure if there is a better way to deal with this....

**Comment by rmjarvis** [comment]
Normally, yes PREFIX is required on systems like that where you don't have sudo privileges to install the executables and such into your local home directory.  Sometimes PYPREFIX is required, sometimes not.  With conda, I find it usually finds the right location on its own, but YMMV.

**Comment by rmjarvis** [comment]
Assuming this is resolved now.  Please reopen if you have further problems with this.
