### ISSUE TITLE
Directly setting WCS fields from YAML

### ISSUE THREAD

**Issue by gijzelaerr** [GalSim-developers/GalSim#947]
hi!

Is it possible to just manually set the WCS fields from a Galsim YAML file? There are various modules available to help you with conversion, but I'm unable to figure out how to manually set arbitrary fields, for example, the `CDELT*` headers. Is a custom WCS builder required for this?

**Comment by rmjarvis** [comment]
The Tan WCS type is possibly what you want.  It essentially lets you define the CD matrix and CRVALs (to use the language of the Griesen and Calabretta WCS parametrization).

If you want to read in a WCS from a FITS file and then change some of the parameters around, no that's not native to GalSim, but it wouldn't be too hard to write a custom WCS class that would do this for you.

cf. https://github.com/GalSim-developers/GalSim/wiki/Config-Image#wcs for instructions about how to do this.  (And about the Tan WCS type.)
