### ISSUE TITLE
Excessively long execution time for galsim.Kolmogorov

### ISSUE THREAD

**Issue by jchiang87** [GalSim-developers/GalSim#952]
I've encountered a set of parameters that cause `galsim.Kolmogorov` to run seemingly indefinitely.  I'm attaching a pickle file with those parameters.  Here's what I see:
```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> import galsim
>>> galsim.__version__
'1.5.1'
>>> pars = pickle.load(open('kolmogorov_pars.txt', 'rb'))
>>> pars
{'fwhm': 0.55344217545630736, 'gsparams': galsim.GSParams(128,4096,0.0008316873626901008,5.0,0.001,1e-05,1e-05,1.0,0.0001,1e-06,1e-06,1e-08,1e-05,0.81,32,0.0001)}
>>> galsim.Kolmogorov(**pars)
```
I get the same behavior on cori-haswell at NERSC and in a CentOS 7 docker container.

[kolmogorov_pars.txt](https://github.com/GalSim-developers/GalSim/files/1787008/kolmogorov_pars.txt)

**Comment by rmjarvis** [comment]
Yep.  I can confirm that this gets into an endless loop when building the sampler.  Looking now into what is causing it.

**Comment by rmjarvis** [comment]
Fixed in v1.5.2

**Comment by jchiang87** [comment]
Thanks Mike!  @danielsf Can we get v1.5.2 into the next lsst_sims version please?

**Comment by danielsf** [comment]
@jchiang87 sure thing
