### ISSUE TITLE
Add Differential Chromatic Refraction (DCR) as a surface_op

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#955]
A relatively quick way to incorporate DCR (when using photon-shooting) is to add it as a surface operation.  The way this would work is: 

• Assign wavelengths to photons if not already present.
• For each photon, compute a displacement that depends on the wavelength.  (The displacement also depends on pressure, temperature, and water vapor pressure which should be constant for a given exposure, and airmass which is nearly constant, though I suppose we could use the actual object-dependent airmass if there's an easy way to access that).  Also, I think we'd want to use a _relative_ displacement; i.e., look at the difference in chromatic refraction between this photon's wavelength and some fiducial wavelength.
• Figure out which direction to apply the displacement.  This is the part that I think will be the trickiest to get right. (As in, don't make any minus sign errors).
• Apply displacement for each photon.

There are already tools in dcr.py for much of the above.

I'd like to have this available for LSST DESC DC2.  I probably won't attempt to tackle it before getting the atmospheric PSF finished though, so if anyone else wants to give this a go first, please go ahead (but let me know).

**Comment by cwwalter** [comment]
I am a bit confused by how the surface option would retrieve the ray-traced photons.  Since (for now) I think the plan is to use a weighted monochromatic wavelength per band (correct?), would the idea be to randomly assign them based on the bandpass as they arrive photon by photon from your raytrace code?

**Comment by jmeyers314** [comment]
Right.  My thought was: 

1) Do all the atmosphere + optics monochromatically, accumulating photons right at the top of the silicon
2) (Re)assign wavelengths from SED*bandpass.  
3) Apply DCR

and I suppose we could even do Craig's sensor stuff polychromatically next if it has hooks for that.

**Comment by rmjarvis** [comment]
We're already doing the sensor stuff with assigned wavelengths.  He needs that to know how far into the silicon the photons go before being converted to electrons.  Indeed, that wavelength assignment is [currently the tall pole in Jim's test runs](https://github.com/LSSTDESC/imSim/issues/86#issuecomment-373143596).  Still thinking about how to speed that up.

**Comment by cwwalter** [comment]
Yes, I think we don't want to lose that connection since the BF will be also be coupled to the conversion depth and thus to wavelength. So the DCR and BF should be correlated at some level.

**Comment by rmjarvis** [comment]
There's no correlation required.  The DCR surface op will appear after the select wavelengths surface op.  Then the photons will still have wavelengths and slightly modified positions when they go into the silicon code.  The two steps are completely decoupled.  Just both have to be after the wavelengths are selected.

**Comment by cwwalter** [comment]
Right... Sorry, I was unclear.  I didn't mean we had to build in an extra correlations.  I just meant if we do not do this for both then we will lose a correlation between shifted position and BF since the redder photons will convert deeper in the bulk and have less BF effect.

**Comment by rmjarvis** [comment]
Merged via PR #961
