### ISSUE TITLE
VonKarman GSObject fails with certain values of r0

### ISSUE THREAD

**Issue by areshernandez** [GalSim-developers/GalSim#959]
The VonKarman GSObject fails with certain values of r0. Although this generally occurs when r0 has a large number of decimal places, some values of r0 trigger an error even though they have less decimal places than some that don't. Increasing the folding_threshold may help deal with the problem in some cases. 

Here is an example:

RuntimeError                              Traceback (most recent call last)
<ipython-input-30-77c962a179fd> in <module>()
      1 import galsim
      2 #0.14606888419121025
----> 3 galsim.VonKarman(L0=25.,lam=700.,r0=0.146068884)

/nfs/slac/g/ki/ki19/des/aresh/Old_Stuff/Code_Depository/anaconda2/lib/python2.7/site-packages/galsim/vonkarman.pyc in __init__(self, lam, r0, L0, flux, scale_unit, do_delta, suppress_warning, gsparams)
     91         self._scale_unit = scale_unit
     92         scale = scale_unit/galsim.arcsec
---> 93         self._sbvk = _galsim.SBVonKarman(lam, r0, L0, flux, scale, do_delta, gsparams)
     94         self._delta_amplitude = self._sbvk.getDeltaAmplitude()
     95         self._suppress_warning = suppress_warning

RuntimeError: SB Error: Could not find folding_threshold

**Comment by rmandelb** [comment]
This was raised in issue #957 a few days ago and fixed via a PR that was merged to master yesterday (#958).  Are you using the latest version of the master branch as of yesterday, on which this should be fixed? If not, can you please pull the latest version of master and confirm whether or not the fix works for you?

**Comment by rmandelb** [comment]
Closing #959.
