### ISSUE TITLE
non-parametric models

### ISSUE THREAD

**Issue by dannygoldstein** [GalSim-developers/GalSim#960]
I'd like to create a GSObject from a high-resolution simulated image. The image has no noise, and is the output of a ray tracing simulation of galaxy-galaxy lensing, so has a complex morphology that cannot be specified parametrically.

Is there a preferred pattern in GalSim for this? I have tried using RealGalaxy with a vanishingly small PSF and a very small noise variance, but this seems like a bit of a kludge.

**Comment by rmjarvis** [comment]
You want InterpolatedImage.

**Comment by dannygoldstein** [comment]
I looked into that but it looks like a subclass of Image, not GSObject, and so it does not appear to expose the GSObject API. My goal is to realize a final image in which there are several GSObjects (this being just one). The others have parametrically specifiable profiles.

**Comment by dannygoldstein** [comment]
Ah nevermind I now see that InterpolatedImage is a subclass of GSObject. OK I will give this a try. Thanks Mike. 

Danny

**Comment by rmjarvis** [comment]
You can look at demo11 for an example.  It uses InterpolatedImage for the PSF.
