### ISSUE TITLE
Let objects change their gsparams after construction

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#968]
Something that comes up from time to time is people specifying gsparams in a Convolve object and expecting that to affect the component objects.  

This wasn't really possible to make happen in v1.6 (at least not easily), but I think given some of the changes in our noboost branch (specifically that construction of _sbp is delayed until it is needed), it would be possible to do now.

Therefore, I'd like to make the following changes to how this works for v2.0:

1. Add a `withGSParams(gsparams)` method to all GSObjects, which would return a new object with the gsparams attribute changed to the given value.
2. Change classes that contain other objects (Convolution, Transformation, Sum, etc.) to apply any specified gsparams option to the contained component(s).
3. For the ones that wrap multiple objects, if the given gsparams=None, then find the most restrictive combination of parameters from the components and apply that to all the components.

The last two would be API changes, so if people think it's a good idea, v2.0 would be a good time to do it.

Pinging @jchiang87 who was recently bit by this "feature" in v1.6.
Also @sweverett who requested this feature for Balrog.

**Comment by rmjarvis** [comment]
Note: this would include similarly propagating gsparams into Aperture and other such classes that use gsparams but aren't GSObjects.  cf. https://github.com/LSSTDESC/imSim/pull/101/files#r187122346

**Comment by rmandelb** [comment]
I like this suggestion.

**Comment by rmjarvis** [comment]
Merged via #970
