### ISSUE TITLE
Allow chromatic objects in config processing

### ISSUE THREAD

**Issue by sweverett** [GalSim-developers/GalSim#969]
I’m trying to use parametric, chromatic COSMOS galaxies as test inputs for DES Y3 Balrog. This wouldn’t be an issue except that I made the decision early on to use config processing rather than the python interface. As far as I can tell, chromatic objects are not yet supported when running from config files.

I have made a few small changes that allows me to use chromatic COSMOS objects in this way. However, I wanted to check (1) if these changes are correct, (2) whether I have missed any important details, and (3) if there’s a better way to do all this. I can change this into a pull request if there is interest in incorporating any of these changes.

I made a custom COSMOS chromatic catalog / loader / builder for testing, but the biggest differences are that I:
1.  Included `chromatic` in `makeGalaxy._opt_params`,
2. Call `makeGalaxy()` rather than `_makeSingleGalaxy()` in the `COSMOSChromaticGalaxy` builder as `_makeSingleGalaxy()` does not have an implementation for chromatic objects (but I’m looking into that as well),
3. Added a `getCatalog()` method (at least for parametric), and
4. Pass `bandpass` parameters in a custom stamp builder that builds the `bandpass` and passes it to `profile.drawImage(bandpass=bandpass,…)` if `isinstance(profile, ChromaticObject)`.

The bigger issues have to do with the config processing itself. I can get around most of these issues with the custom stamp class by skipping certain features, but I’d like to implement them correctly if possible.

**Issue 1:** One of the final steps in `stamp.BuildStamp()` is to call the builder’s `whiten()` method. The following conditional will fail even with no noise model in the simulation:
```python
def whiten(self, prof, image, config, base, logger):
	...
	if prof is not None and prof.noise is not None:
	...
```
as `ChromaticConvolution.noise` will error if there is not *exactly* 1 object with a covariance spectrum:
```python
@property
def noise(self):
        covspecs = [ obj.covspec for obj in self.obj_list if hasattr(obj, 'covspec') ]
        if len(covspecs) != 1:
           	raise TypeError("Cannot compute noise for ChromaticConvolution for which number "
                            "of convolutants with covspec attribute is not 1.")
	...
```
While I can can overwrite `whiten()` in a custom stamp builder, I believe this could be resolved by allowing `ChromaticConvolution.noise` to be `None` in this case:
```python
    @property
    def noise(self):
        	covspecs = [ obj.covspec for obj in self.obj_list if hasattr(obj, 'covspec') ]
        	if len(covspecs) == 0:
        	    return None
        	elif len(covspecs) != 1:
	...
```
although I am unsure if this breaks anything else. Is there a reason why `ChromaticConvolution`s *must* have noise properties?

**Issue 2:** The trickiest part has been dealing with `StampBuilder.updateSkip()`:
```python
    def updateSkip(self, prof, image, method, offset, config, base, logger):
        if prof is not None and base.get('current_image',None) is not None:
            if image is None:
                prof = base['wcs'].toImage(prof, image_pos=base['image_pos'])
                N = prof.getGoodImageSize(1.)
	    …
```
The final two lines above both fail. 

**(a)** `base[‘wcs’].toImage(prof, ...)` calls the following:
```python
    def toImage(self, arg, **kwargs):
        if isinstance(arg, galsim.GSObject):
            return self.profileToImage(arg, **kwargs)
        else:
            return self.posToImage(arg, **kwargs)
```
which clearly fails as `arg` is not a position. Changing the conditional to `if isinstance(arg, galsim.GSObject) or isinstance(arg, galsim.ChromaticObject):` fixes this problem but the next method to be called `_profileToImage()` is only suited for `GSObject`s:
```python
    def _profileToImage(self, world_profile):
         return galsim._Transform(world_profile, 1./self._scale, 0., 0., 1./self._scale,
                                  flux_ratio=self._scale**2)
```
as `_Transform()` cannot handle `ChromaticObject`s. I resolved this by adding an additional check which calls the main `Transform()` method for `ChromaticObjects` (and adjust the inputs accordingly).

**(b)** These changes allow the code to progress to `N = prof.getGoodImageSize(1.)`. This fails as only `GSObject`’s / `SBProfile`s have this method, but I had hoped to do something similar to this:
```python
if isinstance(prof, ChromaticObject):
	possible_im_sizes = [ obj.getGoodImageSize(scale) for obj in prof.obj_list ]
	im_size = np.max(possible_im_sizes)
```
However, at this stage `prof` is a recursive set of `ChromaticTransformation`s or `ChromaticConvolution`s (and sometimes `ChromaticSum`s of these) that I haven’t been able to reliably unpack in a way useful for the above code. Do you have a suggestion for predicting a good image size of a generic `ChromaticTransformation`, as in principle I care whether the *transformed* galaxy image intersects the main image, correct? Or is the stamp size unchanged from the original `ChromaticObject` and I can use that? (Although I’ve also had trouble getting that to work). 

Sorry for the long post! Do these changes to `chromatic.py`, `stamp.py`, and `wcs.py` seem reasonable? Have I missed any additional changes that must be made to process `ChromaticObjects` consistently with the existing config structure? Using these changes (and ignoring the `updateSkip()` step for the moment) leads to completed runs that have passed some sanity checks by adjusting the `bandpass` parameters.

**Comment by rmjarvis** [comment]
Thanks Spencer.  This is definitely a good start.  The original issue to implement chromatic objects in the config layer is #510.  But I'm inclined to just close that in preference to this issue, since you already have a lot of this worked out it looks like.

To your specific points/questions:
1. It looks like the logic in ChromaticObject's noise property is indeed slightly wrong. I think you're right that if len(covspecs) == 0, then returning None is the right action.
2. For the `_profileToImage` bit, I think just remove the underscore in front of `Transform`.  That was a (slight) efficiency thing, but better to allow chromatic objects here, which the regular `Transform` would do.
3. For `getGoodImageSize` to work you need to evaluate the chromatic object at some specific wavelength.  Usually the `bandpass.effective_wavelength`, which in the config context.  So something like this:
```
if isinstance(prof, galsim.ChromaticObject):
    wave = bandpass.effective_wavelength
    prof0 = prof.evaluateAtWavelength(wave)
    N = prof0.getGoodImageSize(1.)
```
In the config context, we'll probably want to require bandpass to exist in the `image` field I guess.  And maybe store it in `base['bandpass']` like we do with a few other useful values that get used throughout the config processing.

Also, I'd suggest making your changes branched off of the noboost branch, rather than master.  We're about to release v1.6 based on the current master, and then shortly thereafter release v2.0 based on noboost.  (Which will then become the new master.)  So these changes will probably be slated for v2.1.  It will simplify the eventual merge if you start from noboost now.

**Comment by sweverett** [comment]
Thanks for the comments! A few decisions like putting `bandpass` in the custom stamp builder was just to make a quick and dirty test for the TAMU Balrog run. Once that's running I'll work off the noboost branch planning on an eventual pull request.

**Comment by rmjarvis** [comment]
Great.  Thanks!  Please don't hesitate to ask questions here if you run into any more road blocks or things that seem unclear how to proceed.
