### ISSUE TITLE
trouble installing in high sierra

### ISSUE THREAD

**Issue by nrosa007** [GalSim-developers/GalSim#974]
I am working under @msimet and I am trying to install GalSim on High Sierra and I am having trouble with boost. I am getting the following error: 

Checking if we can build against Boost.Python... 
Unable to build a python loadable module with Boost.Python

There is nothing in the $DYLD_LIBRARY_PATH so adding that will not solve the problem. I tried running Scons with CXX=Clang++ and Boost with ./b2 toolset=clang cxxflags="-stdlib=libc++" linkflags="stdlib=libc++" -a  install. I am using systems python 2.7,  Boost 1.67, and GalSim 1.6. Boost itself installs okay but I cannot link  it to GalSim.

**Comment by rmjarvis** [comment]
And now 2.0 is official, so please do try that [installation](https://github.com/GalSim-developers/GalSim/blob/releases/2.0/INSTALL.md).  No boost required.

**Comment by rmjarvis** [comment]
Great!  Glad that worked for you.
