### ISSUE TITLE
v2.0.2 pip install fails with alternate root directory

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#978]
I just tried to install v2.0.2 within an existing conda env that has its own version of pip, so that `pip install ...` only updates files with the environment, rather than the base python install (which is the recommended way to use pip within a conda env AFAIK).  However, this fails with:
```
Collecting galsim
  Downloading https://files.pythonhosted.org/packages/96/a1/4da265850d10f13b0aa99fa20db13a5ee81865fb8e07e7544fd69a3d0c5a/GalSim-2.0.2.tar.gz (36.8MB)
    100% |████████████████████████████████| 36.8MB 737kB/s
  Missing build time requirements in pyproject.toml for galsim from https://files.pythonhosted.org/packages/96/a1/4da265850d10f13b0aa99fa20db13a5ee81865fb8e07e7544fd69a3d0c5a/GalSim-2.0.2.tar.gz#sha256=659ba3d3b0c4fe2b77361822ce89ee1ed6a454fe1a8ed14f7a3e752b52304996: 'wheel'.
  This version of pip does not implement PEP 517 so it cannot build a wheel without 'setuptools' and 'wheel'.
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    warning: no files found matching 'eigency/*.pyd'
    warning: no previously-included files found matching 'eigency/*.cpp'
    warning: no previously-included files matching 'CMakeLists.txt' found under directory 'eigency/eigen_3.2.8/Eigen'

...snip...

    distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/private/var/var', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    Using setuptools version 40.0.0
    Python version =  3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
    Adding eigency to build_dep
    GalSim version is 2.0.2
```
I don't think this is a conda issue since I get the same error if I tell pip to use an alternate root dir:
```
mkdir /tmp/galsim
pip install --root /tmp/galsim galsim
```

**Comment by rmjarvis** [comment]
I think this is probably a bug in eigency.  Possibly coupled somehow to something non-standard about anaconda's build environment.  I was able to reproduce this on one of my anaconda systems, so I'll look into whether there is something I can do in our setup.py to avoid this.

However, in the meanwhile (and in general probably a better solution anyway), try doing
```
conda install eigen
```
first before `pip install galsim`.  I think that should work.  (At least it works on the system where I was able to reproduce this.)

**Comment by dkirkby** [comment]
Thanks @rmjarvis, that solves the `eigen` problem for me also.  I now have a problem with a missing pybind11 dependency:
```
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Using setuptools version 40.0.0
    Python version =  3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
    GalSim version is 2.0.2
    running egg_info
    creating pip-egg-info/GalSim.egg-info
    writing pip-egg-info/GalSim.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/GalSim.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/GalSim.egg-info/entry_points.txt
    writing requirements to pip-egg-info/GalSim.egg-info/requires.txt
    writing top-level names to pip-egg-info/GalSim.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/GalSim.egg-info/SOURCES.txt'
    error: Could not find PyBind11
    Include directory for fftw3 is  /usr/local/include
    PyBind11 is version  2.2.3
    Looking for pybind11 header files:
       /Users/david/.local/include/python3.6m  (no)
       /Users/david/anaconda3/envs/desi/include/python3.6m  (no)
    Could not find pybind11 header files.
    They should have been in one of the following two locations:
        /Users/david/.local/include/python3.6m
        /Users/david/anaconda3/envs/desi/include/python3.6m
```
I don't see `pybind11` in the base conda distribution, but found it in conda-forge:
```
conda install -c conda-forge pybind11
```
After doing this, `pip install galsim` works!

**Comment by dkirkby** [comment]
After my successful `pip install galsim`, I was still not able to `import galsim` because the new install linked the `_galsim` shlib it created against an old version (1.3) of the `libgalsim` shlib it found in my `/usr/local/bin/`:
```
ImportError: dlopen(/Users/david/anaconda3/envs/desi/lib/python3.6/site-packages/galsim/_galsim.cpython-36m-darwin.so, 2): Symbol not found: __ZN3tmv14BandMatrixViewINSt3__17complexIdEELi0EE13conjugateSelfEv
  Referenced from: /usr/local/lib/libgalsim.1.3.dylib
  Expected in: /usr/local/lib/libtmv_symband.0.dylib
 in /usr/local/lib/libgalsim.1.3.dylib
```
This seems like a (minor) installation bug, but was straightforward to fix using:
```
sudo rm /usr/local/lib/libgalsim*
pip uninstall galsim
pip install --no-cache-dir galsim
```
Any idea why this is happening?

**Comment by dkirkby** [comment]
For the record, this is the complete recipe that worked for me:
```
conda install eigen
conda install -c conda-forge pybind11
pip install galsim
```
If you have old versions of galsim installed in your system library search path you may also need to remove them first with:
```
sudo rm /usr/local/lib/libgalsim*
```
or something similar.

Thanks @rmjarvis for making `pip install` possible!!

**Comment by rmjarvis** [comment]
This is the lib file from the old SCons installation.  I couldn't figure out how to delete this automatically from within setup.py.  So for now, it's one of the FAQ items:

**Comment by rmjarvis** [comment]
I'll also add FAQ items about eigen and pybind11 within the conda section.  (And mention the old lib problem again in that context.) 

Thanks for trying this out.

**Comment by dkirkby** [comment]
Ok, sorry I missed that FAQ.  The only thing I would add to what you have already written is that if you get this error, the problem shlib has now been cached by pip, so deleting the old installation is not enough and you need to re-install with `--no-cache-dir`.

**Comment by rmjarvis** [comment]
Good.  Thanks, I'll add that.

**Comment by rmjarvis** [comment]
I added some entries to the FAQ about your above points:
https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(pip,-setup.py)#4-installing-with-conda

**Comment by rmjarvis** [comment]
I assume this is ok to close now.  Please reopen if there is any further action requested about this.
