### ISSUE TITLE
Installing GalSim to Anaconda

### ISSUE THREAD

**Issue by CTugTEZ** [GalSim-developers/GalSim#980]
I installed GalSim via pip but it does not work with anaconda. How can I able to install GalSim to use with anaconda environment? Thanks.

**Comment by rmjarvis** [comment]
Many people do use GalSim with anaconda.  So without more details about the problem you are having, I don't know how to help you.  Perhaps read the Anaconda section of [INSTALL.md](https://github.com/GalSim-developers/GalSim/blob/releases/2.0/INSTALL.md#using-conda) and the [FAQ](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(pip,-setup.py)#4-installing-with-conda) to see if any of those address whatever problem you are having.

**Comment by esheldon** [comment]
It might also be good to note that this works now: `conda install -c conda-forge galsim`
