### ISSUE TITLE
also look for pybind in /usr

### ISSUE THREAD

**Issue by gijzelaerr** [GalSim-developers/GalSim#984]
I have pybind installed (debian package) but galsim can't find it:
```
$  dpkg -L pybind11-dev
/.
/usr
/usr/include
/usr/include/pybind11
/usr/include/pybind11/attr.h
/usr/include/pybind11/cast.h
/usr/include/pybind11/chrono.h
/usr/include/pybind11/common.h
[...]
```

but when i python setup.py galsim i get:
```
Looking for pybind11 header files:
   /home/gijs/.local/include/python2.7  (no)
   /usr/local/include/python2.7  (no)
Could not find pybind11 header files.
They should have been in one of the following two locations:
    /home/gijs/.local/include/python2.7
    /usr/local/include/python2.7
error: Could not find PyBind11
```

**Comment by rmjarvis** [comment]
It looks like your python-installed pybind11 is incompatible with where you actually have the header files.  Those two directories that it looked in are the directories reported by `pybind11.get_include()`.

So perhaps try reinstalling pybind11 with `pip install -U pybind11`.  Or you can install using SCons instead, where there is more flexibility about specifying precisely which directory you want it to look for these files.

**Comment by gijzelaerr** [comment]
hm, that is odd:
```
$  python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybind11
>>> pybind11.__path__
['/usr/lib/python2.7/dist-packages/pybind11']
>>> pybind11.get_include()
'/usr/include'
```

**Comment by gijzelaerr** [comment]
looks like the setup.py script is using a pybind11 from a local egg and not the system wide pybind11:

/scratch/packaging/kern/packaging/build/galsim/.eggs/pybind11-2.2.3-py2.7.egg/pybind11

to clarify, i'm trying to update our debian package for galsim so we actually want to use that specific pybind11.

**Comment by gijzelaerr** [comment]
it works if I modify the code to look for `/usr/include`

**Comment by rmjarvis** [comment]
Is there any action to do here?  Or should this be closed?

**Comment by EiffL** [comment]
:-/ just had the same problem, had to manually go in and change the path to pybind11 headers, which for archlinux are located in `/usr/include`. Not sure how to resolve this automatically though...

**Comment by EiffL** [comment]
So, this is a known issue, pybind is not going to necessarily return the path to the headers. 
https://github.com/pybind/pybind11/issues/421
I haven't found a great way of solving the problem but the PR above adds the standard path `/usr/include` in the list of searched directories.
