### ISSUE TITLE
Fix `PhaseScreenPSF.withGSParams`

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#990]
`PhaseScreenPSF.withGSParams` uses `copy.copy`, which uses pickling, which currently draws the PSF in FFT mode before serializing the state of the PSF object.  This adds unnecessary dependencies on the underlying phase screen `wavefront()` method and unnecessary computation in the case where the PSF is only intended to be drawn using photon-shooting.  See (https://github.com/LSSTDESC/imSim/pull/182).

I think part of the solution here will be to avoid using `copy.copy` in `PhaseScreenPSF.withGSParams`.  The goal is that the result of using `withGSParams` ought to be indistinguishable from creating a new `PhaseScreenPSF` directly but with different gsparams.

This probably also means we should rethink pickling for this class to make sure it's commutative with the rewritten `withGSParams`.  This likely means including the underlying `PhaseScreenList` in the pickle (which could mean a large pickle file, but is really the only correct way to proceed).

I'm also considering making `PhaseScreenPSF.img` and `.finalize` hidden attributes, since these are really implementation details for drawing with `method='FFT'`, and potentially exposing `PhaseScreenPSF._screen_list`, since it seems to be formally required and definitely is part of the PSF definition.

**Comment by rmjarvis** [comment]
Closed via #991
