### ISSUE TITLE
Add wfirst persistence

### ISSUE THREAD

**Issue by chienhaolin** [GalSim-developers/GalSim#992]
Our previous implementation of the wfirst persistence effect is based on the general applyPersistence, which applies constant weighting coefficients that are independent of illumination level on previous images. The new implementation uses the fermi model to describe the dependence of persistence on x (illumination level) and t (time):  A* (x/x0)^a * (t/1000.)^(-r) / (.exp( -(x-x0)/dx ) +1. ). In addition, persistence effect is put after applyNonlinearity and applyIPC.

**Comment by rmjarvis** [comment]
Closed via #1011.  Thanks Chien-Hao.
